force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>First National Employee Information used to facilitate tracking of employee community interactions</description>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <description>Department Cost Center for the Employee</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee Email Address</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Employee First Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Employee Last Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Logon_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Logon_Name__c</fullName>
    <description>Local Area Network (LAN) ID associated with User</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User Logon Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Board_Membership__c/Employee_Board_Membership__c.object-meta.xml
<CustomObject>
    <description>Tracks FNBO employee involvement with Non Profit organization boards of directors</description>
    <label>Employee Board Membership</label>
    <nameField>
        <displayFormat>EMB-{00000}</displayFormat>
        <label>Employee Board Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Board Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Board_Membership__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Board_Membership__c/fields/Employee_Market__c.field-meta.xml
<CustomField>
    <fullName>Employee_Market__c</fullName>
    <label>Employee Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Des Moines</fullName>
            </value>
            <value>
                <fullName>Great Plains</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Lincoln</fullName>
            </value>
            <value>
                <fullName>Omaha</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Board_Membership__c/fields/Organization_Other__c.field-meta.xml
<CustomField>
    <fullName>Organization_Other__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization Other</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Board_Membership__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipLabel>Employee Board Memberships</relationshipLabel>
    <relationshipName>Employee_Board_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/Activity_Date_Intranet__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date_Intranet__c</fullName>
    <description>Date of activity for Intranet site.  (Here so users who enter will not have to enter both date and time.  Will be converted to Date_and_time__c in Volunteer site backend apex class.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter date of Activity</inlineHelpText>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <label>Duration (hours)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Employee_Board_Membership__c.field-meta.xml
<CustomField>
    <fullName>Employee_Board_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Connect to your Board Membership record, if your activity is related to your Board Service</inlineHelpText>
    <label>Employee Board Membership</label>
    <referenceTo>Employee_Board_Membership__c</referenceTo>
    <relationshipLabel>Volunteer Activities</relationshipLabel>
    <relationshipName>Volunteer_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Employee_Email_Intranet__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email_Intranet__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Type the email address of the employee who volunteered</inlineHelpText>
    <label>Employee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <description>Employee&#39;s user login.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Employee_Market__c.field-meta.xml
<CustomField>
    <fullName>Employee_Market__c</fullName>
    <label>Employee Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Lincoln</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
            <value>
                <fullName>Omaha</fullName>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
            </value>
            <value>
                <fullName>Fremont</fullName>
            </value>
            <value>
                <fullName>Kearney</fullName>
            </value>
            <value>
                <fullName>North Platte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Event_Summary__c.field-meta.xml
<CustomField>
    <fullName>Event_Summary__c</fullName>
    <defaultValue>&quot;&lt;provide complete activity details here&gt;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Organization_Other__c.field-meta.xml
<CustomField>
    <fullName>Organization_Other__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Fill this in if your organization does not exist in our list.  Please be sure to blank out the Volunteer Organization name if you use this, however.</inlineHelpText>
    <label>Organization Other</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Sessions__c.field-meta.xml
<CustomField>
    <fullName>Sessions__c</fullName>
    <label>Number of Sessions</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Events__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Events__c</fullName>
    <label>Activity Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beautification/Cleaning/Painting/Gardening</fullName>
            </value>
            <value>
                <fullName>Business Assistance</fullName>
            </value>
            <value>
                <fullName>CRA Community Contact</fullName>
            </value>
            <value>
                <fullName>CRA Community Outreach</fullName>
            </value>
            <value>
                <fullName>Education/Training/Tutoring</fullName>
            </value>
            <value>
                <fullName>Faith-based</fullName>
            </value>
            <value>
                <fullName>Fundraising/Event Management</fullName>
            </value>
            <value>
                <fullName>Mentoring/leadership development</fullName>
            </value>
            <value>
                <fullName>Professional Skills</fullName>
            </value>
            <value>
                <fullName>Walks/Runs/Parades/Booth/Table</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Building/Construction/Rehabilitation/Home Maintenance</fullName>
            </value>
            <value>
                <fullName>Community Event Participation</fullName>
            </value>
            <value>
                <fullName>Food serving/distributing/sorting/delivering</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Health Care and Social Services</fullName>
            </value>
            <value>
                <fullName>Disaster/Emergency Services</fullName>
            </value>
            <value>
                <fullName>Civic Participation/Political</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_VolunteerTrackingExtension.cls
@istest
    public class Test_VolunteerTrackingExtension {
         ApexPages.StandardController sc;
         public static Volunteer_Activity__c vact = new Volunteer_Activity__c();  
         public static Integer CurrYear = date.today().year(); // Two variables here for restricting board entries to current year only. 
         public static  ApexPages.StandardController stdvact = new ApexPages.StandardController(vact);
         public static  VolunteerTrackingExtension vte = new VolunteerTrackingExtension(stdvact);     
         public Employee__c employee;
         public static String emp = '1241';
        
         public Test_VolunteerTrackingExtension(ApexPages.StandardController standardController) {
             sc = standardController;
         }
         /*
         public static testMethod void BoardReportingControllerTest() {
             BoardReportingController b = new BoardReportingController();
         } */
         @TestSetup
        public static void setup() {
            
        }
         @istest
         public static void InitNullTest() {
              vte.Init();
              String vteInitURL = vte.Init().getURL();
              System.assertEquals('/apex/volunteersignin',vteInitURL);
         }
         
         @istest
         public static void InitNotNullTest() {
              Employee__c employee = new Employee__c();
                employee.Cost_Center__c = '100010'; 
                employee.Last_Name__c = 'Mouse';
                employee.First_Name__c = 'Mickey';
                employee.Email__c = 'mmouse@gmail.com';
                employee.User_Logon_Name__c = emp;
              insert employee;     
              apexpages.currentpage().getparameters().put('q' , '1241');
              vte.Init();
         }
    
         @istest
         public static void signin_Usecase1_User_exists() {
              setEmployee();
              vte.q = emp;
              String signinURL = vte.signin().getURL();
              System.assertEquals('/apex/volunteerreporting',signinURL);
    
        }
    
         @istest
         public static void signin_Usecase2_User_not_exist() {
              setEmployee();
              vte.q = '994994';
              String signinURL = vte.signin().getURL();
              System.assertEquals('/apex/volunteerreporting',signinURL);
    
        }
    
        @istest
        public static void viewVolunterReporting() {
             Employee__c employee = new Employee__c();
                employee.Cost_Center__c = '100010';
                employee.Last_Name__c = 'Mouse';
                employee.First_Name__c = 'Mickey';
                employee.Email__c = 'mmouse@gmail.com';
                employee.User_Logon_Name__c = emp;
            insert employee;
            vte.employee = employee;
            String VolReportingURL = vte.viewVolunteerReporting().getURL();
            System.assertEquals('/apex/VolunteerReporting?q=1241',VolReportingURL);
        }
    
         @istest
         public static void test_viewVolunteerAddMore() {
              apexpages.currentpage().getparameters().put('Market' , 'Omaha');     
              String VolAddMoreURL = vte.VolunteerAddMore().getURL();
              System.assertEquals('/apex/volunteeraddition',VolAddMoreURL);
        }
    
         @istest
         public static void test_viewVolFinish() {
              String VolFinishURL = vte.viewVolFinish().getURL();
              System.assertEquals('/apex/volunteerthankyou',VolFinishURL);
        }
    
         @istest
         public static void test_viewVolSignin() {
              String SignInURL = vte.viewVolunteerSignIn().getURL();
              System.assertEquals('/apex/volunteersignin',SignInURL);
        }
    
        @istest
         public static void test_getemployee() {
              setemployee();
              apexpages.currentpage().getparameters().put('q' , emp);
              Employee__c chkempl = vte.getemployee();
              System.assertEquals(emp,chkempl.user_logon_name__c);
        }
    
         @istest
         public static void test_viewVolActivity() {
              apexpages.currentpage().getparameters().put('q' , emp);
              String ActivityURL = vte.viewVolunteerActivity().getURL();
              System.assertEquals('/apex/volunteeraddition',ActivityURL);
        }
    
         @istest
         public static void test_addVolActivity_allFieldsFilled() {
              createVactAllFilledIn();
              String AddFinishURL = vte.addVolunteerActivity().getURL();
              System.assertEquals('/apex/volunteeraddfinish',AddFinishURL);
        }

         @istest
         public static void test_addVolActivity_NoOrg() {
              createVactNoOrg();
              vte.addVolunteerActivity();
         //Nothing to assert here.  This will return null because of invalid Volunteer_Activity__c data.
        }

         @istest
         public static void test_addVolActivity_BlankData() {
              createVactNoSummary();
              vte.addVolunteerActivity();
         //Nothing to assert here.  This will return null because of invalid Volunteer_Activity__c data.
        }

         @istest
         public static void test_addVolActivity_OtherOrgBlankVolOrg() {
              createVactOtherOrg();
              String AddFinishURL = vte.addVolunteerActivity().getURL();
              System.assertEquals('/apex/volunteeraddfinish',AddFinishURL);
        }

         @istest
         public static void test_addVolActivity_OtherOrgThatExists() {
              createVactOtherOrgthatExists();
              String AddFinishURL = vte.addVolunteerActivity().getURL();
              System.assertEquals('/apex/volunteeraddfinish',AddFinishURL);
        }

         @istest
         public static void test_addVolActivity_OtherOrgAndVolOrg() {
              createVactOtherOrgAndVolOrg();
              String AddFinishURL = vte.addVolunteerActivity().getURL();
              System.assertEquals('/apex/volunteeraddfinish',AddFinishURL);
        }

         @istest
         public static void test_viewVolAddFinish() {
              String AddFinishURL = vte.viewVolunteerAddFinish().getURL();
              System.assertEquals('/apex/volunteeraddfinish',AddFinishURL);
        }

         @istest
         public static void test_getEmployeeActivitiesNoActivities() {
              vte.getEmployeeVolActivities();
         //Nothing to assert here.  This will return null because of no activities created.
        }

         @istest
         public static void test_getEmployeeActivitiesWithActivities() {
         createVactAndInsert();
         Employee__c fillemployee = new Employee__c();
             fillemployee.Cost_Center__c = '100010'; 
             fillemployee.Last_Name__c = 'Mouse';
             fillemployee.First_Name__c = 'Mickey';
             fillemployee.Email__c = 'mmouse@gmail.com';
             fillemployee.User_Logon_Name__c = emp;
         vte.employee = fillemployee;
         vte.index = 0;
         list<Volunteer_Activity__c> volactlist = new list<volunteer_activity__c>();
         volactlist = vte.getEmployeeVolActivities();
                 
        }

         @istest
         public static void test_getEmployeeActivitiesWithActivitiesOtherOrg() {
         createVactAndInsertOtherOrg();
         Employee__c fillemployee = new Employee__c();
             fillemployee.Cost_Center__c = '100010'; 
             fillemployee.Last_Name__c = 'Mouse';
             fillemployee.First_Name__c = 'Mickey';
             fillemployee.Email__c = 'mmouse@gmail.com';
             fillemployee.User_Logon_Name__c = emp;
         vte.employee = fillemployee;
         vte.index = 0;
         list<Volunteer_Activity__c> volactlist = new list<volunteer_activity__c>();
         volactlist = vte.getEmployeeVolActivities();
                 
        }

         @istest
         public static void test_getEmployeeActivitiesWithActivitiesOtherOrgThatExists() {
         createVactAndInsertOtherOrgExists();
         Employee__c fillemployee = new Employee__c();
             fillemployee.Cost_Center__c = '100010'; 
             fillemployee.Last_Name__c = 'Mouse';
             fillemployee.First_Name__c = 'Mickey';
             fillemployee.Email__c = 'mmouse@gmail.com';
             fillemployee.User_Logon_Name__c = emp;
         vte.employee = fillemployee;
         vte.index = 0;
         list<Volunteer_Activity__c> volactlist = new list<volunteer_activity__c>();
         volactlist = vte.getEmployeeVolActivities();
                 
        }

        @istest
        public static void setEmployee() {
            Employee__c employee = new Employee__c();
                employee.Cost_Center__c = '100010'; 
                employee.Last_Name__c = 'Mouse';
                employee.First_Name__c = 'Mickey';
                employee.Email__c = 'mmouse@gmail.com';
                employee.User_Logon_Name__c = emp;
            insert employee;
            vte.setEmployee(employee);
        }
    
        @istest
        public static void createVactAllFilledIn() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vte.vact = new Volunteer_Activity__c();  //DAG_2019_01_22 Change this from Employee_Board_Membership__c.
            vte.vact.Volunteer_Organization__c = org_id;
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = 'Helped with Food Drive';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    

        @istest
        public static void createVactNoOrg() {
            setemployee();
            vte.vact = new Volunteer_Activity__c();
            vte.vact.volunteer_organization__c = null;
            vte.vact.organization_other__c = '';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = 'Helped with Food Drive';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    

        @istest
        public static void createVactNoSummary() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vte.vact = new Volunteer_Activity__c();
            vte.vact.Volunteer_Organization__c = org_id;
            vte.vact.organization_other__c = '';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = '';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = null;
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    
        
        @istest
        public static void createVactOtherOrg() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            Volunteer_Organization__c new_organization = new Volunteer_Organization__c();
            new_organization.Name = 'New Organization';
            insert new_organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vte.vact = new Volunteer_Activity__c();
            vte.vact.organization_other__c = 'Yosemite Sam Politeness School';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = 'Helped with Food Drive';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    
        
        @istest
        public static void createVactOtherOrgThatExists() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vte.vact = new Volunteer_Activity__c();
            vte.vact.organization_other__c = 'Food For Life';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = 'Helped with Food Drive';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    

        @istest
        public static void createVactOtherOrgAndVolOrg() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            Volunteer_Organization__c new_organization = new Volunteer_Organization__c();
            new_organization.Name = 'New Organization';
            insert new_organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vte.vact = new Volunteer_Activity__c();
            vte.vact.organization_other__c = 'Yosemite Sam Politeness School';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vte.vact.Recordtypeid = iarecordtype[0].id;
            vte.vact.Employee_Market__c = 'Omaha';
            vte.vact.name = 'Helped with Food Drive';
            vte.vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vte.vact.Volunteer_Events__c = 'Animal Services';
            vte.vact.Duration_hours__c = 4;
            vte.vact.Sessions__c = 1;
            vte.vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vte.vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vte.vact.Employee_ID__c =emp;
        }    

        @istest
        public static void createVactAndInsert() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'Food for Life';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'Food for Life'].id;   
            setemployee();
            vact = new Volunteer_Activity__c();
            vact.Volunteer_Organization__c = org_id;
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vact.Recordtypeid = iarecordtype[0].id;
            vact.Employee_Market__c = 'Omaha';
            vact.name = 'Helped with Food Drive';
            vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Volunteer_Events__c = 'Animal Services';
            vact.Duration_hours__c = 4;
            vact.Sessions__c = 1;
            vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vact.Employee_ID__c =emp;
            insert vact;
        }    

        @istest
        public static void createVactAndInsertOtherOrg() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'New Organization';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'New Organization'].id;   
            setemployee();
            vact = new Volunteer_Activity__c();
            vact.Organization_Other__c = 'Yosemite Sam Politeness School';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vact.Recordtypeid = iarecordtype[0].id;
            vact.Employee_Market__c = 'Omaha';
            vact.name = 'Helped with Food Drive';
            vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Volunteer_Events__c = 'Animal Services';
            vact.Duration_hours__c = 4;
            vact.Sessions__c = 1;
            vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vact.Employee_ID__c =emp;
            insert vact;
        }
        @istest
        public static void createVactAndInsertOtherOrgExists() {
            Volunteer_Organization__c organization = new Volunteer_Organization__c();
            organization.Name = 'New Organization';
            insert organization;
            ID org_id = [select id from Volunteer_Organization__c where name = 'New Organization'].id;   
            Volunteer_Organization__c existing_organization = new Volunteer_Organization__c();
            existing_organization.Name = 'Yosemite Sam Politeness School';
            insert existing_organization;            
            setemployee();
            vact = new Volunteer_Activity__c();
            vact.Organization_Other__c = 'Yosemite Sam Politeness School';
            list<RecordType> iarecordtype = [select id from recordtype where sobjecttype = 'Volunteer_Activity__c' and name = 'Intranet Activity Record' limit 1];
            vact.Recordtypeid = iarecordtype[0].id;
            vact.Employee_Market__c = 'Omaha';
            vact.name = 'Helped with Food Drive';
            vact.Date_and_Time__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Activity_Date_Intranet__c = date.newInstance(date.today().year(), date.today().month(), date.today().day());
            vact.Volunteer_Events__c = 'Animal Services';
            vact.Duration_hours__c = 4;
            vact.Sessions__c = 1;
            vact.Event_Summary__c = 'Did a lot of heavy lifting';
            vact.Employee_Email_Intranet__c = 'mmouse@gmail.com';
            vact.Employee_ID__c =emp;
            insert vact;
        }            
        
    }