force-app/main/default/objects/Transaction_Security_Code__c/Transaction_Security_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Transaction Security Code</label>
</CustomObject>

force-app/main/default/objects/Transaction_Security_Code__c/fields/Max_Export__c.field-meta.xml
<CustomField>
    <fullName>Max_Export__c</fullName>
    <label>Max Export</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityExportNotificaPolicyCondition.cls
global class OpportunityExportNotificaPolicyCondition implements TxnSecurity.PolicyCondition {

    public boolean evaluate(TxnSecurity.Event e) {
        //get the user & profile        
        User u = [SELECT Id, Username, UserRoleId, ProfileId FROM User where Id =: e.userId];
        Profile p = [SELECT id, Name FROM Profile WHERE id =: u.ProfileId];
       
       //Test 1: return 'false' if the user profile is a SysAdmin or Integration User       
       switch on p.Name {
           when 'System Administrator' {return false; }
           when 'Custom System Admin' {return false; }
           when 'Integration User' {return false; }
           when 'Enterprise Business Intelligence' {return false; }
       }
       
       //get number of records
       Integer numberOfRecords = Integer.valueOf(e.data.get('NumberOfRecords'));
       
       //Test 2: for non-SysAdmin or IntegrationUser, evaluate the number of records
       Integer maxExport = Transaction_Security_Code__c.getInstance('maxExport').Max_Export__c.intValue();
       if(numberOfRecords > maxExport)
       {
            return true;   
       }
       else
       {
           return false; 
       } 
   }
}