force-app/main/default/objects/IMPAX__c/IMPAX__c.object-meta.xml
<CustomObject>
    <description>Contains information record by Wealth Management from prospects and existing customers - aligns with the Bank&#39;s strategy on IMPAX sales techniques</description>
    <label>IMPAX</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IMPAX Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMPAX</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IMPAX__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IMPAX</relationshipLabel>
    <relationshipName>IMPAX</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IMPAXRelatedList_Controller.cls
// Author: Dallas Grafton
// Date Created/Modified: 01.04.2018
// Project: IMPAX VF page
// Purpose: 
//

public class IMPAXRelatedList_Controller {

    private list<IMPAX__c> IMPAX = new List<IMPAX__c>();
    private boolean renderPage = True;
    
    public IMPAXRelatedList_Controller(ApexPages.StandardController controller) {
        
                try{
            // SOQL statements to build sObject lists                      
            IMPAX = [SELECT Id, Name, Account__c, Account__r.Name, CreatedById, LastModifiedById, CreatedDate, LastModifiedDate
                    FROM IMPAX__c 
                    WHERE Account__c = :ApexPages.currentPage().getParameters().get('id')
                    LIMIT 50000];        
      
                } catch (exception e) {
            
           renderPage = false;
                }      
    }
    
        public list<IMPAX__C> getIMPAX() {
                return IMPAX;
    }
    
}