force-app/main/default/objects/IMPAX__c/IMPAX__c.object-meta.xml
<CustomObject>
    <description>Contains information record by Wealth Management from prospects and existing customers - aligns with the Bank&#39;s strategy on IMPAX sales techniques</description>
    <label>IMPAX</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IMPAX Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMPAX</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IMPAX__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IMPAX</relationshipLabel>
    <relationshipName>IMPAX</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IMPAXRelatedList_Controller_Test.cls
// Author: Dallas Grafton
// Date Created/Modified: 01/24/2018
// Project: IMPAX Page

@isTest
public class IMPAXRelatedList_Controller_Test {
    
    static testMethod void IMPAXRelatedList_Controller_Test() {
        List<TriggerSupport__c> triggerSupportSettings = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSetting = new TriggerSupport__c();
        accountTriggerSetting.Name = 'Account';
        accountTriggerSetting.TriggerIsDisabled__c = true;
        
        triggerSupportSettings.add(accountTriggerSetting);
        
        insert triggerSupportSettings;

        RecordType RecTypeID = [select id, name from Recordtype where sobjecttype = 'Account' and name = 'Person Account'];
        System.AssertEquals('01230000000sSnGAAU', RecTypeId.Id);

        Account acct = new Account(firstname = 'TestAccount', lastname = 'IMPAXRL', recordTypeId = RecTypeID.id);
        insert acct;
        
        IMPAX__c IMPAXTest = new IMPAX__c(Account__c = acct.Id);
        insert IMPAXTest;
        
        ApexPages.currentPage().getParameters().put('id',acct.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        IMPAXRelatedList_Controller ce = new IMPAXRelatedList_Controller(sc);
        
        test.startTest();
        
        List<IMPAX__c> IMPAXRecords = ce.getIMPAX();
        
        System.assertNotEquals(null, IMPAXRecords);
        
        test.stopTest();

        accountTriggerSetting.TriggerIsDisabled__c = false;
        update triggerSupportSettings;
        
    }
}