force-app/main/default/objects/NAICS__c/NAICS__c.object-meta.xml
<CustomObject>
    <description>Assigns a NAICS code based on the industry of the account entity</description>
    <label>NAICS</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NAICS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NAICS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAICS__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAICS__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NAICS Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/naicssearchcontroller.cls
public with sharing class naicssearchcontroller {  
   public list <NAICS__c> naics {get;set;}  
   public string searchstring {get;set;}  
   public naicssearchcontroller(ApexPages.StandardController controller) {  
   }  
   public void search(){  
     string searchquery='select id,Name,NAICS_Code__c,Description__c from NAICS__c where NAICS_Code__c like \'%'+searchstring+'%\' OR Description__c like \'%'+searchstring+'%\' Limit 80';  
     naics= Database.query(searchquery);  
   }  
   public void clear(){  
   naics.clear();  
   }  
 }