force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/FIC_Survey_Application__c.field-meta.xml
<CustomField>
    <fullName>FIC_Survey_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FIC Survey Application</label>
    <referenceTo>FIC_Survey_Application__c</referenceTo>
    <relationshipLabel>Community Investments</relationshipLabel>
    <relationshipName>Community_Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Community_Givings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/FIC_Survey_Application__c.object-meta.xml
<CustomObject>
    <description>Stores data received from Grant and Donation applications submitted by non profit organizations in our communitieis</description>
    <label>FIC Survey Application</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>FIC Survey Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIC Survey Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Update_Code__c</fullName>
    <description>Code passed from community investment trigger to allow updates of fields when the Processed flag is set to true (record already been processed and copied to Community Investment).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Update Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateFICNonProfitOrg.cls
//Author:  Dallas Grafton
//Date:  2019-03-13
//VersionOne Story:  S-28706
//Purpose:  Update the non-profit org field on FIC Survey application if it is changed on the corresponding community investment.

public without sharing class updateFICNonProfitOrg {

    private final Map<Id, Community_Giving__c> oldMap;
    private final List<Community_Giving__c> newCommGiv;
    
    public static void compareNonProfitOrg(Map<Id, Community_Giving__c> oldMap, 
                                            List<Community_Giving__c> newCommGiv) {                                            
       for(Community_Giving__c newComm: newCommGiv) {
          Community_Giving__c oldComm = oldMap.get(newComm.id);
          if (newComm.Non_Profit_Organization__c != oldComm.Non_Profit_Organization__c) {
             if (newComm.FIC_Survey_Application__c != null) {
                updateFIC(newComm);
             }
          }
       }
    }
 
    public static void updateFIC(Community_Giving__c commGivtogetFIC) {
       FIC_Survey_Application__c appToUpdate = [SELECT id, name, Non_Profit_Organization__c from FIC_Survey_Application__c where id = :commGivtogetFIC.FIC_Survey_Application__c];
       appToUpdate.Non_Profit_Organization__c = commGivtogetFIC.Non_Profit_Organization__c;
       appToUpdate.Update_Code__c = '37';
       update appToUpdate;
    }
}