force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Requested__c</fullName>
    <label>Amount Requested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/FIC_Survey_Application__c.field-meta.xml
<CustomField>
    <fullName>FIC_Survey_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FIC Survey Application</label>
    <referenceTo>FIC_Survey_Application__c</referenceTo>
    <relationshipLabel>Community Investments</relationshipLabel>
    <relationshipName>Community_Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Community_Givings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Community_Giving__c/recordTypes/Sponsorship.recordType-meta.xml
<RecordType>
    <fullName>Sponsorship</fullName>
    <active>true</active>
    <label>Sponsorship</label>
</RecordType>

force-app/main/default/objects/FIC_Survey_Application__c/FIC_Survey_Application__c.object-meta.xml
<CustomObject>
    <description>Stores data received from Grant and Donation applications submitted by non profit organizations in our communitieis</description>
    <label>FIC Survey Application</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>FIC Survey Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIC Survey Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Requested__c</fullName>
    <label>Amount Requested</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Briefly_Describe_Community_Issue__c.field-meta.xml
<CustomField>
    <fullName>Briefly_Describe_Community_Issue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Briefly Describe Community Issue</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Briefly_Describe_Community_Success__c.field-meta.xml
<CustomField>
    <fullName>Briefly_Describe_Community_Success__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Briefly Describe Community Success</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Conversion__c.field-meta.xml
<CustomField>
    <fullName>Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process Survey Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Conversion_Type__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Type__c</fullName>
    <label>Community Investment Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Flood Relief</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/First_National_Bank_Request__c.field-meta.xml
<CustomField>
    <fullName>First_National_Bank_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreed to Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_City__c.field-meta.xml
<CustomField>
    <fullName>Organization_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Program_Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Program_Event_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program/Event Description</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Program_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Event_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program/Event Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Provide_Name_and_Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Provide_Name_and_Service_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Provide Name and Service Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Update_Code__c</fullName>
    <description>Code passed from community investment trigger to allow updates of fields when the Processed flag is set to true (record already been processed and copied to Community Investment).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Update Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/updateFICNonProfitOrg_Test.cls
@isTest
public class updateFICNonProfitOrg_Test {
   @isTest
    public static void compareNonProfitOrg_UpdateNonProfitOrg() {
              
        Id grantRecordTypeId = [SELECT Id
                                FROM RecordType
                                WHERE sObjectType = 'FIC_Survey_Application__c'
                                AND Name = 'Donation/Sponsorship'
                                LIMIT 1].id;
        
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;

        Volunteer_Organization__c volOrgII = new Volunteer_Organization__c(name = 'test Vol OrgII');
        insert volOrgII;
        
        FIC_Survey_Application__c ficsurveyAppDon = new FIC_Survey_Application__c(Market__c = 'Omaha',
                                                                                  Organization_City__c = 'Omaha',
                                                                                  RecordTypeId = grantRecordTypeId,
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Donation',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppDon;
        
        Blob attachbodyDon = Blob.valueOf('Attach Body Blob');
        
        Attachment attachDon = new Attachment(parentId = ficsurveyAppDon.id,
                                              name = 'attachment test',
                                              body = attachbodyDon);
        
        insert attachDon;
        
        ficsurveyAppDon.Conversion__c = True;
        
        update ficsurveyAppDon;
        
        Community_Giving__c commGivingDon = [SELECT Id, FIC_Survey_Application__c, Market__c, Non_Profit_Organization__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1];
        
        System.assertEquals(ficsurveyAppDon.Id, commGivingDon.FIC_Survey_Application__c);
        System.assertEquals('Omaha', commGivingDon.Market__c);
        
        Id commGivingDonId = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1].Id;
        
        Id commGivingDonAttachment = [SELECT Id, ParentId
                                      FROM Attachment
                                      WHERE ParentId =: commGivingDonId].ParentId;
        
        Id ficsurveyAppDonCommGivingId = [SELECT Id, Community_Investment__c
                                          FROM FIC_Survey_Application__c
                                          WHERE Community_Investment__c =: commGivingDonId].Community_Investment__c;
        
        System.assertEquals(ficsurveyAppDonCommGivingId, commGivingDonId);
        System.assertEquals(commGivingDonAttachment, commGivingDonId);
        
        Community_Giving__c commGivingDonII = [SELECT Id, FIC_Survey_Application__c, Market__c, Non_Profit_Organization__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1];

        commGivingDonII.Non_Profit_Organization__c = VolOrgII.id;
        
        update commGivingDonII;
      //updateFICNonProfitOrg.compareNonProfitOrg(Trigger.oldMap, Trigger.new);
        
        FIC_Survey_Application__c checkFICNonProfit1 = [SELECT id, name, Non_Profit_Organization__c, update_code__c from FIC_Survey_Application__c where id =: ficsurveyAppDon.Id];
        System.assertEquals(VolOrgII.id, checkFICNonProfit1.Non_Profit_Organization__c);
        System.assertEquals('XX', checkFICNonProfit1.Update_Code__c);
    }
   @isTest
    public static void compareNonProfitOrg_UpdateAnotherField() {
              
        Id donRecordTypeId = [SELECT Id
                                FROM RecordType
                                WHERE sObjectType = 'FIC_Survey_Application__c'
                                AND Name = 'Donation/Sponsorship'
                                LIMIT 1].id;
        
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;

        Volunteer_Organization__c volOrgII = new Volunteer_Organization__c(name = 'test Vol OrgII');
        insert volOrgII;
        
        FIC_Survey_Application__c ficsurveyAppDon = new FIC_Survey_Application__c(Market__c = 'Omaha',
                                                                                  Organization_City__c = 'Omaha',
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Donation',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id,
                                                                                  RecordTypeid = donRecordTypeId);
        Insert ficsurveyAppDon;
        
        ficsurveyAppDon.Conversion__c = True;
        
        update ficsurveyAppDon;
        
        Community_Giving__c commGivingDon = [SELECT Id, FIC_Survey_Application__c, Non_Profit_Organization__c, Market__c
                            FROM Community_Giving__c WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1];
        
        System.assertEquals(ficsurveyAppDon.Id, commGivingDon.FIC_Survey_Application__c);
        System.assertEquals('Omaha', commGivingDon.Market__c);
        
        commGivingDon.Market__c = 'North Platte';
        
        update commGivingDon;
        
        Community_Giving__c checkCommGiv = [SELECT id, name, Market__c from Community_Giving__c where id =: commGivingDon.Id];
        FIC_Survey_Application__c checkFICNonProfit = [SELECT id, name, Market__c from FIC_Survey_Application__c where id =: ficsurveyAppDon.Id];
        
        System.assertEquals('North Platte', checkCommGiv.Market__c);
        System.assertEquals('Omaha', checkFICNonProfit.Market__c);
    }
   @isTest
    public static void compareNonProfitOrg_NoFIC() {
              
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;

        Volunteer_Organization__c volOrgII = new Volunteer_Organization__c(name = 'test Vol OrgII');
        insert volOrgII;
        
        Community_Giving__c CommGivingDon = new Community_Giving__c(Market__c = 'Omaha',
                                                                 Amount_Requested__c = 1000,
                                                                 Non_Profit_Organization__c = volOrg.Id);
        Insert CommGivingDon;
        
        commGivingDon.Market__c = 'North Platte';
        
        update commGivingDon;
        
        Community_Giving__c checkCommGiv = [SELECT id, name, Market__c from Community_Giving__c where id =: commGivingDon.Id];
        
        System.assertEquals('North Platte', checkCommGiv.Market__c);
    }                
}