force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/Grant_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Reviewed_by_MCIC_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_by_MCIC_Decision__c</fullName>
    <inlineHelpText>by MCIC ($501-$9,999)</inlineHelpText>
    <label>Reviewed by MCIC Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Community_Giving__c/recordTypes/Sponsorship.recordType-meta.xml
<RecordType>
    <fullName>Sponsorship</fullName>
    <active>true</active>
    <label>Sponsorship</label>
</RecordType>

force-app/main/default/objects/Community_Survey__c/Community_Survey__c.object-meta.xml
<CustomObject>
    <description>Contains the survey data provided by non profit organziations after they have been approved for grants and donations.</description>
    <label>Community Survey Email Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Survey Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Survey__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipLabel>Community Survey Emails</relationshipLabel>
    <relationshipName>Community_Survey_Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/Date_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/Email_body__c.field-meta.xml
<CustomField>
    <fullName>Email_body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/From_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>From Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/AtoDecisionTemplateCtrl_Test.cls
@isTest
public class AtoDecisionTemplateCtrl_Test {
    @istest
           static void testme(){
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
            insert CMG ;
               
               
            Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
               
               
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
               d.filecount='1';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
              // string email='Test@gmail.com';
               //d.calFromAddress('Test@gmail.com');
               d.Uploaddoc();
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
               
        
    }
    
    @istest 
    static void testusecase2(){
      Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
            insert CMG ;
        Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
           list<id>Attis=new list<id>();
           for(Attachment a1:Atch){
              Attis.add(a1.id);
                }
                 system.assertequals(true,attis.size()>0);
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
               d.filecount='2';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
               d.addattachment();
               d.attachesid=Attis;
               //d.templateName='Grant_Decline_Template';
              // d.conObjMarket=new contact();
             // d.templateName = 'Grant_Decline_Template';
             list<Messaging.Emailfileattachment>Sendattach=new  list<Messaging.Emailfileattachment>();
                Messaging.Emailfileattachment ME=new Messaging.Emailfileattachment();
                  ME.setfilename(Atch[0].name);
                    ME.setbody(Atch[0].body);
                     Sendattach.add(ME);
        system.assertequals(true,Sendattach.size()>0);
         //taking away due to test failure
         //d.sendemail();
 
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
               
          
    }
    @istest static void recordtype(){
        list<recordtype>rec=[select id,name,DeveloperName from recordtype where DeveloperName='Donation'];
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.RecordTypeid=rec[0].id;
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
            insert CMG ;
        
        Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
               
               
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
               d.filecount='1';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
              // string email='Test@gmail.com';
               //d.calFromAddress('Test@gmail.com');
               d.Uploaddoc();
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
    } 
@istest static void recordtype1(){
        list<recordtype>rec=[select id,name,DeveloperName from recordtype where DeveloperName='Sponsorship'];
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.RecordTypeid=rec[0].id;
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
            insert CMG ;
    
    
    Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
               
               
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
    
 
               d.filecount='1';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
              // string email='Test@gmail.com';
               //d.calFromAddress('Test@gmail.com');
               d.Uploaddoc();
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
    }     
       
@istest static void recordtype3(){
        list<recordtype>rec=[select id,name,DeveloperName from recordtype where DeveloperName='Sponsorship'];
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.RecordTypeid=rec[0].id;
        CMG.Reviewed_by_MCIC_Decision__c='Denied';
            insert CMG ;
    Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
               
               
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
    
 
               d.filecount='1';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
              // string email='Test@gmail.com';
               //d.calFromAddress('Test@gmail.com');
               d.Uploaddoc();
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
    }  
    @istest static void recordtype4(){
        list<recordtype>rec=[select id,name,DeveloperName from recordtype where DeveloperName='Donation'];
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.RecordTypeid=rec[0].id;
        CMG.Reviewed_by_MCIC_Decision__c='Denied';
            insert CMG ;
        Community_Survey__c ficSurObj = new Community_Survey__c();
            //ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  ='Testbody';
            ficSurObj.From_Email__c  ='Test@gmail.com';
            ficSurObj.To_Email__c='Test1@gmail.com';
            insert ficSurObj;
            
    list<Community_Giving__c>CM=[Select id,Market__c,requestor_Email__c,Grant_Contact_Email__c,Reviewed_by_MCIC_Decision__c from Community_Giving__c];
               system.assertequals(true,CM.size()>0);
               Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
               
         Attachment a=new Attachment(name='Unit Test Attachment',body=bodyBlob,parentId=CMG.id,IsPrivate=false);
               insert a;
               
             list<Attachment>Atch=[select id,name,body,isprivate from Attachment where id=:a.id];
               system.assertequals(true,atch.size()>0);
               
               
              // string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        AtoDecisionTemplateCtrl d  = new AtoDecisionTemplateCtrl(con);
    
 
               d.filecount='1';
               d.countlist=new list<selectoption>();
               d.attach=Atch;
               d.Attnames=new list<string>();
              // string email='Test@gmail.com';
               //d.calFromAddress('Test@gmail.com');
               d.Uploaddoc();
               
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        //pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
    }   
}