force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Requested__c</fullName>
    <label>Amount Requested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/FIC_Survey_Application__c.field-meta.xml
<CustomField>
    <fullName>FIC_Survey_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FIC Survey Application</label>
    <referenceTo>FIC_Survey_Application__c</referenceTo>
    <relationshipLabel>Community Investments</relationshipLabel>
    <relationshipName>Community_Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Flood_Describe_Impact__c.field-meta.xml
<CustomField>
    <fullName>Flood_Describe_Impact__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flood Describe Impact</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Flood_Describe_Track_Record__c.field-meta.xml
<CustomField>
    <fullName>Flood_Describe_Track_Record__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flood Describe Track Record</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Community_Givings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Community_Giving__c/recordTypes/Sponsorship.recordType-meta.xml
<RecordType>
    <fullName>Sponsorship</fullName>
    <active>true</active>
    <label>Sponsorship</label>
</RecordType>

force-app/main/default/objects/FIC_Survey_Application__c/FIC_Survey_Application__c.object-meta.xml
<CustomObject>
    <description>Stores data received from Grant and Donation applications submitted by non profit organizations in our communitieis</description>
    <label>FIC Survey Application</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>FIC Survey Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIC Survey Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Requested__c</fullName>
    <label>Amount Requested</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Briefly_Describe_Community_Issue__c.field-meta.xml
<CustomField>
    <fullName>Briefly_Describe_Community_Issue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Briefly Describe Community Issue</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Briefly_Describe_Community_Success__c.field-meta.xml
<CustomField>
    <fullName>Briefly_Describe_Community_Success__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Briefly Describe Community Success</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Conversion__c.field-meta.xml
<CustomField>
    <fullName>Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process Survey Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Conversion_Date__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Conversion_Type__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Type__c</fullName>
    <label>Community Investment Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Flood Relief</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/First_National_Bank_Request__c.field-meta.xml
<CustomField>
    <fullName>First_National_Bank_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreed to Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Flood_Describe_Impact__c.field-meta.xml
<CustomField>
    <fullName>Flood_Describe_Impact__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flood Describe Impact</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Flood_Describe_Track_Record__c.field-meta.xml
<CustomField>
    <fullName>Flood_Describe_Track_Record__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flood Describe Track Record</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Educated_Workforce__c.field-meta.xml
<CustomField>
    <fullName>G_Educated_Workforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Educated Workforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Eligible_for_Free_and_Reduced_Lunch__c.field-meta.xml
<CustomField>
    <fullName>G_Eligible_for_Free_and_Reduced_Lunch__c</fullName>
    <label>Eligible for Free and Reduced Lunch</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Neighborhood_Revitalization__c.field-meta.xml
<CustomField>
    <fullName>G_Neighborhood_Revitalization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Neighborhood Revitalization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Schools_Free_and_Reduced_Lunch__c.field-meta.xml
<CustomField>
    <fullName>G_Schools_Free_and_Reduced_Lunch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schools Free and Reduced Lunch</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Stable_Housing__c.field-meta.xml
<CustomField>
    <fullName>G_Stable_Housing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stable Housing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Strong_Local_Economies__c.field-meta.xml
<CustomField>
    <fullName>G_Strong_Local_Economies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Strong Local Economies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_City__c.field-meta.xml
<CustomField>
    <fullName>Organization_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Program_Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Program_Event_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program/Event Description</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Program_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Event_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program/Event Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Provide_Name_and_Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Provide_Name_and_Service_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Provide Name and Service Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/processFicSurveyApps_Test.cls
@isTest
public class processFicSurveyApps_Test {
  @isTest
    public static void processFicSurveyApps_Test() {
              
        Id grantRecordTypeId = [SELECT Id
                                FROM RecordType
                                WHERE sObjectType = 'FIC_Survey_Application__c'
                                AND Name = 'Grant'
                                LIMIT 1].id;
        
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;
        
        FIC_Survey_Application__c ficsurveyAppDon = new FIC_Survey_Application__c(Market__c = 'Omaha',
                                                                                  Organization_City__c = 'Omaha',
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Donation',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppDon;
        
        Blob attachbodyDon = Blob.valueOf('Attach Body Blob');
        
        Attachment attachDon = new Attachment(parentId = ficsurveyAppDon.id,
                                              name = 'attachment test',
                                              body = attachbodyDon);
        
        insert attachDon;
        
        ficsurveyAppDon.Conversion__c = True;
        
        update ficsurveyAppDon;
        
        Id commGivingDon = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1].FIC_Survey_Application__c;
        
        System.assertEquals(ficsurveyAppDon.Id, commGivingDon);
        System.assertEquals('Omaha', ficsurveyAppDon.Market__c);
        
        Id commGivingDonId = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppDon.Id
                            LIMIT 1].Id;
        
        Id commGivingDonAttachment = [SELECT Id, ParentId
                                      FROM Attachment
                                      WHERE ParentId =: commGivingDonId].ParentId;
        
        Id ficsurveyAppDonCommGivingId = [SELECT Id, Community_Investment__c
                                          FROM FIC_Survey_Application__c
                                          WHERE Community_Investment__c =: commGivingDonId].Community_Investment__c;
        
        System.assertEquals(ficsurveyAppDonCommGivingId, commGivingDonId);
        System.assertEquals(commGivingDonAttachment, commGivingDonId);
        
        FIC_Survey_Application__c ficsurveyAppSpon = new FIC_Survey_Application__c(Market__c = 'Texas',
                                                                                  Organization_City__c = 'texas',
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Sponsorship',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More Texas More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppSpon;
        
        Blob attachbodySpon = Blob.valueOf('Attach Body Blob');
        
        Attachment attachSpon = new Attachment(parentId = ficsurveyAppDon.id,
                                              name = 'attachment test',
                                              body = attachbodySpon);
        
        insert attachSpon;
        
        ficsurveyAppSpon.Conversion__c = True;
        
        update ficsurveyAppSpon;
        
        Id commGivingSpon = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppSpon.Id
                            LIMIT 1].FIC_Survey_Application__c;
        
        System.assertEquals(ficsurveyAppSpon.Id, commGivingSpon);
        System.assertEquals('Texas', ficsurveyAppSpon.Market__c);
        
        
        ficsurveyAppSpon.Conversion__c = False;
        try{
            update ficsurveyAppSpon;
        } catch (Exception e) {
            
            String exceptionMessage =  e.getMessage();
            System.assertNotEquals(null, exceptionMessage);
        }
        
        System.assertNotEquals(ficsurveyAppSpon.Conversion__c, null);
        
        // Grant
        
        FIC_Survey_Application__c ficsurveyAppGrant = new FIC_Survey_Application__c(
                                                                                  Organization_City__c = 'texas',
                                                                                  Amount_Requested__c = 1000,
                                                                                  G_Educated_Workforce__c = True,
                                                                                  G_Stable_Housing__c = True,
                                                                                  G_Strong_Local_Economies__c = True,
                                                                                  G_Neighborhood_Revitalization__c = True,
                                                                                  G_Eligible_for_Free_and_Reduced_Lunch__c = 10,
                                                                                  G_Schools_Free_and_Reduced_Lunch__c = 'test',
                                                                                  Conversion_Type__c = 'Grant',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  recordTypeId = grantRecordTypeId,
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More Texas More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppGrant;
        
        Blob attachbodyGrant = Blob.valueOf('Attach Body Blob');
        
        Attachment attachGrant = new Attachment(parentId = ficsurveyAppGrant.id,
                                              name = 'attachment test',
                                              body = attachbodySpon);
        
        insert attachGrant;
        
        ficsurveyAppGrant.Conversion__c = True;
        
        update ficsurveyAppGrant;
        
        Id commGivingGrant = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppGrant.Id
                            LIMIT 1].FIC_Survey_Application__c;
        
        System.assertEquals(ficsurveyAppGrant.Id, commGivingGrant);
        
        
        ficsurveyAppSpon.Conversion__c = False;
        try{
            update ficsurveyAppGrant;
        } catch (Exception e) {
            
            String exceptionMessage =  e.getMessage();
            System.assertNotEquals(null, exceptionMessage);
        }
        
        System.assertNotEquals(ficsurveyAppGrant.Conversion__c, null);
        
        // Null
            
        FIC_Survey_Application__c ficsurveyAppNull = new FIC_Survey_Application__c(Market__c = 'Lincoln',
                                                                                  Organization_City__c = 'Lincoln',
                                                                                  Amount_Requested__c = 1000,
                                                                                  //Conversion_Type__c = 'Sponsorship',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Briefly_Describe_Community_Issue__c = 'More Test',
                                                                                  Briefly_Describe_Community_Success__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppNull;
        System.assertEquals('Lincoln', ficsurveyAppNull.Market__c);
        
        ficsurveyAppNull.Conversion__c = True;
        
        try {
            update ficsurveyAppNull;
        } catch (Exception e) {
        
            String exceptionMessage =  e.getMessage(); 
            System.assertNotEquals(null, exceptionMessage);
            
        }
        
        System.assertEquals(ficsurveyAppNull.Conversion_Date__c, null);
        
        
    }
    @isTest
    public static void processFicSurveyApps_FloodTest() {
              
        Id floodRecordTypeId = [SELECT Id
                                FROM RecordType
                                WHERE sObjectType = 'FIC_Survey_Application__c'
                                AND Name = 'Flood Relief'
                                LIMIT 1].id;
        
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;
        
        FIC_Survey_Application__c ficsurveyAppFlood = new FIC_Survey_Application__c(recordtypeid = floodRecordTypeId,
                                                                                  Market__c = 'Omaha',
                                                                                  Organization_City__c = 'Omaha',
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Flood Relief',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Flood_Describe_Impact__c = 'More Test',
                                                                                  Flood_Describe_Track_Record__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppFlood;
        
        Blob attachbodyFlood = Blob.valueOf('Attach Body Blob');
        
        Attachment attachFlood = new Attachment(parentId = ficsurveyAppFlood.id,
                                              name = 'attachment test',
                                              body = attachbodyFlood);
        
        insert attachFlood;
        
        ficsurveyAppFlood.Conversion__c = True;
        
        update ficsurveyAppFlood;
        
        Id commGivingFlood = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppFlood.Id
                            LIMIT 1].FIC_Survey_Application__c;
        
        System.assertEquals(ficsurveyAppFlood.Id, commGivingFlood);
        System.assertEquals('Omaha', ficsurveyAppFlood.Market__c);
        
        Id commGivingFloodId = [SELECT Id, FIC_Survey_Application__c
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppFlood.Id
                            LIMIT 1].Id;
        
        Id commGivingFloodAttachment = [SELECT Id, ParentId
                                      FROM Attachment
                                      WHERE ParentId =: commGivingFloodId].ParentId;
        
        Id ficsurveyAppFloodCommGivingId = [SELECT Id, Community_Investment__c
                                          FROM FIC_Survey_Application__c
                                          WHERE Community_Investment__c =: commGivingFloodId].Community_Investment__c;
        
        System.assertEquals(ficsurveyAppFloodCommGivingId, commGivingFloodId);
        System.assertEquals(commGivingFloodAttachment, commGivingFloodId);
    }

    @isTest
    public static void processFicSurveyApps_FloodTest_code37() {
              
        Id floodRecordTypeId = [SELECT Id
                                FROM RecordType
                                WHERE sObjectType = 'FIC_Survey_Application__c'
                                AND Name = 'Flood Relief'
                                LIMIT 1].id;
        
        Volunteer_Organization__c volOrg = new Volunteer_Organization__c(name = 'test Vol Org');
        insert volOrg;

        Volunteer_Organization__c volOrg2 = new Volunteer_Organization__c(name = 'test Vol Org2');
        insert volOrg2;
        
        FIC_Survey_Application__c ficsurveyAppFlood = new FIC_Survey_Application__c(recordtypeid = floodRecordTypeId,
                                                                                  Market__c = 'Omaha',
                                                                                  Organization_City__c = 'Omaha',
                                                                                  Amount_Requested__c = 1000,
                                                                                  Conversion_Type__c = 'Flood Relief',
                                                                                  Program_Event_Description__c = 'Test',
                                                                                  Provide_Name_and_Service_Description__c = 'Test test Test',
                                                                                  Program_Event_Name__c = 'Test',
                                                                                  First_National_Bank_Request__c = True,
                                                                                  Flood_Describe_Impact__c = 'More Test',
                                                                                  Flood_Describe_Track_Record__c = 'More More Test',
                                                                                  Non_Profit_Organization__c = volOrg.Id);
        Insert ficsurveyAppFlood;
        
        Blob attachbodyFlood = Blob.valueOf('Attach Body Blob');
        
        Attachment attachFlood = new Attachment(parentId = ficsurveyAppFlood.id,
                                              name = 'attachment test',
                                              body = attachbodyFlood);
        
        insert attachFlood;
        
        ficsurveyAppFlood.Conversion__c = True;
        
        update ficsurveyAppFlood;
        
        community_giving__c commGivingFloodNP = [SELECT Id, FIC_Survey_Application__c, non_profit_organization__c, non_profit_organization__r.name
                            FROM Community_Giving__c
                            WHERE FIC_Survey_Application__c =: ficsurveyAppFlood.Id
                            LIMIT 1];
        
        commGivingFloodNP.non_profit_organization__c = volOrg2.id;
        update commGivingFloodNP;

        FIC_Survey_Application__c ficsurveyAppFloodNP = [SELECT Id, non_profit_organization__r.name from FIC_Survey_Application__c where id = : ficsurveyAppFlood.Id]; 
        
        System.assertEquals('test Vol Org2', ficsurveyAppFloodNP.non_profit_organization__r.name);
      //System.assertEquals(commGivingFloodAttachment, commGivingFloodId);
    }        
}