force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/Awarded_Date__c.field-meta.xml
<CustomField>
    <fullName>Awarded_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Awarded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Grant_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Grant_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Survey_Email_notification__c.field-meta.xml
<CustomField>
    <fullName>Survey_Email_notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Email notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/recordTypes/Community_Development_Grant.recordType-meta.xml
<RecordType>
    <fullName>Community_Development_Grant</fullName>
    <active>true</active>
    <label>Community Development Grant</label>
</RecordType>

force-app/main/default/objects/Progress_Report_Forms__c/Progress_Report_Forms__c.object-meta.xml
<CustomObject>
    <description>Grant Survey Responses</description>
    <label>Progress Report Email Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Progress Report Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Report Email Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Forms__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipName>Progress_Report_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Forms__c/fields/Date_sent__c.field-meta.xml
<CustomField>
    <fullName>Date_sent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Forms__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Forms__c/fields/To_Email__c.field-meta.xml
<CustomField>
    <fullName>To_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/GrantEmailtemplate.cls
public class GrantEmailtemplate {
    
    public Community_Giving__c   CMG{set;get;}
    public String templateDeveName  {get;set;}
    public String fromAddress  {get;set;}
    public String toAddress  {get;set;}
    public String emailBody  {get;set;}
    public boolean blockBool {get;set;}
    
public GrantEmailtemplate(Apexpages.standardcontroller controller)
{
        CMG=(Community_Giving__c)controller.getrecord();
         blockBool=true;
    Emailformate();
      
}
public void calculateexpiredate(){

     
    }
    public void Emailformate()
{
         CMG=calFicRecord();
         templateDeveName = findTemplate(CMG);
         toAddress = calToAddress(CMG);
         emailBody=createEmailStr();
         fromAddress = calFromAddress();
}
    
public string findTemplate(Community_Giving__c   comObjVal)
 {     
          String templateName = '';
          if(comObjVal != null) 
          {
             if(comObjVal.RecordType.DeveloperName == 'Community_Development_Grant'){
                if(comObjVal.Survey_Email_notification__c==true) {
                   if(comObjVal.Market__c=='Texas') {
                      templateName='Grant_Survey_Response_2nd_Notification_FNBSW';
                   } else if(comObjVal.Market__c=='South Dakota') {
                      templateName='Grant_Survey_Response_2nd_Notification_FNBSD';
                   } else if(comObjVal.Market__c=='North Platte') {
                      templateName='Grant_Survey_Response_2nd_Notification_FNBNP';
                   } else {templateName='Grant_Survey_Response_2nd_Notification_FNB';}
                } else {
                   if(comObjVal.Market__c=='Texas') {
                      templateName='Grant_Survey_Response_1st_Notification_FNBSW';
                   } else if(comObjVal.Market__c=='South Dakota') {
                      templateName='Grant_Survey_Response_1st_Notification_FNBSD';
                   } else if(comObjVal.Market__c=='North Platte') {
                      templateName='Grant_Survey_Response_1st_Notification_FNBNP';
                   } else {templateName='Grant_Survey_Response_1st_Notification_FNB';}
                }
             }
          
          }
        
   return templatename;
        
 }
    public string createEmailStr(){
        
         String emailStr = '';
        List<EmailTemplate> templateList = new List<EmailTemplate>();
        if(templateDeveName != null && templateDeveName != '') {
            templateList = [SELECT Id,HTMLValue,Name,developername FROM EmailTemplate WHERE developername =: templateDeveName];
        }
        
        
        if(templateList.size()>0) {
            Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateList[0].id,Null, CMG.id);
            emailStr = mail.getHTMLBody();
        }
        system.debug('emailStr&&&'+emailStr);
        return emailStr;        
      
    }
    
    
    public string calToAddress(Community_Giving__c CMGto){
        String toStr = '';
        if(CMGto != null && CMGto.Grant_Contact_Email__c != null){
            toStr = CMGto.Grant_Contact_Email__c;
        }
                 system.debug('toStr'+toStr);    
        return toStr;
        
    }
private String calFromAddress() 
{
        String fromStr = '';
        
       
            fromStr = 'firstinthecommunity@fnni.com';
      
        system.debug('fromStr'+fromStr);
        return fromStr;
}
    
    
   public Community_Giving__c calFicRecord() 
{
    
   Community_Giving__c returncommunity=new Community_Giving__c();
     if(CMG != null && CMG.id !=null) 
     {
          CMG=[select id,RecordType.DeveloperName,Survey_Email_notification__c,Grant_Contact_Name__c,Grant_Contact_Email__c,Market__c, Awarded_Date__c from Community_Giving__c where id=:CMG.id];
         returncommunity=CMG;
     }
     return returncommunity;  
}
    public Pagereference sendEmail() {
        if (CMG.Awarded_Date__c==null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, 'Date Awarded needs to be filled in.  Go back and fill that in, then try again.'));
      } else {
         try {
            OrgWideEmailAddress orgWideAdd = [Select id from OrgWideEmailAddress Where DisplayName =: 'First in the Community'];
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            PageReference Respform = new pageReference('/grantsurveyresponse?id='+CMG.id);
            string Respheader = Respform.getHeaders().get('Host');
            string Respurl=Respform.geturl();
            string Resppagename='https://'+ Respheader + Respurl;
            String[] toAddresses = new String[]{toAddress};
            mail.setToAddresses(toAddresses);
            mail.setInReplyTo(fromAddress);
            mail.setSubject('Grant Progress Report');
            mail.setUseSignature(false);
            mail.setSaveAsActivity(false);
            //mail.setSenderDisplayName(fromName);
             //mail.setFileAttachments(Sendattach);
            mail.setOrgWideEmailAddressId(orgWideAdd.id);
           
            mail.setHtmlBody(emailBody);
            //mail.setWhatId(comObj.id); 
            //mail.setTemplateId(tempID.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
             blockBool = False;
            insertSurveyEmailRecord();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Confirm, 'Email Sent Successfully.'));
         }catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, ex.getMessage()));
         }
      }
         return null; 
    }
    private void insertSurveyEmailRecord() {
        try {
            Progress_Report_Forms__c ficSurObj = new Progress_Report_Forms__c();
            ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c=CMG.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  = emailBody;
            ficSurObj.From_Email__c  = fromAddress;
            ficSurObj.To_Email__c = toAddress;
            insert ficSurObj;
          Community_Giving__c  CG=new  Community_Giving__c ();
            CG.id=CMG.id;
            CG.Survey_Email_notification__c=true;
            update CG;
            System.debug('Community%%%%'+CG);
            
        }catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, ex.getMessage()));
        }
    }
    
}