force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/FIC_Survey_Application__c.field-meta.xml
<CustomField>
    <fullName>FIC_Survey_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FIC Survey Application</label>
    <referenceTo>FIC_Survey_Application__c</referenceTo>
    <relationshipLabel>Community Investments</relationshipLabel>
    <relationshipName>Community_Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Grant_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Community_Givings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requestor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Reviewed_by_FIC_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_by_FIC_Disposition__c</fullName>
    <inlineHelpText>FIC ($10,000+)</inlineHelpText>
    <label>Reviewed by FIC Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Reviewed_by_MCIC_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_by_MCIC_Decision__c</fullName>
    <inlineHelpText>by MCIC ($501-$9,999)</inlineHelpText>
    <label>Reviewed by MCIC Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Reviewed_outside_of_MCIC_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_outside_of_MCIC_Decision__c</fullName>
    <inlineHelpText>Review outside of MCIC Decision is up to $500</inlineHelpText>
    <label>Reviewed outside of MCIC Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Market Approve</fullName>
            </value>
            <value>
                <fullName>Market Decline</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <label>Total Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/recordTypes/Community_Development_Grant.recordType-meta.xml
<RecordType>
    <fullName>Community_Development_Grant</fullName>
    <active>true</active>
    <label>Community Development Grant</label>
</RecordType>

force-app/main/default/objects/Community_Giving__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Community_Giving__c/recordTypes/Sponsorship.recordType-meta.xml
<RecordType>
    <fullName>Sponsorship</fullName>
    <active>true</active>
    <label>Sponsorship</label>
</RecordType>

force-app/main/default/objects/Community_Survey__c/Community_Survey__c.object-meta.xml
<CustomObject>
    <description>Contains the survey data provided by non profit organziations after they have been approved for grants and donations.</description>
    <label>Community Survey Email Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Community Survey  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Survey Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Survey__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipLabel>Community Survey Emails</relationshipLabel>
    <relationshipName>Community_Survey_Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/Date_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/Email_body__c.field-meta.xml
<CustomField>
    <fullName>Email_body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Community_Survey__c/fields/From_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>From Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CRA_Contact_Title__c.field-meta.xml
<CustomField>
    <fullName>CRA_Contact_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CRA Contact Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CRA_Logo__c.field-meta.xml
<CustomField>
    <fullName>CRA_Logo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CRA Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CRA_Market_Name__c.field-meta.xml
<CustomField>
    <fullName>CRA_Market_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CRA Market Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/FIC_Survey_Application__c.object-meta.xml
<CustomObject>
    <description>Stores data received from Grant and Donation applications submitted by non profit organizations in our communitieis</description>
    <label>FIC Survey Application</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>FIC Survey Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIC Survey Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Community_Investment__c.field-meta.xml
<CustomField>
    <fullName>Community_Investment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Community Investment</label>
    <referenceTo>Community_Giving__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Grant_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Organization__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Non Profit Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipLabel>FIC Survey Applications</relationshipLabel>
    <relationshipName>FIC_Survey_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AtoDecisionTemplateCtrl.cls
public  class AtoDecisionTemplateCtrl {
    
    //public Id ficID {get;set;}
    public Community_Giving__c comObj {get;set;}
    //public Community_Giving__c ficObj;
    public Boolean blockBool {get;set;}
    
    private Contact conObjMarket {get; set;}
 
    public String templateDeveName  {get;set;}
    public String fromAddress  {get;set;}
    public String toAddress  {get;set;}
    public string Emailsubject {get;set;}
    public String emailBody  {get;set;}
   // Public id Communityinvestmentid;
    public list<selectoption>countlist{set;get;}
    Public  list<Attachment>attach{set;get;}
    public list<string>Attnames{set;get;}
    public list<id>attachesid{set;get;}
    public string filecount{set;get;}
   // private list<attachment> myattach;
 // public  list<Messaging.Emailfileattachment>Attaches;
    public AtoDecisionTemplateCtrl(ApexPages.StandardController std) {
        comObj = (Community_Giving__c)std.getRecord();
//Communityinvestmentid=apexpages.currentpage().getparameters().get('id');
        conObjMarket = new Contact();
        blockBool = False;
        countlist=new list<selectoption>();
         attach=new list<attachment>();
        Attnames=new list<string>();
        attachesid=new list<id>();
        //Attaches=new list<Messaging.Emailfileattachment>();
        //myattach=new list<Attachment>();
        filecount='';
        for(integer i=1; i<3; i++){
            countlist.add(new selectoption(''+i,''+i));
        }
        dispatcher();
    }
    public  pagereference addattachment(){
        attach.clear();
       // Attaches.clear();
        for(integer i=1;i<=integer.valueof(filecount);i++){
            attach.add(new attachment());
           
        }
         return null;
        
    }   
    public void Uploaddoc(){
       //if(comObj.id==null ||comObj.id==''){
   //ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.ERROR,'No record is associated. Please pass record Id in parameter.'));

       //}
             attachesid.clear();
        list<attachment>listtoinsert=new list<attachment>();
        for(Attachment a:attach){
            if(a.name!='' && a.body!=null){
                listtoinsert.add(new attachment(parentid=comObj.id,name=a.name,body=a.body));
            /*Messaging.Emailfileattachment a1=new Messaging.Emailfileattachment();
                a1.setfilename(a.name);
                a1.setbody(a1.body);
                attaches.add(a1);*/
            }
        }
        if(listtoinsert.size()>0){
            insert listtoinsert;
          ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.INFO, listToInsert.size() + ' file(s) are uploaded successfully'));
            for(Attachment a:listtoinsert){
                Attnames.add(a.name);
                attachesid.add(a.parentid);
            }

         //Attnames=new list<string>(listtoinsert[0].name);
            //attachesid=new list<id>(listtoinsert[0].id);
           // system.debug('myattach'+myattach);

            filecount='';
          attach=new list<attachment>(); 
          
        }
         
    }
        
    private void dispatcher() {
        List<Contact> fcMarketList = new List<Contact>();
        comObj = calFicRecord();
        templateDeveName = findTemplate(comObj);
        System.debug('templateDeveName'+templateDeveName);
        List<Community_Survey__c> ficSurveyList = [Select id from Community_Survey__c Where Name=:templateDeveName AND Community_Investment__c=:comObj.id LIMIT 1];
       
        if(ficSurveyList.size()>0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.INFO, 'Email has already been sent.'));
        }else {
            if(comObj.Market__c != null)
                fcMarketList = [Select id,Name,CRA_Contact_Title__c,CRA_Logo__c,Email from Contact Where CRA_Market_Name__c =: comObj.Market__c Limit 1];
             system.debug('%%%%Fcmarklist%%%%%%%'+fcMarketList.size());
            if(fcMarketList.size()>0)
               
                conObjMarket = fcMarketList[0];
            
            emailBody = createEmailStr();
            toAddress = calToAddress(comObj);
          //fromAddress = calFromAddress(comObj.Market__c);
            fromAddress = 'firstinthecommunity@fnni.com';
            blockBool = True;
        }
    }
    
    
    private String calFromAddress(String marketType) {
        String fromStr = '';
        if(conObjMarket != null && conObjMarket.Email != null) {
            fromStr = conObjMarket.Email;
        }else {
            fromStr = 'firstinthecommunity@fnni.com';
        }
        system.debug('fromStr'+fromStr);
        return fromStr;
    }
    
    private String calToAddress(Community_Giving__c ficObjVal) {
        String toStr = '';
        if(ficObjVal != null && ficObjVal.Grant_Contact_Email__c != null)
            toStr = ficobjVal.Grant_Contact_Email__c;
            if(ficObjVal != null && ficObjVal.requestor_Email__c != null)
            toStr = ficObjVal.requestor_Email__c;
                 system.debug('toStr'+toStr);    
        return toStr;
    }
    
    
    public Community_Giving__c calFicRecord() {
        Community_Giving__c ficObjToReturn = new Community_Giving__c();
        if(comObj != null && comObj.id != null) {
            comObj = [Select id,  FIC_Survey_Application__c,Grant_Contact_Email__c,Non_Profit_Organization__c ,Status_Picklist__c,Market__c,
            Total_Approved_Amount__c,Reviewed_by_MCIC_Decision__c,Reviewed_outside_of_MCIC_Decision__c,Reviewed_by_FIC_Disposition__c, requestor_Email__c, requestor_Name__c,
            RecordType.DeveloperName from Community_Giving__c Where id = :comObj.id];
           ficObjToReturn=comObj;
        }
        
        system.debug('ficObjToReturn'+ficObjToReturn);
        return ficObjToReturn;
    }
    
    public Pagereference sendEmail() {
      
            OrgWideEmailAddress orgWideAdd = [Select id from OrgWideEmailAddress Where address = 'firstinthecommunity@fnni.com'];
             list<Messaging.Emailfileattachment>Sendattach=new  list<Messaging.Emailfileattachment>();
          
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          // Attaches=new list<Messaging.Emailfileattachment>();
           /* if(attaches.size()>0){
                mail.setFileAttachments(Attaches);
            }*/
            mail.setOrgWideEmailAddressId(orgWideAdd.Id);
            if(attachesid.size()>0){
               list<attachment>attach=[select id,name,body,parentid from attachment where parentid in:attachesid]; 
                for(Attachment a:attach){
                   Messaging.Emailfileattachment ME=new Messaging.Emailfileattachment();
                    ME.setfilename(a.name);
                    ME.setbody(a.body);
                    Sendattach.add(ME);
                }
            }
            String[] toAddresses = new String[]{toAddress};
            mail.setToAddresses(toAddresses);
          //mail.setInReplyTo(fromAddress);
          //mail.setReplyTo(fromAddress);
            mail.setUseSignature(false);
            mail.setSaveAsActivity(false);
          //mail.setSenderDisplayName(fromName);
          //mail.setSenderDisplayName('First in the Community');
             mail.setFileAttachments(Sendattach);
            //mail.setOrgWideEmailAddressId(orgWideAdd.id);
           
            mail.setHtmlBody(emailBody);
            mail.setSubject(EmailSubject);
            //mail.setWhatId(comObj.id); 
            //mail.setTemplateId(tempID.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            blockBool = False;
            insertSurveyEmailRecord();
            //system.debug()
           ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Confirm, 'Email Sent Successfully.'));
        
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, ex.getMessage()));
           // system.debug(ex.getMessage());
      
        return null;
    }
    
    private void insertSurveyEmailRecord() {
        try {
            Community_Survey__c ficSurObj = new Community_Survey__c();
            ficSurObj.Name = templateDeveName;
            ficSurObj.Community_Investment__c = comObj.id;
            ficSurObj.Date_sent__c = System.Today();
            ficSurObj.Email_Body__c  = emailBody;
            ficSurObj.From_Email__c  = fromAddress;
            ficSurObj.To_Email__c = toAddress;
            insert ficSurObj;
            system.debug('ficSurObj'+ficSurObj);
        }catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, ex.getMessage()));
        }
    }
    
    public String createEmailStr() {
        String emailStr = '';
        List<EmailTemplate> templateList = new List<EmailTemplate>();
        if(templateDeveName != null && templateDeveName != '') {
            templateList = [SELECT Id,HTMLValue,Name,subject,developername FROM EmailTemplate WHERE developername =: templateDeveName];
        }
        
        if(templateList.size()>0) {
            Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateList[0].id, conObjMarket.id, comObj.id);
            EmailSubject = templateList[0].subject;
            emailStr = mail.getHTMLBody();
        }
        system.debug('emailStr&&&'+emailStr);
        return emailStr;
    }
     @Testvisible  private String findTemplate( Community_Giving__c comObjVal ) {
        String templateName = '';
        if(comObjVal != null) {
           if( comObjVal.RecordType.DeveloperName == 'Community_Development_Grant' ){
              if(comObjVal.Status_Picklist__c == 'Market Decline' || comObjVal.Status_Picklist__c == 'Declined') {
                  if(comObj.Market__c == 'South Dakota') {
                      templatename = 'Grant_Decline_Template_SD';
                  } else if(comObj.Market__c == 'North Platte') {
                       templatename = 'Grant_Decline_Template_NP';
                      } else if(comObj.Market__c == 'Texas') {
                           templatename = 'Grant_Decline_Template_SW';
                          } else {
                              templatename = 'Grant_Decline_template_FNB';
                          }
              } else if(comObjVal.Status_Picklist__c == 'Market Approve' || comObjVal.Status_Picklist__c == 'Approve') {
                   if(comObj.Market__c == 'South Dakota') {
                       templatename = 'Grant_Award_Template_SD';
                   } else if(comObj.Market__c == 'North Platte') {
                        templatename = 'Grant_Award_Template_NP';
                       } else if(comObj.Market__c == 'Texas') {
                            templatename = 'Grant_Award_Template_SW';
                           } else {
                               templatename = 'Grant_Award_template_FNB';
                           }
                       }
           }else if( comObjVal.RecordType.DeveloperName == 'Donation') {
              if((comObjVal.Reviewed_by_MCIC_Decision__c == 'Approved' ) ||
                (comObjVal.Reviewed_outside_of_MCIC_Decision__c == 'Approved' ) || 
                (comObjVal.Reviewed_by_FIC_Disposition__c == 'Approved')) {
                   if(comObj.Market__c == 'South Dakota') {
                       templatename = 'Donation_Approve_Template_SD';
                   } else if(comObj.Market__c == 'North Platte') {
                        templatename = 'Donation_Approve_Template_NP';
                       } else if(comObj.Market__c == 'Texas') {
                            templatename = 'Donation_Approve_Template_SW';
                           } else {
                               templatename = 'Donation_Approve_template_FNB';
                           }
              }else if((comObjVal.Reviewed_by_MCIC_Decision__c == 'Denied' ) ||
                (comObjVal.Reviewed_outside_of_MCIC_Decision__c == 'Denied' ) || 
                (comObjVal.Reviewed_by_FIC_Disposition__c == 'Denied')) {
                   if(comObj.Market__c == 'South Dakota') {
                       templatename = 'Donation_Decline_Template_SD';
                   } else if(comObj.Market__c == 'North Platte') {
                        templatename = 'Donation_Decline_Template_NP';
                       } else if(comObj.Market__c == 'Texas') {
                            templatename = 'Donation_Decline_Template_SW';
                           } else {
                               templatename = 'Donation_Decline_template_FNB';
                           }
              }
           }else if( comObjVal.RecordType.DeveloperName == 'Sponsorship'){
              if((comObjVal.Reviewed_by_MCIC_Decision__c == 'Approved' ) ||
                (comObjVal.Reviewed_outside_of_MCIC_Decision__c == 'Approved' ) || 
                (comObjVal.Reviewed_by_FIC_Disposition__c == 'Approved')) {
                   if(comObj.Market__c == 'South Dakota') {
                       templatename = 'Sponsorship_Approve_Template_SD';
                   } else if(comObj.Market__c == 'North Platte') {
                        templatename = 'Sponsorship_Approve_Template_NP';
                       } else if(comObj.Market__c == 'Texas') {
                            templatename = 'Sponsorship_Approve_Template_SW';
                           } else {
                               templatename = 'Sponsorship_Approve_template_FNB';
                           }
              }else if((comObjVal.Reviewed_by_MCIC_Decision__c == 'Denied' ) ||
                (comObjVal.Reviewed_outside_of_MCIC_Decision__c == 'Denied' ) || 
                (comObjVal.Reviewed_by_FIC_Disposition__c == 'Denied')) {
                   if(comObj.Market__c == 'South Dakota') {
                       templatename = 'Sponsorship_Decline_Template_SD';
                   } else if(comObj.Market__c == 'North Platte') {
                        templatename = 'Sponsorship_Decline_Template_NP';
                       } else if(comObj.Market__c == 'Texas') {
                            templatename = 'Sponsorship_Decline_Template_SW';
                           } else {
                               templatename = 'Sponsorship_Decline_template_FNB';
                           }
              }
           }    
        }
         system.debug('templateName&&&'+templateName);
        return templateName;
        }
        }