force-app/main/default/objects/Community_Giving__c/Community_Giving__c.object-meta.xml
<CustomObject>
    <description>Tracks the amounts approved via grant and donation requests from non profit organiziations</description>
    <label>Community Investment</label>
    <nameField>
        <displayFormat>FNBG-{00000}</displayFormat>
        <label>Community Giving Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Giving__c/fields/Awarded_Date__c.field-meta.xml
<CustomField>
    <fullName>Awarded_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Awarded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Grant_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
                <label>NE - Columbus, Norfolk, David City</label>
            </value>
            <value>
                <fullName>Fremont</fullName>
                <label>NE - Fremont</label>
            </value>
            <value>
                <fullName>Kearney</fullName>
                <label>NE - Kearney, Grand Island</label>
            </value>
            <value>
                <fullName>Lincoln</fullName>
                <label>NE - Lincoln, Beatrice</label>
            </value>
            <value>
                <fullName>North Platte</fullName>
                <label>NE - North Platte, Alliance, Chadron, Scottsbluff</label>
            </value>
            <value>
                <fullName>Omaha</fullName>
                <label>NE - Omaha Metro Area</label>
            </value>
            <value>
                <fullName>South Dakota</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purpose</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Giving__c/fields/Reviewed_by_MCIC_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_by_MCIC_Decision__c</fullName>
    <inlineHelpText>by MCIC ($501-$9,999)</inlineHelpText>
    <label>Reviewed by MCIC Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CRA_Contact_Title__c.field-meta.xml
<CustomField>
    <fullName>CRA_Contact_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CRA Contact Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CRA_Market_Name__c.field-meta.xml
<CustomField>
    <fullName>CRA_Market_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CRA Market Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GrantEmailTemplate_Test.cls
@isTest
public class GrantEmailTemplate_Test {
    @istest
    public static void GrantEmailTemplate1(){
       test.starttest();
     
        contact facemarklist=new contact();
          facemarklist.lastname='TestName';
          facemarklist.CRA_Contact_Title__c='TestTitle';
          facemarklist.Email='TestEmail@gmail.com';
          facemarklist.CRA_Market_Name__c='Kansas';
           insert facemarklist;
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
        CMG.purpose__c='Educated Workforce';
        CMG.Awarded_date__c = Date.newInstance(2017, 12, 9);
            insert CMG ;        
        //Emailtemplate 
        string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        GrantEmailTemplate d  = new GrantEmailTemplate(con);
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
        
         list<Attachment>Attach=new list<Attachment>();
        list<string>lstnames=new list<string>();
        list<id>ids=new list<id>();
        for(integer i=1; i<=3;i++){
         Attachment attachs=new Attachment();       
          attachs.Name='Unit Test Attachment';
          Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
          attachs.body=bodyBlob;
          attachs.parentId=CMG.id;
          Attach.add(attachs);
            
        }
        insert Attach;
        system.assertnotequals(2,Attach.size());
       
       /*for(integer i=1;i<=integer.valueof(count); i++){
            attach.add(new Attachment());
        }*/
      

        
        d.blockBool=false;
        d.FromAddress='test@fnni.com';
        d.toAddress='test1@fnni.com';
        d.templateDeveName='testing';
        d.sendEmail();
        //d.dispatcher();
        d.findTemplate(new Community_Giving__c());
      //d.filecount='2';
      //d.addattachment();
      //d.Uploaddoc();
       test.stoptest();
       
    }

    public static void GrantEmailTemplate2(){
       test.starttest();
     
        contact facemarklist=new contact();
          facemarklist.lastname='TestName';
          facemarklist.CRA_Contact_Title__c='TestTitle';
          facemarklist.Email='TestEmail@gmail.com';
          facemarklist.CRA_Market_Name__c='Kansas';
           insert facemarklist;
        
       Community_Giving__c  CMG= new Community_Giving__c();
        CMG.Market__c='Kansas';
        CMG.requestor_Email__c='Test@gmail.com';
        CMG.Grant_Contact_Email__c='Test1@gmail.com';
        CMG.Reviewed_by_MCIC_Decision__c='Approved';
        CMG.purpose__c='Educated Workforce';
        CMG.Awarded_date__c = null;
            insert CMG ;        
        //Emailtemplate 
        string count='2';
        apexpages.StandardController con =new apexpages.StandardController(CMG);
        GrantEmailTemplate d  = new GrantEmailTemplate(con);
         PageReference pageRef = Page.AtodecisionTemplate1; // Add your VF page Name here
        pageRef.getParameters().put('filecount',count);
         Test.setCurrentPage(pageRef);
        
         list<Attachment>Attach=new list<Attachment>();
        list<string>lstnames=new list<string>();
        list<id>ids=new list<id>();
        for(integer i=1; i<=3;i++){
         Attachment attachs=new Attachment();       
          attachs.Name='Unit Test Attachment';
          Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
          attachs.body=bodyBlob;
          attachs.parentId=CMG.id;
          Attach.add(attachs);
            
        }
        insert Attach;
        system.assertnotequals(2,Attach.size());
       
       /*for(integer i=1;i<=integer.valueof(count); i++){
            attach.add(new Attachment());
        }*/
      

        
        d.blockBool=false;
        d.FromAddress='test@fnni.com';
        d.toAddress='test1@fnni.com';
        d.templateDeveName='testing';
        d.sendEmail();
        //d.dispatcher();
        d.findTemplate(new Community_Giving__c());
      //d.filecount='2';
      //d.addattachment();
      //d.Uploaddoc();
       test.stoptest();
       
    }
   
}