force-app/main/default/objects/Transaction_Logs__e/Transaction_Logs__e.object-meta.xml
<CustomObject>
    <description>Capture transaction log information so it is written even if an exception occurs.</description>
    <label>Transaction Logs</label>
    <pluralLabel>Transaction Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_Logs__e/fields/App_Plugin__c.field-meta.xml
<CustomField>
    <fullName>App_Plugin__c</fullName>
    <label>App Plugin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Logs__e/fields/Transaction_Detail__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Detail__c</fullName>
    <label>Transaction Detail</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Logs__e/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TranLogPlatformEventTriggerTest.cls
@isTest
public class TranLogPlatformEventTriggerTest {
    
    @isTest 
    private static void testCreateTransactionLogTrigger() {

        // Create test event instance
        // Create an instance of the event and store it in the transactionLogEvent variable
		Transaction_Logs__e transactionLogEvent = new Transaction_Logs__e (
        	Action__c = PLUGIN_ACTION,
			App_Plugin__c = PLUGIN_NAME,
			Transaction_Detail__c = 'This is a test transaction detail',
			Transaction_Status__c = 'Complete',
			User_Id__c	= UserInfo.getUserId());
        
        Test.startTest();
        
        // Call method to publish events
        Database.SaveResult sr = EventBus.publish(transactionLogEvent);
        
        Test.stopTest();
        
        // Perform validation here
        // Verify that the publish was successful
        System.assertEquals(true, sr.isSuccess());
        
        // Check that the tranLog that the trigger created is present
        List<nFUSE__Transaction_Log__c> tranLog = [SELECT Id FROM nFUSE__Transaction_Log__c];
        
        // Validate that the tranLog was found.
        // There is only one test tranLog created
        System.assertEquals(1, tranLog.size());
    }

    private static final String 
		PLUGIN_NAME = 'SingleSignOn',
        PLUGIN_ACTION = 'sign_on';

}