force-app/main/default/objects/Dataload_Error_Log__c/Dataload_Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object receives daily person and business customer loading error info from two _error.csv files.</description>
    <label>Dataload Error Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Dataload Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dataload Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataload_Error_Log__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateErrorLogTest.cls
@IsTest
public class UpdateErrorLogTest {

      @isTest static void TestErrorLog() {
        // Test data setup                
        Dataload_Error_Log__c el = new Dataload_Error_Log__c(External_ID__c='65000211848');
        insert el;   
        
        // Perform test        
        List<Dataload_Error_Log__c> el2 = [SELECT External_ID__c FROM Dataload_Error_Log__c LIMIT 1];
        Test.startTest();
        System.assertEquals('65000211848', el2[0].External_ID__c);        
        Test.stopTest();
    }    
}