force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/FNNI_Account_Relationship_Portal__c.object-meta.xml
<CustomObject>
    <description>Allows limited data from the FNBO org to be shared to the FNTS Salesforce instance</description>
    <label>FNNI Account Relationship Portal</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNNI Account Relationship Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/fntsPartnerConnForward_Test.cls
@isTest
public class fntsPartnerConnForward_Test {
    /* Commenting out the test class as per the Story S-46099
    public static testMethod void fnniAcctRelPortTrigger() {
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        FNNI_Account_Relationship_Portal__c insertTest = new FNNI_Account_Relationship_Portal__c(
                                                            Name__c = 'insertTest');
        
        insert insertTest;
        
    }
*/
}