force-app/main/default/objects/COI__c/COI__c.object-meta.xml
<CustomObject>
    <description>Center of Influence Object</description>
    <label>COI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>COI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unfunded_Trust__c/Unfunded_Trust__c.object-meta.xml
<CustomObject>
    <description>Tracks Unfunded Trusts (FNBO has bee notified that we are assigned to be associated with a trust but it has not yet been funded</description>
    <label>Unfunded Trust</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unfunded Estate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unfunded Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unfunded_Trust__c/fields/COI__c.field-meta.xml
<CustomField>
    <fullName>COI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Unfunded Trusts</relationshipLabel>
    <relationshipName>Unfunded_Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/unfundedTrustHelper.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 09/29/2016
// Project: Unfunded Trust
// Purpose: Helper class to handle scope creep requirements

public without sharing class unfundedTrustHelper {

    private final Map<Id, Unfunded_Trust__c> oldMap;
    private final List<Unfunded_Trust__c> newVer;
    
    public static void preventUpdates(Map<Id, Unfunded_Trust__c> oldMap, List<Unfunded_Trust__c> newVer) {
    
        for(Unfunded_Trust__c unfundT : NewVer) {
            
            Unfunded_Trust__c oldUnfundT = oldMap.get(unfundT.Id);  
            if (unfundT.COI__c != oldUnfundT.COI__c) {
                unfundT.addError(' Changes to the Source COI field are not allowed.');
            }
        }
    }
}