force-app/main/default/objects/COI__c/COI__c.object-meta.xml
<CustomObject>
    <description>Center of Influence Object</description>
    <label>COI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>COI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COI Source</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/Unfunded_Trust__c.object-meta.xml
<CustomObject>
    <description>Tracks Unfunded Trusts (FNBO has bee notified that we are assigned to be associated with a trust but it has not yet been funded</description>
    <label>Unfunded Trust</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unfunded Estate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unfunded Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unfunded_Trust__c/fields/COI__c.field-meta.xml
<CustomField>
    <fullName>COI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Unfunded Trusts</relationshipLabel>
    <relationshipName>Unfunded_Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Funded = We are named as fiduciary and chose to serve
Inactive = We are not named as fiduciary or chosen not to serve
Active = Everything else</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/coiLeadandTrustController_Test.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 09/29/2016
// Project: Unfunded Trust

@isTest
public class coiLeadandTrustController_Test {

    static testMethod void coiLeadandTrustController_Test() {
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        Coi__c coi = new Coi__c(name = 'COI Test');
        insert coi;
        
        Lead openLead = new Lead(lastName = 'OpenLeadTest',
                                 status = 'Open',
                                 Lead_Source_COI__c = coi.id);
        insert openLead;
        
        Lead closedLead = new Lead(lastName = 'ClosedLeadTest',
                                 status = 'Closed',
                                 Lead_Source_COI__c = coi.id);
        insert closedLead;
        
        Unfunded_Trust__c testTrust = new Unfunded_Trust__c(name = 'Test Trust',
                                                  COI__c = coi.id);
        insert testTrust;
        
        try {
        
            testtrust.COI__c = null;
            update testTrust;
            
        } catch (exception e) {
        
            String message = e.getMessage();
            
        }
        
        
        System.assertEquals(testtrust.COI__c, testtrust.COI__c);
        
        testtrust.COI__c = coi.id;
        testtrust.Status__c = 'Funded';
        update testTrust;
        
 
        ApexPages.currentPage().getParameters().put('id',coi.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(coi);
        coiLeadandTrust_Controller ce = new coiLeadandTrust_Controller(sc);
        
        test.startTest();
        
        List<Account> coiAccounts = ce.getCoiAccounts();
        List<Opportunity> coiOpportunities = ce.getCoiOpportunities();
        List<Lead>coiLeadsOpen = ce.getCoiLeadsOpen();
        List<Lead>coiLeadsNotOpen = ce.getCoiLeadsNotOpen();
        list<Unfunded_Trust__c> coiFundTrusts = ce.getCoiFundTrusts();
        Boolean renderPage = ce.getRenderPage();
        
        System.assertNotEquals(null, coiAccounts);
        System.assertNotEquals(null, coiOpportunities);
        System.assertNotEquals(null, coiLeadsOpen);
        System.assertNotEquals(null, coiLeadsNotOpen);
        System.assertNotEquals(null, coiFundTrusts);
        System.assertNotEquals(null, renderPage);
        
        test.stopTest();
    
    }
}