force-app/main/default/objects/Employee_Talent_Referral__c/Employee_Talent_Referral__c.object-meta.xml
<CustomObject>
    <description>HR Talent referral tracking</description>
    <label>Talent Referral</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employee Talent Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talent Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Addtl_Notes__c.field-meta.xml
<CustomField>
    <fullName>Addtl_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quick Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Candidate_Email__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Candidate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Candidate_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Candidate Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Referral_Source_Employee__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source_Employee__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Referring Employee (if applicable)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Referrer_Dept__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Dept__c</fullName>
    <inlineHelpText>Please select the Referrer&#39;s department if they are a current employee</inlineHelpText>
    <label>Referrer Dept</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
            </value>
            <value>
                <fullName>Consumer Banking</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>FNTS</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Talent_Referral__c/fields/Referring_Employee_Email_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Referring_Employee_Email_if_applicable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter referring employee&#39;s email address</inlineHelpText>
    <label>Referring Employee Email (if applicable)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/talentReferralAttachmentRedirect_Test.cls
@isTest
public class talentReferralAttachmentRedirect_Test {
    public static testMethod void talentReferralAttachmentRedirect_Test() {
        
        Employee_Talent_Referral__c talentReferral = new Employee_Talent_Referral__c(name = '123',
                                                                                    Referrer_Dept__c = 'IT',
                                                                                    Referring_Employee_Email_if_applicable__c = 'abc@abc.com',
                                                                                    Candidate_Email__c = 'abc@abc.com',
                                                                                    Candidate_Phone_Number__c = 'abc',
                                                                                    Referral_Source_Employee__c = 'alex',
                                                                                    Addtl_Notes__c = 'abc');
        //insert talentReferral;
        
        System.assertEquals(talentReferral.name, '123');
        System.assertNotEquals(talentReferral.name, '456');
        
		ApexPages.StandardController sc = new ApexPages.StandardController(talentReferral);
        talentReferralAttachmentRedirect cc = new talentReferralAttachmentRedirect(sc);
        pageReference action = cc.saveAndDirect();
        
        System.assertNotEquals(talentReferral.id, null);
        
	}
}