force-app/main/default/objects/Account/fields/Card_Product_FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Card_Product_FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Product FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/Card_Product__c.object-meta.xml
<CustomObject>
    <description>Used to track the progress of Commercial card applications from Sales &gt; Underwriting &gt; Implementations</description>
    <label>Card Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Card Products</relationshipLabel>
    <relationshipName>Card_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Card_Product__c.field-meta.xml
<CustomField>
    <fullName>Card_Product__c</fullName>
    <label>(*) Card Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial &amp; Purchasing</fullName>
            </value>
            <value>
                <fullName>Commercial Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing with Virtual+</fullName>
            </value>
            <value>
                <fullName>VOX</fullName>
            </value>
            <value>
                <fullName>Still Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(*) FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Card_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateParentAcctCompanyIdFBCSalesPerson.cls
// Author: Alexander Nourbakhsh
// Date: 06.27.2016
// Project: Card Spend
// Purpose: Update Card_Product__c record parent Account with the Card_Product__c record 
// Company_Id__c and FBC_Sales_Person__c field values.  

public without sharing class updateParentAcctCompanyIdFBCSalesPerson {
    
    //Map and list to allow passing of Trigger.oldMap and Trigger.new  trigger context variables 
    private final Map<Id, Card_Product__c> oldMap;
    private final List<Card_Product__c> newCardProducts;
    
    public static void updateParentAcctCompanyIdFBCSalesPerson(List<Card_Product__c> newCardProducts, Map<Id, Card_Product__c> oldMap) {
        
        List<Card_Product__c> cardProductsUpdated = new List <Card_Product__c>();
        
        //Loop thru new Card Product versions and qualify records where FBC_Sales_Person__c 
        //or Company_ID__c field values were changed 
        for(Card_Product__c cardProduct : newCardProducts){
            Card_Product__c oldCardProduct = oldMap.get(cardproduct.id);
            if (cardproduct.FBC_Sales_Person__c != oldCardProduct.FBC_Sales_Person__c
                || cardproduct.Company_ID__c != oldCardProduct.Company_ID__c) {
                cardProductsUpdated.add(cardProduct);
    
            }    
        }   
                  
        Map<Id, Card_Product__c> parentAccounts = new Map<Id, Card_Product__c>();
        
        //Put parent Account Id as key and Card Product sObject as value in map
        for(Card_Product__c i : cardProductsUpdated) {
            parentAccounts.put(i.Account__c, i);
                    
            }
        
        //Gather parent Accounts           
        List<Account> accountsToBeUpdated = [SELECT Id
                                             FROM Account
                                             WHERE Id IN: parentAccounts.keySet()
                                             LIMIT 50000];
        
        //Loop thru list of parent Accounts and assign field values from parentAccounts map        
        for(Account acct : accountsToBeUpdated){
            Card_Product__c childCardProduct = parentAccounts.get(acct.Id);
            
            acct.Existing_Company_ID__c = childCardProduct.Company_ID__c;
            acct.Card_Product_FBC_Sales_Person__c = childCardProduct.FBC_Sales_Person__c;
            
            }  
            
            // Update parent Account records  
            update accountsTobeUpdated;           
    }
}