force-app/main/default/objects/Account/fields/Card_Product_FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Card_Product_FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Product FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_180_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_180_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 180 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_60_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_60_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 60 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>180 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>180 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>60 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>60 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/accountDaily180SpendWorkflow.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 06.28.2016
// Project: Card Spend
// Purpose: To evaluate Account records where X180_Day_Daily_Spend_Sum__c
// field value is less than the Est_180_Day_Spend__c field value respectively, 
// AND when at evalution the Cards_Mailed_Date__c field is outside the 180 date range, 
// 

public without sharing class accountDaily180SpendWorkflow {

    public void accountDaily180SpendWorkflow() {
        System.debug('firing accountDaily180SpendWorkflow');
        // List of Accounts for processing
        List<Account> spendAccts = [SELECT Id, Existing_Company_Id__c, Cards_Mailed_Date__c, X60_Day_Daily_Spend_Sum__c, 
         							X180_Day_Daily_Spend_Sum__c, X60_Day_Daily_Spend__c, X180_Day_Daily_Spend__c, Est_60_Day_Spend__c, 
         							Est_180_Day_Spend__c, Card_Product_FBC_Sales_Person__r.isActive
         							FROM Account 
             						WHERE Existing_Company_Id__c != Null
                                    AND Cards_Mailed_Date__c != Null
                                    AND Card_Product_FBC_Sales_Person__r.isActive = True];
       
        // List of Accounts to qualify for Process Builder tasks
        List<Account> acctsProBuilder = New List<Account>();
        
        for(Account acct : spendAccts) {
            
            // 180 datetime calculation
            Date acctCardsMailed0 = acct.Cards_Mailed_Date__c.date().addDays(15);
            Date acctCardsMailedDate180 = acctCardsMailed0.addDays(180);
            // Current datetime calculation
            datetime todayDateTime = datetime.now();

            
            // Qualify Accounts
            if(acct.X180_Day_Daily_Spend__c == false 
               && (todayDateTime > acctCardsMailedDate180) 
               && (acct.X180_Day_Daily_Spend_Sum__c < acct.Est_180_Day_Spend__c)) {
                   // Update Account field values and add to list
                   acct.X180_Day_Daily_Spend__c = true;
                   acctsProBuilder.add(acct);
                   
               }
        } 
        
        // Update Accounts
        update acctsProBuilder;
    }
}