force-app/main/default/objects/Account/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/Card_Product__c.object-meta.xml
<CustomObject>
    <description>Used to track the progress of Commercial card applications from Sales &gt; Underwriting &gt; Implementations</description>
    <label>Card Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Card Products</relationshipLabel>
    <relationshipName>Card_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Card_Product__c.field-meta.xml
<CustomField>
    <fullName>Card_Product__c</fullName>
    <label>(*) Card Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial &amp; Purchasing</fullName>
            </value>
            <value>
                <fullName>Commercial Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing with Virtual+</fullName>
            </value>
            <value>
                <fullName>VOX</fullName>
            </value>
            <value>
                <fullName>Still Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Company_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Company_Annual_Revenue__c</fullName>
    <label>Company Annual Revenue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(*) FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Card_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/cardProductTrigger_Test.cls
@istest
public class cardProductTrigger_Test{
    static testmethod void cardProductTrigger(){
        //08/08/2019 Added as part of test class fix -begin
      	List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
       	accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
       //08/08/2019-end
        
        Account acct = new Account(name = 'Parent Test 1', Industry = 'Education');
        insert acct;
        
        Id FBCSalesPersonId = [SELECT Id
                            FROM User
                            WHERE lastname = 'Nourbakhsh'
                            LIMIT 1].id;
        
        Id accountId = [SELECT Id 
                        FROM Account 
                        WHERE Name = 'Parent Test 1' 
                        LIMIT 1].Id;
                        
        //DAG 07/17/2018 ADS002977 Added value Company_Annual_revenue__c field, since this field is now required.
        Card_Product__c crdp = new Card_Product__c(name = 'Card Product Test 1', Account__c = accountId, Company_Annual_Revenue__c = 123456.65);
        insert crdp;
        
        crdp.Company_ID__c = '123456789';
        update crdp;
        
        List<Card_Product__c> assertSize = [SELECT Id 
                                            FROM Card_Product__c 
                                            LIMIT 10];
        
        System.assertEquals(assertSize.size(), 1);
        
        crdp.Cards_Mailed_Date__c = Date.newInstance(2016, 2, 17);
        update crdp;
        
        System.assertEquals(crdp.Cards_Mailed_Date__c.year(), 2016);
        
        crdp.FBC_Sales_Person__c = FBCSalesPersonId;
        update crdp;
        
        System.assertEquals(crdp.FBC_Sales_Person__c, FBCSalesPersonId);
    }
}