force-app/main/default/objects/Account/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_180_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_180_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 180 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_60_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_60_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 60 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>180 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_List__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_List__c</fullName>
    <defaultValue>&quot;Base&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>180 Day Daily Spend List</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>180 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>60 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_List__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_List__c</fullName>
    <defaultValue>&quot;Base&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>60 Day Daily Spend List</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>60 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/Card_Spend__c.object-meta.xml
<CustomObject>
    <description>Utilized to house card spend data for Commercial card customers</description>
    <label>Card Spend</label>
    <nameField>
        <displayFormat>CS{0000000000}</displayFormat>
        <label>Card Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Spend__c/fields/Company_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Company_Credit_Limit__c</fullName>
    <label>Company_Credit_Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Month_End__c.field-meta.xml
<CustomField>
    <fullName>Month_End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month_End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Month_Spend__c.field-meta.xml
<CustomField>
    <fullName>Month_Spend__c</fullName>
    <label>Month_Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Multiple_Product_Flag__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Product_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Multiple Product Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Card Spends</relationshipLabel>
    <relationshipName>Card_Spends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Partnering_Bank__c.field-meta.xml
<CustomField>
    <fullName>Partnering_Bank__c</fullName>
    <description>SuperBank from the TBS system interface file for Card Spend</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Partnering Bank</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/System_of_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>System_of_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>System of Record Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Card_Spend__c/recordTypes/Monthly.recordType-meta.xml
<RecordType>
    <fullName>Monthly</fullName>
    <active>true</active>
    <label>Monthly</label>
</RecordType>

force-app/main/default/objects/Partnering_Bank__c/Partnering_Bank__c.object-meta.xml
<CustomObject>
    <description>Used to house data on our partnering agent banks (a lookup relationship from the Card Product object)</description>
    <label>Partnering Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partnering Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnering Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/cardSpendChartStatController_Test.cls
@isTest
public class cardSpendChartStatController_Test {
	@TestSetup
    static void setupData() {   
        //08/08/2019 Added as part of test class fix -begin
      	List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
       	accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
       //08/08/2019-end
     }
    
    @isTest
    public static void cardSpendChartStatController_Test() {
        date myDate = system.Today();
        date firstDate = myDate.toStartOfMonth();
        date EndofLastMonth = firstDate - 1;

        Account acct = new Account(name = 'test123', Existing_Company_Id__c = '5555', Cards_Mailed_Date__c = EndofLastMonth, X60_Day_Daily_Spend_List__c = 'Base', 
                    X180_Day_Daily_Spend_List__c = 'Base', X60_Day_Daily_Spend_Sum__c = 0, X180_Day_Daily_Spend_Sum__c = 0,
                    X60_Day_Daily_Spend__c = False, X180_Day_Daily_Spend__c = False, Est_60_Day_Spend__c = 10000, Est_180_Day_Spend__c = 2000);
        
        insert acct;
        
        String cardSpendRecordTypeId = [SELECT Id 
                                        FROM recordtype 
                                        WHERE sObjectType = 'Card_Spend__c'
                                        AND name = 'Monthly'
                                        LIMIT 1].Id;
        system.debug('Test 1-- EndofLastMonth = ' + EndofLastMonth);
        Card_Spend__c cardSpend = new Card_Spend__c(Company_Id__c = '5555', RecordTypeId = cardSpendRecordTypeId, Parent_Account__c = acct.id, Company_Name__c = 'Acme Splosion Stuff',
                                  Month_Spend__c = 1000, System_of_Record_Id__c ='223789', Month_End__c = EndofLastMonth, 
                                                   Company_Credit_Limit__c = 2000, Multiple_Product_Flag__c = 'Y', Partnering_Bank__c = 'Wells Fargo');
        insert cardSpend;
        
        List<Card_Spend__c> cardSpendRecords = [SELECT Id
                                                FROM Card_Spend__c
                                                LIMIT 50000];
        
        ApexPages.currentPage().getParameters().put('id',acct.id);
        ApexPages.StandardController stdAccount = new ApexPages.StandardController(acct);
        cardSpendChartStatController StatAccountController  = new cardSpendChartStatController(stdAccount);
        ApexPages.currentPage().getParameters().put('id',acct.id);
        cardSpendChartStatController StatCustomAccountController  = new cardSpendChartStatController();
        
    }
    @isTest
    public static void cardSpendChartStatController_Test2() {
        date myDate = system.Today();
        date firstDate = myDate.toStartOfMonth();
        date EndofLastMonth = firstDate - 1;
        date myDateLastYear = system.Today() - 365;
        date firstDateLastYear = myDateLastYear.toStartOfMonth();
        date EndofLastYearMonth = firstDateLastYear - 1;

        Account acct = new Account(name = 'test123', Existing_Company_Id__c = '5555', Cards_Mailed_Date__c = EndofLastMonth, X60_Day_Daily_Spend_List__c = 'Base', 
                    X180_Day_Daily_Spend_List__c = 'Base', X60_Day_Daily_Spend_Sum__c = 0, X180_Day_Daily_Spend_Sum__c = 0,
                    X60_Day_Daily_Spend__c = False, X180_Day_Daily_Spend__c = False, Est_60_Day_Spend__c = 10000, Est_180_Day_Spend__c = 2000);
        
        insert acct;
        
        String cardSpendRecordTypeId = [SELECT Id 
                                        FROM recordtype 
                                        WHERE sObjectType = 'Card_Spend__c'
                                        AND name = 'Monthly'
                                        LIMIT 1].Id;
        
        Card_Spend__c cardSpend = new Card_Spend__c(Company_Id__c = '5555', RecordTypeId = cardSpendRecordTypeId, Parent_Account__c = acct.id,
                                  Month_Spend__c = 1000, System_of_Record_Id__c ='223789', Month_End__c = EndofLastMonth, 
                                                   Company_Credit_Limit__c = 2000, Multiple_Product_Flag__c = 'Y', Partnering_Bank__c = 'Union Bank');
        system.debug('Test 2-- EndofLastMonth = ' + EndofLastMonth);
        system.debug('Test 2-- CardSpend.Month_End__c = ' + CardSpend.Month_End__c);
        
        insert cardSpend;

        Card_Spend__c cardSpend2 = new Card_Spend__c(Company_Id__c = '5555', RecordTypeId = cardSpendRecordTypeId, Parent_Account__c = acct.id,
                                  Month_Spend__c = 1000, System_of_Record_Id__c ='339197', Month_End__c = EndofLastYearMonth, 
                                                   Company_Credit_Limit__c = 2000, Multiple_Product_Flag__c = 'Y', Partnering_Bank__c = 'CitiBank');
        insert cardSpend2;
        
        List<Card_Spend__c> cardSpendRecords = [SELECT Id
                                                FROM Card_Spend__c
                                                LIMIT 50000];
        
        System.assertEquals(cardSpendRecords.size(), 2);      
        
        ApexPages.currentPage().getParameters().put('id',acct.id);
        ApexPages.StandardController stdAccount = new ApexPages.StandardController(acct);
        cardSpendChartStatController StatAccountController  = new cardSpendChartStatController(stdAccount);
        ApexPages.currentPage().getParameters().put('id',acct.id);
        cardSpendChartStatController StatCustomAccountController  = new cardSpendChartStatController();        
        StatCustomAccountController.getCalcRecord();
        StatCustomAccountController.getRenderPage();
        StatCustomAccountController.getLastMonthEndDate();
        StatCustomAccountController.getCompanyID();
        StatCustomAccountController.getCompanyCreditLimit();
        StatCustomAccountController.getTBSCompanyName();
        StatCustomAccountController.getTBSPartneringBank();
        StatCustomAccountController.getProductCode();
        StatCustomAccountController.getMultipleProductFlag();
        StatCustomAccountController.getManagedFlag();
        StatCustomAccountController.getLiveAccountCount();
        StatCustomAccountController.getActiveCards();
        StatCustomAccountController.getYtdSpendSum();
        StatCustomAccountController.getPytdSpendSum();
        StatCustomAccountController.getYtdAvgPerUtil();
        StatCustomAccountController.getPytdAvgPerUtil();

        
    }
    @isTest
    public static void cardSpendChartStatController_Test3() {
        date myDate = system.Today();
        date firstDate = myDate.toStartOfMonth();
        date EndofLastMonth = firstDate - 1;

        Account acct = new Account(name = 'test123', Existing_Company_Id__c = '5555', Cards_Mailed_Date__c = EndofLastMonth, X60_Day_Daily_Spend_List__c = 'Base', 
                    X180_Day_Daily_Spend_List__c = 'Base', X60_Day_Daily_Spend_Sum__c = 0, X180_Day_Daily_Spend_Sum__c = 0,
                    X60_Day_Daily_Spend__c = False, X180_Day_Daily_Spend__c = False, Est_60_Day_Spend__c = 10000, Est_180_Day_Spend__c = 2000);
        
        insert acct;
        
        String cardSpendRecordTypeId = [SELECT Id 
                                        FROM recordtype 
                                        WHERE sObjectType = 'Card_Spend__c'
                                        AND name = 'Monthly'
                                        LIMIT 1].Id;
        
        List<Card_Spend__c> cardSpendRecords = [SELECT Id
                                                FROM Card_Spend__c
                                                LIMIT 50000];
        
        System.assertEquals(cardSpendRecords.size(), 0);      
        
        ApexPages.currentPage().getParameters().put('id',acct.id);
        ApexPages.StandardController stdAccount = new ApexPages.StandardController(acct);
        cardSpendChartStatController StatAccountController  = new cardSpendChartStatController(stdAccount);
        
        ApexPages.currentPage().getParameters().put('id',acct.id);
        cardSpendChartStatController StatCustomAccountController  = new cardSpendChartStatController();
        
    }        
}