force-app/main/default/objects/Account/fields/Card_Product_FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Card_Product_FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Product FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_180_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_180_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 180 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_60_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_60_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 60 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>180 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_List__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_List__c</fullName>
    <defaultValue>&quot;Base&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>180 Day Daily Spend List</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>180 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>60 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_List__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_List__c</fullName>
    <defaultValue>&quot;Base&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>60 Day Daily Spend List</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>60 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/Card_Product__c.object-meta.xml
<CustomObject>
    <description>Used to track the progress of Commercial card applications from Sales &gt; Underwriting &gt; Implementations</description>
    <label>Card Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Card Products</relationshipLabel>
    <relationshipName>Card_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Card_Product__c.field-meta.xml
<CustomField>
    <fullName>Card_Product__c</fullName>
    <label>(*) Card Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial &amp; Purchasing</fullName>
            </value>
            <value>
                <fullName>Commercial Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing Edition</fullName>
            </value>
            <value>
                <fullName>Purchasing with Virtual+</fullName>
            </value>
            <value>
                <fullName>VOX</fullName>
            </value>
            <value>
                <fullName>Still Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Est_180_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_180_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated 180 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/Est_60_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_60_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated 60 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Card_Product__c/fields/FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(*) FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Card_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/Card_Spend__c.object-meta.xml
<CustomObject>
    <description>Utilized to house card spend data for Commercial card customers</description>
    <label>Card Spend</label>
    <nameField>
        <displayFormat>CS{0000000000}</displayFormat>
        <label>Card Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Spend__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateParentAcctCardsMailedDate.cls
// Author: Alexander Nourbakhsh
// Date: 06.27.2016
// Project: Card Spend
// Purpose: Stage Card_Product__c parent Account record for 60 and 180 day Daily Card_Spend__c record processing.
// A change to the Card_Product__c record Cards_Mailed_Date__c field will qualify the record for processing. 

public without sharing class updateParentAcctCardsMailedDate {
    
    //Map and list to allow passing of Trigger.oldMap and Trigger.new  trigger context variables 
    private final Map<Id, Card_Product__c> oldMap;
    private final List<Card_Product__c> newCardProducts;
    
    public static void updateParentAcctCardsMailedDate(List<Card_Product__c> newCardProducts, Map<Id, Card_Product__c> oldMap) {
        
        List<Card_Product__c> cardProductsUpdated = new List <Card_Product__c>();
        
        //Loop thru new Card Product versions and qualify records Cards_Mailed_Date__c field values were changed 
        for(Card_Product__c cardProduct : newCardProducts){
            Card_Product__c oldCardProduct = oldMap.get(cardproduct.id);
            if (cardproduct.Cards_Mailed_Date__c != oldCardProduct.Cards_Mailed_Date__c) {
                cardProductsUpdated.add(cardProduct);
    
            }    
        }   
                  
        Map<Id, Card_Product__c> parentAccounts = new Map<Id, Card_Product__c>();
        
        //Put parent Account Id as key and Card Product sObject as value in map
        for(Card_Product__c i : cardProductsUpdated) {
            parentAccounts.put(i.Account__c, i);
                    
            }
        
        //Gather parent Accounts           
        List<Account> accountsToBeUpdated = [SELECT Id
                                             FROM Account
                                             WHERE Id IN: parentAccounts.keySet()
                                             LIMIT 50000];
        
        //Loop thru list of parent Accounts and assign field values from parentAccounts map        
        for(Account acct : accountsToBeUpdated){
            Card_Product__c childCardProduct = parentAccounts.get(acct.Id);
            
            acct.Existing_Company_ID__c = childCardProduct.Company_ID__c;
            acct.Cards_Mailed_Date__c = childCardProduct.Cards_Mailed_Date__c;
            acct.Est_60_Day_Spend__c = childCardProduct.Est_60_Day_Spend__c;
            acct.Est_180_Day_Spend__c = childCardProduct.Est_180_Day_Spend__c;
            acct.Card_Product_FBC_Sales_Person__c = childCardProduct.FBC_Sales_Person__c;
            acct.X60_Day_Daily_Spend_List__c = 'Base';
            acct.X180_Day_Daily_Spend_List__c = 'Base';
            acct.X60_Day_Daily_Spend_Sum__c = 0;
            acct.X180_Day_Daily_Spend_Sum__c = 0;
            acct.X60_Day_Daily_Spend__c = false;
            acct.X180_Day_Daily_Spend__c = false;
            
            }  
            
            // Update parent Account records  
            update accountsTobeUpdated;           
    }
}