force-app/main/default/objects/Account/fields/Card_Product_FBC_Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Card_Product_FBC_Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Product FBC Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cards_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Cards_Mailed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cards Mailed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_180_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_180_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 180 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Est_60_Day_Spend__c.field-meta.xml
<CustomField>
    <fullName>Est_60_Day_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Est 60 Day Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>180 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X180_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X180_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>180 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>60 Day Daily Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X60_Day_Daily_Spend_Sum__c.field-meta.xml
<CustomField>
    <fullName>X60_Day_Daily_Spend_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>60 Day Daily Spend Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/scheduledDailySpend60Workflow_Test.cls
@istest
public without sharing class scheduledDailySpend60Workflow_Test {
    static testmethod void scheduledDailySpend60Workflow_Test() {
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        Account daily60acct = new Account(Name = 'daily60acct', Existing_Company_Id__c = '12345' , Cards_Mailed_Date__c = Datetime.newInstance(2016, 1, 1, 1, 1, 1), X60_Day_Daily_Spend_Sum__c = 0, 
                                     X180_Day_Daily_Spend_Sum__c = 0, X60_Day_Daily_Spend__c = false, X180_Day_Daily_Spend__c = false, Est_60_Day_Spend__c = 50, 
                                     Est_180_Day_Spend__c = 50, Card_Product_FBC_Sales_Person__c = '005a000000CLOKt');
        
        insert daily60acct;
        
        Test.startTest();
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        String jobId = System.schedule('Sample_Heading', CRON_EXP, new scheduledAccountDaily60SpendWorkflow() );   
        Test.stopTest();
        
        System.assertEquals(daily60acct.X60_Day_Daily_Spend__c, false);
        
    }

}