force-app/main/default/objects/Account/fields/COI_Source_ID__c.field-meta.xml
<CustomField>
    <fullName>COI_Source_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COI Source ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COI__c/COI__c.object-meta.xml
<CustomObject>
    <description>Center of Influence Object</description>
    <label>COI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>COI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <inlineHelpText>Tell us whether we are trying to ultimately do business with a COMPANY or with a PERSON.</inlineHelpText>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COI Source</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/coileadcontroller.cls
public with sharing class coileadcontroller {
   
   public COI__c currentRecord {get;set;}
   
   public list <Lead> coiLeadsOpen {get;set;}
   public list <Lead> coiLeadsNotOpen {get;set;}
   public list <Opportunity> coiOpportunities {get;set;}
   public list <Account> coiAccounts {get;set;}
   
   public coileadcontroller(ApexPages.StandardController controller) {
       coiLeadsOpen = [SELECT Id, Name, Company, Email, Status, Owner.Name , Referral_Type__c, Lead_Source_COI__c FROM Lead WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id') AND Status = 'Open'];
       coiLeadsNotOpen = [SELECT Id, Name, Company, Email, Status, Owner.Name , Referral_Type__c, Lead_Source_COI__c FROM Lead WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id') AND Status != 'Open'];
       coiOpportunities = [SELECT Id, Account.Name, Amount, Name, StageName, Owner.Name, Type, CloseDate FROM Opportunity WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id')];
       coiAccounts = [SELECT Id, Name, Owner.Name FROM Account WHERE COI_Source_ID__c = :ApexPages.currentPage().getParameters().get('id')];
              }
}