force-app/main/default/objects/Account/fields/COI_Source_ID__c.field-meta.xml
<CustomField>
    <fullName>COI_Source_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COI Source ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_Unfunded_Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_Unfunded_Trust_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Unfunded Trust ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COI__c/COI__c.object-meta.xml
<CustomObject>
    <description>Center of Influence Object</description>
    <label>COI</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>COI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <inlineHelpText>Tell us whether we are trying to ultimately do business with a COMPANY or with a PERSON.</inlineHelpText>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_COI__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_COI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COI Source</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/Unfunded_Trust__c.object-meta.xml
<CustomObject>
    <description>Tracks Unfunded Trusts (FNBO has bee notified that we are assigned to be associated with a trust but it has not yet been funded</description>
    <label>Unfunded Trust</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unfunded Estate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unfunded Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unfunded_Trust__c/fields/COI__c.field-meta.xml
<CustomField>
    <fullName>COI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source COI</label>
    <referenceTo>COI__c</referenceTo>
    <relationshipLabel>Unfunded Trusts</relationshipLabel>
    <relationshipName>Unfunded_Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Document_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Funded = We are named as fiduciary and chose to serve
Inactive = We are not named as fiduciary or chosen not to serve
Active = Everything else</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/coiLeadandTrust_Controller.cls
// Author: Alexander Nourbakhsh
// Date: 09.29.2016
// Project: Unfunded Trust/COI 
// Purpose: Separate COI Influence controller that includes Unfunded trusts branded from COI
// Required per Profiles seeing unique page layouts. 
//

public class coiLeadandTrust_Controller {
        
   public list<Lead> coiLeadsOpen = new List<Lead>();
   public list<Lead> coiLeadsNotOpen = new List<Lead>();
   public list<Opportunity> coiOpportunities = new List<Opportunity>();
   public list<Account> coiAccounts = new List<Account>();
   public list<Unfunded_Trust__c> coiFundTrusts = new List<Unfunded_Trust__c>();
   
   // Boolean for exception handling.
   public boolean renderPage = true;
   
   public coiLeadandTrust_Controller(ApexPages.StandardController controller) {
   
       try{
            
            // SOQL statements to build sObject lists                              
            coiLeadsOpen = [SELECT Id, Name, Company, Email, Status, Owner.Name , Referral_Type__c, Lead_Source_COI__c 
                            FROM Lead 
                            WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id') 
                            AND Status = 'Open'
                            LIMIT 50000];
      
            coiLeadsNotOpen = [SELECT Id, Name, Company, Email, Status, Owner.Name , Referral_Type__c, Lead_Source_COI__c 
                               FROM Lead 
                               WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id') 
                               AND Status != 'Open'
                               LIMIT 50000];
                               
            coiOpportunities = [SELECT Id, Account.Name, Amount, Name, StageName, Owner.Name, Type, CloseDate 
                                FROM Opportunity 
                                WHERE Lead_Source_COI__c = :ApexPages.currentPage().getParameters().get('id')
                                LIMIT 50000];
                                
                                
            coiFundTrusts = [SELECT Id, Name, Document_Date__c, Status__c
                             FROM Unfunded_Trust__c
                             WHERE COI__c = :ApexPages.currentPage().getParameters().get('id')
                             LIMIT 50000]; 
            
            List<String> string15Ids = New List<String>();
            
            for(Unfunded_Trust__c unfund : coiFundTrusts) {
            
                String string15Id = String.valueOf(unfund.id).substring(0, 15);               
                string15Ids.add(string15Id);       
            }                             
      
            coiAccounts = [SELECT Id, Name, Owner.Name 
                           FROM Account 
                           WHERE COI_Source_ID__c = :ApexPages.currentPage().getParameters().get('id')
                           OR Source_Unfunded_Trust_ID__c =: string15Ids
                           LIMIT 50000];
                           
       } catch (exception e) {
       
           // Set boolean variable renderPage to false to prevent page rendering
           renderPage = false;
       }  
   }
   
   public list <Lead> getCoiLeadsOpen() {
        return coiLeadsOpen;
   }
   
   public list <Lead> getCoiLeadsNotOpen() {
        return coiLeadsNotOpen;
   }
   
   public list <Opportunity> getCoiOpportunities() {
        return coiOpportunities;
   }
   
   public list <Account> getCoiAccounts() {
        return coiAccounts;
   }
   
   public list <Unfunded_Trust__c> getCoiFundTrusts() {
        return coiFundTrusts;
   }
   
   public boolean getRenderPage() {
        return renderPage;
   } 
}