force-app/main/default/objects/Account/fields/Comp_Package_Code__c.field-meta.xml
<CustomField>
    <fullName>Comp_Package_Code__c</fullName>
    <formula>IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;a&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;b&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;c&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;d&#39;, &#39;A&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;e&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;1&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;f&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;2&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;2&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;a&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;2&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;b&#39;, &#39;A&#39;, 
IF(TEXT(Vertical__c) = &#39;3&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;&#39;, &#39;A&#39;, 
IF(TEXT(Vertical__c) = &#39;3&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;a&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;3&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;b&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;3&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;c&#39;, &#39;C&#39;, 
IF(TEXT(Vertical__c) = &#39;3&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;d&#39;, &#39;A&#39;, 
IF(TEXT(Vertical__c) = &#39;4&#39; &amp;&amp; TEXT(Sub_vertical__c) = &#39;&#39;, &#39;A&#39;, 
&#39;Please choose valid Vertical and Sub vertical combination.&#39;))))))))))))))))</formula>
    <label>Comp Package/Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_vertical__c.field-meta.xml
<CustomField>
    <fullName>Sub_vertical__c</fullName>
    <label>Sub vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>b</fullName>
            </value>
            <value>
                <fullName>c</fullName>
            </value>
            <value>
                <fullName>d</fullName>
            </value>
            <value>
                <fullName>e</fullName>
            </value>
            <value>
                <fullName>f</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comp_Code__c/Comp_Code__c.object-meta.xml
<CustomObject>
    <description>Small object used to facilitate date on Trident Account records</description>
    <label>Comp Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Comp Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comp Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/compCodeTest.cls
@istest
public class compCodeTest {
  @istest
  static void compCodeAccount(){
    //08/08/2019 Added as part of test class fix -begin
    List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
    TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
    accountTriggerSupportSetting.Name = 'Account';
    accountTriggerSupportSetting.TriggerIsDisabled__c = true;
    triggerSupportList.add(accountTriggerSupportSetting);
    insert triggerSupportList;
    //08/08/2019-end    
    Comp_Code__c compCode1 = new Comp_Code__c(
    name = 'C');    
    insert compCode1;
    
    Comp_Code__c compCode2 = new Comp_Code__c(
    name = 'A');    
    insert compCode2;
    
    Account compAccount = new Account(
    name = 'comp', DunsNumber = '12345', Vertical__c = '1', Sub_vertical__c = '' );
    insert compAccount; 
    
    List<Account>updateCompAccounts = new List<Account>{[SELECT Id, Comp_Package_Code__c FROM Account]};
                                                                  
        for(Account acct : updateCompAccounts) {
        acct.Sub_vertical__c = 'd';
        }
		update updateCompAccounts; 
     Account updateAccounts = [SELECT Id FROM Account where Sub_vertical__c = 'd' limit 1];
     System.assert( updateAccounts.Id != null );
  	}                                                               
    
}