force-app/main/default/objects/Account/fields/Current_Card_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Card_Relationship__c</fullName>
    <inlineHelpText>Is this Card Account an existing customer or a prospect</inlineHelpText>
    <label>Current Card Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_CTS_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_CTS_Relationship__c</fullName>
    <inlineHelpText>Is this CTS account an existing customer or a prospect.</inlineHelpText>
    <label>Current CTS Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Insurance_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Insurance_Relationship__c</fullName>
    <description>Value to identify the customer has a current inurance relationship.</description>
    <label>Current Insurance Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Lauritzen_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Lauritzen_Relationship__c</fullName>
    <inlineHelpText>Is this Lauritzen account an existing customer or a prospect.</inlineHelpText>
    <label>Current Lauritzen Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Lending_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Lending_Relationship__c</fullName>
    <inlineHelpText>Is this Lending account an existing customer or a prospect.</inlineHelpText>
    <label>Current Lending Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Wealth_Account__c.field-meta.xml
<CustomField>
    <fullName>Current_Wealth_Account__c</fullName>
    <inlineHelpText>Is this Wealth account an existing customer or a prospect</inlineHelpText>
    <label>Current Wealth Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer - High</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Med</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Full_Name__c</fullName>
    <formula>Owner.FirstName + &#39; &#39; + Owner.LastName</formula>
    <label>Owner Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/FNNI_Account_Relationship_Portal__c.object-meta.xml
<CustomObject>
    <description>Allows limited data from the FNBO org to be shared to the FNTS Salesforce instance</description>
    <label>FNNI Account Relationship Portal</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNNI Account Relationship Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Card_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Card_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/CTS_Relationship__c.field-meta.xml
<CustomField>
    <fullName>CTS_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CTS Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Current_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Insurance_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Lauritzen_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Lauritzen_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lauritzen Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Lending_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Lending_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lending Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Full_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Owner Full Name</label>
    <length>121</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Wealth_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Wealth_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Wealth Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/batchAcctRelPortGen.cls
public class batchAcctRelPortGen implements Database.batchable<sObject> {
    
    public String query;
    public List<FNNI_Account_Relationship_Portal__c> portalRecs = new List<FNNI_Account_Relationship_Portal__c>();
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);        
    }
    
    public void genPortalRecs(Database.BatchableContext bc, List<Account> forwardAccounts) {
        
    }
    
    public void execute(Database.BatchableContext bc, List<Account> forwardAccounts) {
        for(Account acct : forwardAccounts) {
            FNNI_Account_Relationship_Portal__c portalRec = new FNNI_Account_Relationship_Portal__c(
            Name__c = acct.Name,
            Card_Relationship__c = acct.Current_Card_Relationship__c,
            CTS_Relationship__c = acct.Current_CTS_Relationship__c,
          //Current_Relationship__c = acct.Current_Relationship__c,   DAG 08/07/2018 Remove this field... it is no longer needed. ADS ticket ADS0003026
            Insurance_Relationship__c = acct.Current_Insurance_Relationship__c,
            Lauritzen_Relationship__c = acct.Current_Lauritzen_Relationship__c,
            Lending_Relationship__c = acct.Current_Lending_Relationship__c,
            Owner_Full_Name__c = acct.Owner_Full_Name__c,
            Wealth_Relationship__c = acct.Current_Wealth_Account__c);
            portalRecs.add(portalRec);
        }
        insert portalRecs;
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
}