force-app/main/default/objects/Account/fields/Current_Card_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Card_Relationship__c</fullName>
    <inlineHelpText>Is this Card Account an existing customer or a prospect</inlineHelpText>
    <label>Current Card Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_CTS_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_CTS_Relationship__c</fullName>
    <inlineHelpText>Is this CTS account an existing customer or a prospect.</inlineHelpText>
    <label>Current CTS Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Insurance_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Insurance_Relationship__c</fullName>
    <description>Value to identify the customer has a current inurance relationship.</description>
    <label>Current Insurance Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Lauritzen_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Lauritzen_Relationship__c</fullName>
    <inlineHelpText>Is this Lauritzen account an existing customer or a prospect.</inlineHelpText>
    <label>Current Lauritzen Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Lending_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Lending_Relationship__c</fullName>
    <inlineHelpText>Is this Lending account an existing customer or a prospect.</inlineHelpText>
    <label>Current Lending Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Wealth_Account__c.field-meta.xml
<CustomField>
    <fullName>Current_Wealth_Account__c</fullName>
    <inlineHelpText>Is this Wealth account an existing customer or a prospect</inlineHelpText>
    <label>Current Wealth Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect-Low</fullName>
                <default>true</default>
                <label>Prospect-Low</label>
            </value>
            <value>
                <fullName>Prospect-Medium</fullName>
            </value>
            <value>
                <fullName>Prospect-High</fullName>
            </value>
            <value>
                <fullName>Existing Customer - High</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Med</fullName>
            </value>
            <value>
                <fullName>Existing Customer - Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Full_Name__c</fullName>
    <formula>Owner.FirstName + &#39; &#39; + Owner.LastName</formula>
    <label>Owner Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/FNNI_Account_Relationship_Portal__c.object-meta.xml
<CustomObject>
    <description>Allows limited data from the FNBO org to be shared to the FNTS Salesforce instance</description>
    <label>FNNI Account Relationship Portal</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNNI Account Relationship Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Current_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Relationship__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FNNI_Account_Relationship_Portal__c/fields/Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Full_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Owner Full Name</label>
    <length>121</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchAcctRelPort_Test.cls
//RJP Notes (2019-09-11):
//The Database.executeBatch is attempting to create FNNI_Account_Relationship_Portal__c records.
//  There is an AFTER INSERT trigger event being called... fnniAccountRelationshipPortalTrigger
//    The trigger call fntsPartnerNetworkConnection.forwardFntsConn() passing in the new FNNI_Account_Relationship_Portal__c records.
//    The network status does not work which is causing the process to fail with an "INVALID_PARTNER_NETWORK_STATUS" error.
//The FNTS bridge may no longer be needed.  If that is the case, the following objects/code can be removed.
//   a. FNNI_Account_Relationship_Portal__c - custom object
//   b. fnniAccountRelationshipPortalTrigger - custom trigger
//   c.	fntsPartnerNetworkConnection - custom class
//   d. BatchAcctRelPort_Test - test class
//   e. fntsPartnerConnForward_Test - test class

@isTest
public class BatchAcctRelPort_Test {
 /*Commenting out the test class as per the Story S-46099
    //DAG 08/07/2018 comment out all instances of Current_Relationship__c.  Field is no longer needed.  ADS ticket ADS0003026.
    public static testMethod void genBatchTest() {
               
        List<Account> testAccts = new List<Account>();
        
        for(Integer i=0;i<30;i++) {
            Account acct = new Account(
            Name = 'Test',
            Current_Card_Relationship__c = 'Test',
            Current_CTS_Relationship__c = 'Test',
          //Current_Relationship__c = 'Test',
            Current_Insurance_Relationship__c = 'Test',
            Current_Lauritzen_Relationship__c = 'Test',
            Current_Lending_Relationship__c = 'Test',
            Current_Wealth_Account__c = 'Test');
            
            testAccts.add(acct);
        }
        
        insert testAccts;
        
        
        Test.startTest();
        batchAcctRelPortGen testGen = new batchAcctRelPortGen();
      //testGen.query = 'SELECT Id, Name, Current_Card_Relationship__c, Current_CTS_Relationship__c, Current_Relationship__c, Current_Insurance_Relationship__c,Current_Lauritzen_Relationship__c, Current_Lending_Relationship__c, Owner_Full_Name__c, Current_Wealth_Account__c FROM Account WHERE IsPersonAccount = False AND Non_Disclosure_Agreement__c = False';
        testGen.query = 'SELECT Id, Name, Current_Card_Relationship__c, Current_CTS_Relationship__c, Current_Insurance_Relationship__c,Current_Lauritzen_Relationship__c, Current_Lending_Relationship__c, Owner_Full_Name__c, Current_Wealth_Account__c FROM Account WHERE IsPersonAccount = False AND Non_Disclosure_Agreement__c = False';
        Database.executeBatch(testGen);
        Test.stopTest();
        
        System.assertEquals(Database.countquery('SELECT COUNT() FROM FNNI_Account_Relationship_Portal__c'), 30);
    }    
       
    public static testMethod void delbatchTest() {
               
        List<FNNI_Account_Relationship_Portal__c> testRelPortRecs = new List<FNNI_Account_Relationship_Portal__c>();
        
        for(Integer i=0;i<30;i++) {
            FNNI_Account_Relationship_Portal__c rec = new FNNI_Account_Relationship_Portal__c(
            Name__c = 'Test');
            
            testRelPortRecs.add(rec);
        }
        
        insert testRelPortRecs;
        
        
        Test.startTest();
        batchAcctRelPortDel testDel = new batchAcctRelPortDel();
        testDel.query = 'SELECT Id FROM FNNI_Account_Relationship_Portal__c';
        Database.executeBatch(testDel);
        Test.stopTest();
        
        System.assertEquals(Database.countquery('SELECT COUNT() FROM FNNI_Account_Relationship_Portal__c'), 0);
    }*/
}