force-app/main/default/objects/Account/fields/Existing_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Existing_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/Card_Spend__c.object-meta.xml
<CustomObject>
    <description>Utilized to house card spend data for Commercial card customers</description>
    <label>Card Spend</label>
    <nameField>
        <displayFormat>CS{0000000000}</displayFormat>
        <label>Card Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Spend__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Month_End__c.field-meta.xml
<CustomField>
    <fullName>Month_End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month_End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/recordTypes/Monthly.recordType-meta.xml
<RecordType>
    <fullName>Monthly</fullName>
    <active>true</active>
    <label>Monthly</label>
</RecordType>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/testParentCardSpendRecords.cls
@isTest
public class testParentCardSpendRecords {

    public static testMethod void ParentCardSpendRecords(){
    
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        Account acct = new Account(name = 'Parent Test 1', Industry = 'Education', Existing_Company_ID__c = '777');
        insert acct;
        
        Id monthlyRecordTypeId = [SELECT id
                                  FROM recordType
                                  WHERE name = 'Monthly' 
                                  AND sObjectType = 'Card_Spend__c'].id;
        try{
        	Card_Spend__c cspendOld = new Card_Spend__c(company_Id__c = '777', Month_End__c = date.newinstance(2014, 2, 2), recordTypeId = monthlyRecordTypeId);
       		insert cspendOld;
        } catch (exception e) {
        } 
        try{
        	Card_Spend__c cspendNew = new Card_Spend__c(company_Id__c = '777', Month_End__c = date.newinstance(2014, 8, 2), recordTypeId = monthlyRecordTypeId);      
       		insert cspendNew;
        } catch (exception e) {
        }
        try{
        	Card_Spend__c cspendNoId = new Card_Spend__c(company_Id__c = '778', Month_End__c = date.newinstance(2014, 8, 2), recordTypeId = monthlyRecordTypeId);
        	insert cspendNoId;
        } catch (exception e) {
        }
        
    }
}