force-app/main/default/objects/Account/fields/FNB_System_of_record_id__c.field-meta.xml
<CustomField>
    <fullName>FNB_System_of_record_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>FNB System of Record ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FnboLog__c/FnboLog__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the logs.</description>
    <label>FnboLog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FnboLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FnboLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FnboLog__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Insert, Update, Delete</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Insert, Update, Delete</inlineHelpText>
    <label>Action</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FnboLog__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>e.g.CDS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>API_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FnboLog__c/fields/Log_Detail__c.field-meta.xml
<CustomField>
    <fullName>Log_Detail__c</fullName>
    <description>Log Details</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Details of the log will be displayed here.</inlineHelpText>
    <label>Log_Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FnboLog__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>Salesforce Object Name E.g. Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FnboLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Success. Failure</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Success. Failure</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CdsUpdater.cls
@RestResource(urlMapping='/accounts/*')
global with sharing class CdsUpdater {
    
    @HttpGet
    //endpoint: https://instance.salesforce.com/services/apexrest/accounts/cixfId
    global static Boolean checkCixf() {
        RestRequest req = RestContext.request;
        String details = null;
		String Status = 'Failure';       
        // get the cixfId from the end of the URL
        String cixfId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);       
        System.debug('Cds Updater - The cixfId is ' + cixfId);
        List<Account> results = new List<Account>();
        // query for exsiting account with cixfId
        results = [SELECT Id FROM Account WHERE FNB_System_of_record_id__c =: cixfId];  
        System.debug('Cds Updater - Result size: ' + results.size());
        status = 'Success';
        
        // if query returns any record, means the cixfId exists
        if(results.size()>0){
            details = 'Customer with CIXFID '+ cixfid + ' exists.';
            updateLogs('Get','checkCixf', 'Account', status, details);
            return true;
        } else{
            details = 'Customer with CIXFID '+ cixfid + ' does not exist.';
            updateLogs('Get','checkCixf', 'Account', status, details);
            return false;
        }
    }
  
    @HttpPost
    //endpoint: https://instance.salesforce.com/services/apexrest/account
    global static String addCustomer(String cixfId, String name) {
        
        String status = 'FAILURE';
        String details = null;
        Account account = new Account();
        account.Name = name;
        account.FNB_System_of_record_id__c = cixfId;
        
        // Create a new account
        try{
            insert account;
            status = 'SUCCESS';
            details = 'Customer '+ name +'with CIXFID '+ cixfid + ' is successfully inserted';
        }catch (Exception e){
            details = 'Failed inserting the record for Customer '+ name +'with CIXFID '+ cixfid +
                'with this error: ' + e.getMessage() ;
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        updateLogs('Create','addCustomer', 'Account', status, details);
        return status;     
    }
    @testVisible
    public static void updateLogs(String action, String apiname, String objectName, String status, String details ) {
        FnboLog__c fnlog = new FnboLog__c();
        fnlog.Action__c = action;
        fnlog.API_Name__c = apiname; 
        fnlog.SObject_Name__c = objectName;
        fnlog.Status__c = status;
        fnlog.Log_Detail__c = details;
        insert fnlog;
    }
    
}