force-app/main/default/objects/Account/fields/FNB_System_of_record_id__c.field-meta.xml
<CustomField>
    <fullName>FNB_System_of_record_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>FNB System of Record ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/CoreDataLoadStatistic__c.object-meta.xml
<CustomObject>
    <description>Custom object used to report daily &quot;Core&quot; data loads</description>
    <label>CoreDataLoadStatistic</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoreDataLoadStatistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>Type of data that was loaded: PersonCustomer, BusinessCustomer, CustomerVariance, Junction, FinancialAccount...</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Failed_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Failed_Record_Count__c</fullName>
    <description>Number of records that could not be loaded into org</description>
    <label>Failed Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Load_Date__c.field-meta.xml
<CustomField>
    <fullName>Load_Date__c</fullName>
    <description>Date CoreData was loaded into ORG</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Load Failed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Successful_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Successful_Record_Count__c</fullName>
    <description>Number of records successfully loaded into org</description>
    <label>Successful Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/Dataload_Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object receives daily person and business customer loading error info from two _error.csv files.</description>
    <label>Dataload Error Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Dataload Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dataload Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Date_Insert__c.field-meta.xml
<CustomField>
    <fullName>Date_Insert__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Insert</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/FNB_System_of_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>FNB_System_of_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FNB System of Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dlMatrixControllerTest.cls
@isTest
public class dlMatrixControllerTest {
     @isTest static void TestFetchDailyStats() {
        Date testDate = Date.newInstance(2019, 8, 8);
        CoreDataLoadStatistic__c cd = new CoreDataLoadStatistic__c(Data_Type__c='BusinessCustomer',Status__c='Completed Successfully',Successful_Record_Count__c = 62132,Failed_Record_Count__c = 2, Load_Date__c = testDate);
        insert cd; 
         
        List<CoreDataLoadStatistic__c> dailyStats = dlMatrixController.fetchDailyStats(testDate);
        System.assertEquals('BusinessCustomer', dailyStats[0].Data_Type__c);
        System.assertEquals(62132, dailyStats[0].Successful_Record_Count__c);
    }
    
      @isTest static void TestGetErrorLog() {
        // Test data setup        
        // Create an account with an opportunity, and then try to delete it        
        Date testDate = System.today() - 1;
        Dataload_Error_Log__c el = new Dataload_Error_Log__c(Object_Type__c='BusinessCustomer', External_Id__c = '65000211848_2019-09-10', FNB_System_of_record_id__c='65000211848', Business_Name__c='Vivian M Bonham Trust', Error__c='DUPLICATES_DETECTED:You cannot create this record because there is a duplicate identified in Salesforce.',Date_Insert__c = testDate);
        insert el;   
        
        // Perform test
        //         
        List<Dataload_Error_Log__c> el2 = dlMatrixController.getErrorLog(System.today() - 1, 'BusinessCustomer');        
        Test.startTest();
        System.assertEquals('65000211848', el2[0].FNB_System_of_record_id__c);
        System.assertEquals('Vivian M Bonham Trust', el2[0].Business_Name__c);
        Test.stopTest();
    }    
}