force-app/main/default/objects/Account/fields/FNB_System_of_record_id__c.field-meta.xml
<CustomField>
    <fullName>FNB_System_of_record_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>FNB System of Record ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FnboLog__c/FnboLog__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the logs.</description>
    <label>FnboLog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FnboLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FnboLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FnboLog__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Insert, Update, Delete</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Insert, Update, Delete</inlineHelpText>
    <label>Action</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FnboLog__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>Salesforce Object Name E.g. Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CdsUpdaterTest.cls
@isTest
public class CdsUpdaterTest {
 
    @testSetup 
    static void setup(){
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        insert new Account(Name = 'CdsTestCustomer',FNB_System_of_record_id__c = '12345678999');
    }
    
    //Positive test
    @isTest 
    static void checkCixfTest(){
        String cixfId = '12345678999'; 

        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = 'https://fnni--ncino.cs69.my.salesforce.com/services/apexrest/account/' + cixfId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        //Call the method to test
        Boolean response = CdsUpdater.checkCixf();

        //Verify status
        System.assertEquals(true,response);
    }
 
    //Negative test
	@isTest 
    static void checkCixfNegTest(){ 		
        String cixfId = '98765432101';
        
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestURI = 'https://fnni--ncino.cs69.my.salesforce.com/services/apexrest/account/' + cixfId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        //Call the method to test
        Boolean response = CdsUpdater.checkCixf();
        
        //Verify status
        System.assertEquals(false,response);
    }
    
    //Positvie test
    @isTest 
    static void addCustomerTest(){
        String cixfId = '12345678990';
        String name = 'CdsTestCustomer';

        RestRequest request = new RestRequest();
        request.requestURI = 'https://fnni--ncino.cs69.my.salesforce.com/services/apexrest/account';
        request.httpMethod = 'Post';
        
        //Call the method to test
        String result = CdsUpdater.addCustomer(cixfId, name); 
        System.assertEquals('SUCCESS',result);
    }
    
    //Negative test
    @isTest 
    static void addCustomerNegTest(){
        String cixfId = '12345678999';
        String name = 'CdsTestCustomer';
        
        //Call the method to test
        String result = CdsUpdater.addCustomer(cixfId, name); 
        System.assertEquals('FAILURE',result);
    }
    @isTest
    static void testUpdateLogs() {
        String cixfId = '12345678990';
        String name = 'CdsTestMeCustomer';

        RestRequest request = new RestRequest();
        request.requestURI = 'https://fnni--ncino.cs69.my.salesforce.com/services/apexrest/account';
        request.httpMethod = 'Post';
        
        //Call the method to test
        String result = CdsUpdater.addCustomer(cixfId, name); 
        List<FnboLog__c> fnlogList = new List<FnboLog__c>();
        
        fnlogList = [Select Action__c from FnboLog__c where SObject_Name__c = 'Account' Limit 5];
        System.assert(fnlogList.size() >0 );
        
        System.assertEquals('Create',fnlogList.get(0).Action__c);  
    }
}