force-app/main/default/objects/Account/fields/Reason_for_changing_owner__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_changing_owner__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason for changing owner</label>
    <length>110</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QualifyOwnershipWorkflow_Test.cls
@isTest
public class QualifyOwnershipWorkflow_Test {
    static testMethod void insertAccountandUpdate(){
      QualifyOwnershipWorkflow.QualifyOwnershipWorkflow();      
     // Account acct1 = new Account(name = 'ownerchange',
     //                             Reason_for_changing_owner__c = 'test',
     //                             recordTypeId = '01230000000sSMd',
     //                             ownerId = '005a000000BPHHy');
     // Insert acct1;
     // 
     // acct1.ownerId = '00530000005eEM1';
     // 
     // update acct1;
     // 
     // System.assertNotEquals(acct1.ownerId,'005a000000BPHHy');
     // System.assertEquals(acct1.ownerId,'00530000005eEM1');
     // System.assertNotEquals(acct1.Ownership_Change__c, True);
     // 
     // acct1.Ownership_Change__c = False;
     // update acct1;

     // acct1.ownerId = '005a000000BPHHy';
     // update acct1;
        
     // System.assertEquals(acct1.ownerId,'005a000000BPHHy');
     // System.assertEquals(acct1.Ownership_Change__c, False);
        
    }
}