force-app/main/default/objects/Account/fields/Source_Unfunded_Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_Unfunded_Trust_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Unfunded Trust ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue__c</fullName>
    <inlineHelpText>This field should be used for annualized revenue ONLY.</inlineHelpText>
    <label>Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/One_Time_Fees__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Fees__c</fullName>
    <inlineHelpText>This field is for one time / upfront fees ONLY</inlineHelpText>
    <label>One Time Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/Unfunded_Trust__c.object-meta.xml
<CustomObject>
    <description>Tracks Unfunded Trusts (FNBO has bee notified that we are assigned to be associated with a trust but it has not yet been funded</description>
    <label>Unfunded Trust</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unfunded Estate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unfunded Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_City__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Country__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Country__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_State__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Street__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Additional_Contact_Zip__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Contact Zip</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Assets_under_Management__c.field-meta.xml
<CustomField>
    <fullName>Assets_under_Management__c</fullName>
    <label>Assets under Management</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Billing_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Billing City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Billing_Country__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Billing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Billing_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Billing State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Billing_Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Billing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Billing_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Billing Zip</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Email__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Grantor_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Grantor_Phone__c.field-meta.xml
<CustomField>
    <fullName>Grantor_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grantor Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Unfunded_Trust__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Funded = We are named as fiduciary and chose to serve
Inactive = We are not named as fiduciary or chosen not to serve
Active = Everything else</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/fundTrustAccount_Test.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 07/22/2016
// Project: Unfunded Trust

@isTest
public class fundTrustAccount_Test {

    static testMethod void fundTrustAccount() {
        //08/08/2019 Added as part of test class fix -begin
        List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
        TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
        accountTriggerSupportSetting.Name = 'Account';
        accountTriggerSupportSetting.TriggerIsDisabled__c = true;
        triggerSupportList.add(accountTriggerSupportSetting);
        insert triggerSupportList;
        
        Unfunded_Trust__c unfund1 = new Unfunded_Trust__c(name = 'test123', 
                                                         Status__c = 'Active',
                                                         Additional_Contact_City__c = '',
                                                         Additional_Contact_Country__c = '',
                                                         Additional_Contact_Email__c = '',
                                                         Additional_Contact_First_Name__c = '',
                                                         Additional_Contact_Last_Name__c = '',
                                                         Additional_Contact_Phone__c = '',
                                                         Additional_Contact_State__c = '',
                                                         Additional_Contact_Street__c = '',
                                                         Additional_Contact_Zip__c = '',
                                                         Grantor_Billing_City__c = '',
                                                         Grantor_Billing_Country__c = '',
                                                         Grantor_Billing_State__c = '',
                                                         Grantor_Billing_Street__c = '',
                                                         Grantor_Billing_Zip__c = '',
                                                         Grantor_Email__c = '',
                                                         Grantor_First_Name__c = '',
                                                         Grantor_Last_Name__c = '',
                                                         Grantor_Phone__c ='');
        insert unfund1;
        
        System.assertEquals(unfund1.Status__c, 'Active');
        System.assertNotEquals(unfund1.Status__c, 'Funded');
        
        unfund1.Status__c = 'Funded';
        update unfund1;
        
        System.assertEquals(unfund1.Status__c, 'Funded');
        
        try {     
            unfund1.Status__c = 'Inactive';
            update unfund1;
        } catch (exception e) {
            
        }
        
        Unfunded_Trust__c unfund2 = new Unfunded_Trust__c(name = 'test123', 
                                                         Status__c = 'Active',
                                                         Additional_Contact_City__c = 'Richmond',
                                                         Additional_Contact_Country__c = 'Kenturky',
                                                         Additional_Contact_Email__c = 'ham@test.com',
                                                         Additional_Contact_First_Name__c = 'QA',
                                                         Additional_Contact_Last_Name__c = 'Tester',
                                                         Additional_Contact_Phone__c = '5712823848',
                                                         Additional_Contact_State__c = 'KY',
                                                         Additional_Contact_Street__c = '1234 Tester',
                                                         Additional_Contact_Zip__c = '22344',
                                                         Grantor_Billing_City__c = 'New Orleans',
                                                         Grantor_Billing_Country__c = 'USA',
                                                         Grantor_Billing_State__c = 'LA',
                                                         Grantor_Billing_Street__c = '1234 French Ave',
                                                         Grantor_Billing_Zip__c = '56733',
                                                         Grantor_Email__c = 'zero@gmail235.com',
                                                         Grantor_First_Name__c = '',
                                                         Grantor_Last_Name__c = 'Developer',
                                                         Grantor_Phone__c ='6885',
                                                         Assets_under_Management__c = 1000,
                                                         One_Time_Fees__c = 1500,
                                                         Annual_Revenue__c = 250);
        insert unfund2;
        
        System.assertNotEquals(unfund2.Status__c, 'Funded');
        System.assertEquals(unfund2.Status__c, 'Active');
        
        unfund2.Status__c = 'Funded';
        update unfund2;
        
        System.assertEquals(unfund2.Status__c, 'Funded');
        
        List<Account> testAcctCreated = [SELECT Id, Source_Unfunded_Trust_ID__c
                                         FROM Account];
        
        System.assertEquals(testAcctCreated.size(), 2);
        
        List<Opportunity> testOppCreated = [SELECT Id, AccountId
                                            FROM Opportunity];
        
        System.assertEquals(testOppCreated.size(), 2);
        
        ApexPages.currentPage().getParameters().put('id',unfund2.id);
        ApexPages.StandardController stdunfundedTrust2 = new ApexPages.StandardController(unfund2);
        unfundedTrustController unfundTrust = new unfundedTrustController(stdunfundedTrust2);
        
        test.startTest();
        Account[] unFundedAccounts = unfundTrust.getAccounts();
        Opportunity[] unFundedOpportunities = unfundTrust.getOpportunities();
        Boolean renderPage = unfundTrust.getRenderPage();
        System.assertNotEquals(null, unFundedAccounts);
        System.assertNotEquals(null, unFundedOpportunities);
        System.assertNotEquals(null, renderPage);
        test.stopTest();
    
    }
}