force-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <description>Permissions based on various Objects in Salesforce, used to gather information on user / user profile and permissions available on Salesforce.</description>
    <label>Permission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Permission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission__c/fields/create__c.field-meta.xml
<CustomField>
    <fullName>create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions  - Create</description>
    <label>create</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/delete__c.field-meta.xml
<CustomField>
    <fullName>delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions - Delete</description>
    <label>delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/edit__c.field-meta.xml
<CustomField>
    <fullName>edit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions - Edit</description>
    <label>edit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <description>Object Permissions ID</description>
    <encryptionScheme>None</encryptionScheme>
    <label>id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/modifyAll__c.field-meta.xml
<CustomField>
    <fullName>modifyAll__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions - ModifyAll</description>
    <label>modifyAll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/obj__c.field-meta.xml
<CustomField>
    <fullName>obj__c</fullName>
    <description>ObjectPermissions SobjectType</description>
    <encryptionScheme>None</encryptionScheme>
    <label>obj</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/profile__c.field-meta.xml
<CustomField>
    <fullName>profile__c</fullName>
    <description>Profile Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>profile</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/read__c.field-meta.xml
<CustomField>
    <fullName>read__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions  - Read</description>
    <label>read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permission__c/fields/viewAll__c.field-meta.xml
<CustomField>
    <fullName>viewAll__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ObjectPermissions  - ViewAll</description>
    <label>viewAll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PermissionController.cls
public without sharing class PermissionController {

    Map<Id, Id> permSetProfileMap = new Map<Id, Id>() ;
    Map<Id, String> profileMap = new Map<Id, String>();
     
    List<ObjectPermissions> profileObjectPermList = new  List<ObjectPermissions>();
    
    public List<Permission__c> permissions = new List<Permission__c>();
    
    public List<Permission__c> getPermissions() {
        return permissions;
    }

    public PermissionController() {
        populatePermissionList();
    }

    public void populatePermissionList() {

        For(PermissionSet ps : [SELECT Id, ProfileId 
                                FROM PermissionSet 
                                WHERE IsOwnedbyProfile = TRUE]) {              
            permSetProfileMap.put(ps.id, ps.ProfileId);
        }  
            
        For(ObjectPermissions op : [SELECT id, ParentId, PermissionsCreate, PermissionsRead, PermissionsEdit,
                                    PermissionsDelete, PermissionsViewAllRecords, PermissionsModifyAllRecords, SobjectType 
                                    FROM ObjectPermissions 
                                    WHERE ParentId
                                    IN: permSetProfileMap.keySet()]) {                
            profileObjectPermList.add(op);
        }
            
        For(Profile p : [SELECT Id, Name FROM Profile]) {              
            profileMap.put(p.id, p.Name);
        }           

        For (ObjectPermissions op: profileObjectPermList) {
            Permission__c permission = new Permission__c();
                      
            if (profileMap.containsKey(permSetProfileMap.get(op.parentId))) {
                permission.id__c = permSetProfileMap.get(op.parentId); 
                permission.profile__c = profileMap.get(permission.id__c);         
                permission.obj__c = op.sObjectType;
                permission.create__c = op.PermissionsCreate;
                permission.read__c = op.PermissionsRead;
                permission.edit__c = op.PermissionsEdit;
                permission.delete__c = op.PermissionsDelete;
                permission.viewAll__c = op.PermissionsViewAllRecords;
                permission.modifyAll__c = op.PermissionsModifyAllRecords;
                
                permissions.add(permission); 
             }
        }
    }
}