force-app/main/default/objects/Organization_Contact__c/Organization_Contact__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganizationContact</customHelpPage>
    <description>A contact that works for a Volunteer organization.</description>
    <label>Organization Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Volunteer Org Contact Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Contact__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Contact__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>East Timor</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Contact__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>R00N30000002FFibEAG</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>East Timor</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Date_Time_formula__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_formula__c</fullName>
    <formula>LEFT(TEXT(Date_and_Time__c ), 16)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Date &amp; Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;&lt;provide a brief description here&gt;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/IsOpportunity__c.field-meta.xml
<CustomField>
    <fullName>IsOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A volunteer activity which is not associated with a specific date or time (e.g., Big Brother/Big Sister mentoring).</inlineHelpText>
    <label>Ongoing Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <description>COUNT of Volunteer Activity Participant records</description>
    <label>Current Participants</label>
    <summaryForeignKey>Volunteer_Activity_Participant__c.Volunteer_Activity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Events__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Events__c</fullName>
    <label>Activity Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beautification/Cleaning/Painting/Gardening</fullName>
            </value>
            <value>
                <fullName>Business Assistance</fullName>
            </value>
            <value>
                <fullName>CRA Community Contact</fullName>
            </value>
            <value>
                <fullName>CRA Community Outreach</fullName>
            </value>
            <value>
                <fullName>Education/Training/Tutoring</fullName>
            </value>
            <value>
                <fullName>Faith-based</fullName>
            </value>
            <value>
                <fullName>Fundraising/Event Management</fullName>
            </value>
            <value>
                <fullName>Mentoring/leadership development</fullName>
            </value>
            <value>
                <fullName>Professional Skills</fullName>
            </value>
            <value>
                <fullName>Walks/Runs/Parades/Booth/Table</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Building/Construction/Rehabilitation/Home Maintenance</fullName>
            </value>
            <value>
                <fullName>Community Event Participation</fullName>
            </value>
            <value>
                <fullName>Food serving/distributing/sorting/delivering</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Health Care and Social Services</fullName>
            </value>
            <value>
                <fullName>Disaster/Emergency Services</fullName>
            </value>
            <value>
                <fullName>Civic Participation/Political</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Organization__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>East Timor</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestVolActivityQuickCreateController.cls
@isTest
private class TestVolActivityQuickCreateController{
        
    static void assertNullVolunteerOrganization( Volunteer_Organization__c vo ){
        
        System.assert( vo.id == null );
        System.assert( vo.City__c == null );
        System.assert( vo.Country__c == null );
        System.assert( vo.Fax__c == null );
        System.assert( vo.Phone__c == null );
    }

    testmethod static void testGetNpo(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        Volunteer_Organization__c vo = controller.npo;
        assertNullVolunteerOrganization( vo );
    }
    
    testmethod static void testGetContact(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        Organization_Contact__c oc = controller.oc;
        
        System.assert( oc.id == null );
        System.assert( oc.Mailing_City__c == null );
        System.assert( oc.Mailing_Country__c == null );
        System.assert( oc.Email__c == null );
        System.assert( oc.First_Name__c == null );
    } 
    
    testmethod static void testGetActivity(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        Volunteer_Activity__c va = controller.va;
        
        System.assert( va.id == null );
        System.assert( va.Description__c == null );
        System.assert( va.Volunteer_Events__c == null );
        System.assert( va.Date_Time_formula__c == null );
        System.assert( va.Total_Number_of_Participants__c == null );
    }
    
    testmethod static void testGetActivityType(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        System.assert( controller.activityType == 'e' );
    }
    
    testmethod static void testSetActivityType(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        String activityType     = 'testActivityType';
        controller.activityType = activityType;
        
        System.assert( controller.activityType == activityType );
    }
    
    testmethod static void testGetActivityTypes(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        
        List<SelectOption> options = controller.getActivityTypes();
        
        System.assert( options.size() == 3 );
        
        for( SelectOption option : options ){
            System.assert( option != null );
        }
    }    
    
    testmethod static void testGetOrgIds(){
        
        Volunteer_Organization__c[] voList = [ select id, name from Volunteer_Organization__c order by Name ];
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        
        List<SelectOption> options = controller.getOrgIds();
        
        //System.assert( options.size() == voList.size() + 1 ); commented this out to test 08152014 BDJ 
        
        for( SelectOption option : options ){
            System.assert( option != null );
        }
    } 
    
    testmethod static void testRefreshOrgFieldsForNullOrgId(){
        
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        controller.refreshOrgFields();
        Volunteer_Organization__c vo = controller.npo;
        assertNullVolunteerOrganization( vo );
    }   
    
    testmethod static void testRefreshOrgFieldsForNonNullOrgId(){
        
        Volunteer_Organization__c voExpected = TestCommon.setupVolunteerOrganization();
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        controller.orgId = voExpected.id;                   
        controller.refreshOrgFields();
        Volunteer_Organization__c voActual = controller.npo;
        
        System.assertEquals( voActual.id, voExpected.id );
        System.assertEquals( voActual.name, voExpected.name );
    }
  
    testmethod static void testSave(){
        
        // Updating the test to actually try to save a new org, contact and activity
        // Previously, it queried for any org in the DB, then saved with empty contact and activity
        //    then got an error on save, but still passed if that org happened to have only one
        //    contact, and that happened to be the primary.
        VolActivityQuickCreateController controller = new VolActivityQuickCreateController();
        
        controller.step1();
        controller.step2();
        controller.step3();
        controller.step4();
        controller.cancel();
        controller.displayNoPermPage();
        
        Volunteer_Organization__c npo   = controller.npo;
        Organization_Contact__c contact = controller.oc;
        Volunteer_Activity__c activity  = controller.va;
        
        npo.Name                        = 'TestSaveOrg';
        contact.Name                    = 'TestSaveContact';
        activity.IsOpportunity__c       = true;
        activity.Volunteer_Events__c    = 'Administrative/Clerical';
        activity.Name                   = 'TestSaveActivity';
        PageReference pageRef           = controller.save();
        
        Volunteer_Organization__c voActual = [ select id, name, Status__c 
                                                from Volunteer_Organization__c 
                                                where Id =: npo.id 
                                                limit 1 ];
                                              
        Organization_Contact__c ocActual = [ select id, Primary_Contact__c 
                                                from Organization_Contact__c 
                                                where Volunteer_Organization__c =: npo.id ];
                                              
        Volunteer_Activity__c vaActual = [select id, name, Primary_Contact__c 
                                            from Volunteer_Activity__c 
                                            where Volunteer_Organization__c =: npo.id 
                                            limit 1 ];
                                              
        System.assertEquals( voActual.Status__c, 'Active' );
        System.assertEquals( ocActual.Primary_Contact__c, true );
        System.assertEquals( vaActual.Primary_Contact__c, ocActual.id );
    }                   
}