force-app/main/default/objects/Organization_Contact__c/Organization_Contact__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganizationContact</customHelpPage>
    <description>A contact that works for a Volunteer organization.</description>
    <label>Organization Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Volunteer Org Contact Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Contact__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>R00N30000002FFibEAG</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;&lt;provide a brief description here&gt;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Organization_Cause__c.field-meta.xml
<CustomField>
    <fullName>Organization_Cause__c</fullName>
    <formula>CASE(1, 
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Animal Related&quot;), 1, 0), &quot;Animal Related&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Arts&quot;), 1, 0), &quot;Arts&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;BCorp&quot;), 1, 0), &quot;BCorp&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Culture&quot;), 1, 0), &quot;Culture&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Economic Development&quot;), 1, 0), &quot;Economic Development&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Education K-12&quot;), 1, 0), &quot;Education K-12&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Environment&quot;), 1, 0), &quot;Environment&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Healthcare&quot;), 1, 0), &quot;Healthcare&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Humanities&quot;), 1, 0), &quot;Humanities&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Human Services&quot;), 1, 0), &quot;Human Services&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;International Development&quot;), 1, 0), &quot;International Development&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Public/Social Benefit&quot;), 1, 0), &quot;Public/Social Benefit&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Religious&quot;), 1, 0), &quot;Religious&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Research&quot;), 1, 0), &quot;Research&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Social Justice&quot;), 1, 0), &quot;Social Justice&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Technology&quot;), 1, 0), &quot;Technology&quot;,
IF(ISPICKVAL(Volunteer_Organization__r.Organization_Cause__c , &quot;Youth&quot;), 1, 0), &quot;Youth&quot;,
&quot;&quot;)</formula>
    <label>Organization Cause</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama (AL)</fullName>
            </value>
            <value>
                <fullName>Alaska (AK)</fullName>
            </value>
            <value>
                <fullName>Alberta (AB)</fullName>
            </value>
            <value>
                <fullName>Arizona (AZ)</fullName>
            </value>
            <value>
                <fullName>Arkansas (AR)</fullName>
            </value>
            <value>
                <fullName>British Columbia (BC)</fullName>
            </value>
            <value>
                <fullName>California (CA)</fullName>
            </value>
            <value>
                <fullName>Colorado (CO)</fullName>
            </value>
            <value>
                <fullName>Connecticut (CT)</fullName>
            </value>
            <value>
                <fullName>Delaware (DE)</fullName>
            </value>
            <value>
                <fullName>District of Columbia (DC)</fullName>
            </value>
            <value>
                <fullName>Florida (FL)</fullName>
            </value>
            <value>
                <fullName>Georgia (GA)</fullName>
            </value>
            <value>
                <fullName>Hawaii (HI)</fullName>
            </value>
            <value>
                <fullName>Idaho (ID)</fullName>
            </value>
            <value>
                <fullName>Illinois (IL)</fullName>
            </value>
            <value>
                <fullName>Indiana (IN)</fullName>
            </value>
            <value>
                <fullName>Iowa (IA)</fullName>
            </value>
            <value>
                <fullName>Kansas (KS)</fullName>
            </value>
            <value>
                <fullName>Kentucky (KY)</fullName>
            </value>
            <value>
                <fullName>Louisiana (LA)</fullName>
            </value>
            <value>
                <fullName>Maine (ME)</fullName>
            </value>
            <value>
                <fullName>Manitoba (MB)</fullName>
            </value>
            <value>
                <fullName>Maryland (MD)</fullName>
            </value>
            <value>
                <fullName>Massachusetts (MA)</fullName>
            </value>
            <value>
                <fullName>Michigan (MI)</fullName>
            </value>
            <value>
                <fullName>Minnesota (MN)</fullName>
            </value>
            <value>
                <fullName>Mississippi (MS)</fullName>
            </value>
            <value>
                <fullName>Missouri (MO)</fullName>
            </value>
            <value>
                <fullName>Montana (MT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Organization__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Organization_Cause__c.field-meta.xml
<CustomField>
    <fullName>Organization_Cause__c</fullName>
    <label>Organization Cause</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access to Culture</fullName>
            </value>
            <value>
                <fullName>Athletics</fullName>
            </value>
            <value>
                <fullName>Community Cohesion</fullName>
            </value>
            <value>
                <fullName>Educated Workforce</fullName>
            </value>
            <value>
                <fullName>Good Health</fullName>
            </value>
            <value>
                <fullName>Stable Housing</fullName>
            </value>
            <value>
                <fullName>Strong Local Economies</fullName>
            </value>
            <value>
                <fullName>Sustained Environment</fullName>
            </value>
            <value>
                <fullName>Vibrant Neighborhoods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Parent_Organization__c.field-meta.xml
<CustomField>
    <fullName>Parent_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>ChildOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Alabama (AL)</fullName>
            </value>
            <value>
                <fullName>Alaska (AK)</fullName>
            </value>
            <value>
                <fullName>Alberta (AB)</fullName>
            </value>
            <value>
                <fullName>Arizona (AZ)</fullName>
            </value>
            <value>
                <fullName>Arkansas (AR)</fullName>
            </value>
            <value>
                <fullName>British Columbia (BC)</fullName>
            </value>
            <value>
                <fullName>California (CA)</fullName>
            </value>
            <value>
                <fullName>Colorado (CO)</fullName>
            </value>
            <value>
                <fullName>Connecticut (CT)</fullName>
            </value>
            <value>
                <fullName>Delaware (DE)</fullName>
            </value>
            <value>
                <fullName>District of Columbia (DC)</fullName>
            </value>
            <value>
                <fullName>Florida (FL)</fullName>
            </value>
            <value>
                <fullName>Georgia (GA)</fullName>
            </value>
            <value>
                <fullName>Hawaii (HI)</fullName>
            </value>
            <value>
                <fullName>Idaho (ID)</fullName>
            </value>
            <value>
                <fullName>Illinois (IL)</fullName>
            </value>
            <value>
                <fullName>Indiana (IN)</fullName>
            </value>
            <value>
                <fullName>Iowa (IA)</fullName>
            </value>
            <value>
                <fullName>Kansas (KS)</fullName>
            </value>
            <value>
                <fullName>Kentucky (KY)</fullName>
            </value>
            <value>
                <fullName>Louisiana (LA)</fullName>
            </value>
            <value>
                <fullName>Maine (ME)</fullName>
            </value>
            <value>
                <fullName>Manitoba (MB)</fullName>
            </value>
            <value>
                <fullName>Maryland (MD)</fullName>
            </value>
            <value>
                <fullName>Massachusetts (MA)</fullName>
            </value>
            <value>
                <fullName>Michigan (MI)</fullName>
            </value>
            <value>
                <fullName>Minnesota (MN)</fullName>
            </value>
            <value>
                <fullName>Mississippi (MS)</fullName>
            </value>
            <value>
                <fullName>Missouri (MO)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VolActivityQuickCreateController.cls
/**
* This class is the controller behind the Activity Quick Create wizard.
*/
public with sharing class VolActivityQuickCreateController{
	
    // These three class variables maintain the state of the wizard.
    // When users enter data into the wizard, their input is stored
    // in these variables.
    String npoStatus = 'Active';
	
	/**
    * Constructor
    */ 
    public VolActivityQuickCreateController(){
        this.activityType = 'e';
    }

	/**
    * Getter setter method for orgId
    * @return 
    */ 
    public String orgId{ 
        get; 
        set{
            this.orgId = value;
        }
    }
    
    /**
    * Getter setter method for npo
    * @return Volunteer_Organization__c
    */ 
    public Volunteer_Organization__c npo{
        get{
            if( this.npo == null ){
                this.npo = new Volunteer_Organization__c();
            } 
            
            return this.npo;
        }
        set;
    }
    
    /**
    * Getter setter method for oc
    * @return Organization_Contact__c
    */ 
    public Organization_Contact__c oc{
        get{
            if( this.oc == null ){
                this.oc = new Organization_Contact__c();
            }
            
            return this.oc;
        }
        set;
    }
    
    /**
    * getter setter method for va
    * @return Volunteer_Activity__c
    */ 
    public Volunteer_Activity__c va{
        get{
            if( this.va == null ){
                this.va = new Volunteer_Activity__c();
            }
            
            return this.va;
        }
        set;
    }
    
    /**
    * Getter Setter for activityType
    * @return String
    */ 
    public String activityType{
        get;
        set;
    }
    
    /**
    * Generate the list of activity types used within the wizard.
    * @return options
    */ 
    public List<SelectOption> getActivityTypes(){
    	
        List<SelectOption> options = new List<SelectOption>(); 
        
        options.add( new SelectOption( 'e', System.Label.VolActivityWizardActivityTypeVolEvent ) ); 
        options.add( new SelectOption( 'o', System.Label.VolActivityWizardActivityTypeOngoingOpp ) ); 
        options.add( new SelectOption( 'n', System.Label.VolActivityWizardActivityTypeOngoingOppNoLoc ) ); 
        
        return options; 
    }

    /**
    * Dynamically generate the categories from the Feature_Category__c object.
    * @return optionList
    */ 
    public List<SelectOption> getOrgIds(){
    	
        List<SelectOption> optionList = new List<SelectOption>();
        
        // Add a null option to force the user to make a selection.
        optionList.add( new SelectOption( '', '- New -' ) );
        
        for (Volunteer_Organization__c fc : [ select id, name from Volunteer_Organization__c order by Name limit 1000  ] ){
            optionList.add( new SelectOption( fc.id, fc.name ) );
        }
        
        return optionList;
    }
    
    /**
    * Method for refreshing org fields
    * @return PageReference
    */ 
    public PageReference refreshOrgFields(){
    	
        if( orgId == null ){
            this.npo = new Volunteer_Organization__c();
        } 
        else{
            this.npo = [ select id, name, Parent_Organization__c, Organization_Cause__c, Website__c, Phone__c, 
                                Fax__c, Description__c, Street__c, City__c, State_Province__c, Zip_Postal_Code__c, Country__c 
                        	from Volunteer_Organization__c 
                        	where Id =: orgId ] ;
        }
        
        // returning null indicates the same page should be returned
        return null;
    }
    
    /**
    * Navigation
    * @return PageReference
    */ 
    public PageReference step1(){
        return Page.VolActivityQuickCreate_npo;
    }
    
    /**
    * Navigation
    * @return PageReference
    */ 
    public PageReference step2(){
        return Page.VolActivityQuickCreate_contact;
    }
    
    /**
    * Navigation
    * @return PageReference
    */ 
    public PageReference step3(){
        return Page.VolActivityQuickCreate_activity;
    }
    
    /**
    * Navigation
    * @return PageReference
    */ 
    public PageReference step4(){
    	
        this.va.IsOpportunity__c =! activityType.equals( 'e' );

        return Page.VolActivityQuickCreate_activitydetail;
    }
  
    /**
    * Cancel the volunteer activity creation and send the user to the volunteer activity list page.
    * @return activityPage
    */ 
    public PageReference cancel(){
        PageReference activityPage = new PageReference( '/' + VolActivity.KeyPrefix + '/o' );
        activityPage.setRedirect( true );
        
        return activityPage;
    }
    
    /**
    * This method performs the final save for all three objects, and
    * then navigates the user to the detail page for the new activity.
    * @return PageReference
    */ 
    public PageReference save(){     
        // transaction control.
        Savepoint sp = Database.setSavePoint();
        
        // Keeping copies of the variables because rollback destroys them.
        Volunteer_Organization__c backup_npo 	= ( this.npo != null ) ? this.npo.clone( true, true ) : null;
        Organization_Contact__c backup_contact 	= ( this.oc != null ) ? this.oc.clone( true, true ) : null;
        Volunteer_Activity__c backup_activity 	= ( this.va != null ) ? this.va.clone( true, true ) : null;
        
        try{
            // Create the organization
            this.npo.Status__c = 'Active';
            upsert this.npo;
            
            // Create the contact
            this.oc.Primary_Contact__c = true;
            
            this.oc.Volunteer_Organization__c = this.npo.id;
            
            insert this.oc;
            
            // Create the activity
            this.va.Primary_Contact__c = this.oc.id;
            
            this.va.Volunteer_Organization__c = this.npo.id;
            
            insert this.va;
        } 
        catch( Exception ex ){
            ApexPages.addMessages( ex );
            Database.rollback( sp );
            this.npo 	= backup_npo;
            this.oc 	= backup_contact;
            this.va 	= backup_activity;
            
            return null;
        }
        
        // Send the user to the view page for the new activity.
        ApexPages.StandardController controller = new ApexPages.StandardController( this.va );
        
        return controller.view();        
    }

    /**
    * Should we redirect to the no permission page.
    * @return PageReference
    */ 
    public PageReference displayNoPermPage(){
    	   
        if( VolActivity.CurrentUserHasCreatePermission ){
            return null;
        }

        return Page.VolActivityQuickCreateSecurity_noperm;
    }   
}