force-app/main/default/objects/CoreDataLoadStatistic__c/CoreDataLoadStatistic__c.object-meta.xml
<CustomObject>
    <description>Custom object used to report daily &quot;Core&quot; data loads</description>
    <label>CoreDataLoadStatistic</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoreDataLoadStatistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>Type of data that was loaded: PersonCustomer, BusinessCustomer, CustomerVariance, Junction, FinancialAccount...</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Failed_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Failed_Record_Count__c</fullName>
    <description>Number of records that could not be loaded into org</description>
    <label>Failed Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Load_Date__c.field-meta.xml
<CustomField>
    <fullName>Load_Date__c</fullName>
    <description>Date CoreData was loaded into ORG</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Load Failed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Successful_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Successful_Record_Count__c</fullName>
    <description>Number of records successfully loaded into org</description>
    <label>Successful Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CoreDataLoadStatistic__c/fields/Total_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Record_Count__c</fullName>
    <label>Total Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/Dataload_Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object receives daily person and business customer loading error info from two _error.csv files.</description>
    <label>Dataload Error Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Dataload Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dataload Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Assignee</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Bank_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bank Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/CIXF__c.field-meta.xml
<CustomField>
    <fullName>CIXF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIXF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/CIXF_ID__c.field-meta.xml
<CustomField>
    <fullName>CIXF_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIXF ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Date_Insert__c.field-meta.xml
<CustomField>
    <fullName>Date_Insert__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Insert</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/FNB_System_of_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>FNB_System_of_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FNB System of Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Middle Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/PL_ID__c.field-meta.xml
<CustomField>
    <fullName>PL_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PL ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Precision_Lender_ID__c.field-meta.xml
<CustomField>
    <fullName>Precision_Lender_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Precision Lender ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/Trigger_Type__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trigger Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataload_Error_Log__c/fields/TriggerData_ID__c.field-meta.xml
<CustomField>
    <fullName>TriggerData_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TriggerData ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dlMatrixController.cls
public class dlMatrixController {
    @AuraEnabled
    public static List<CoreDataLoadStatistic__c> fetchDailyStats(Date insertDate) {
        List<CoreDataLoadStatistic__c> dailyStats = [SELECT Data_Type__c, Status__c, Total_Record_Count__c, Successful_Record_Count__c, Failed_Record_Count__c 
                                                     FROM CoreDataLoadStatistic__c WHERE Load_Date__c = :insertDate];
        return dailyStats;
    }
    
    @AuraEnabled
    public static List<Dataload_Error_Log__c> getErrorLog(Date insertDate, String objType)
    {
        List<Dataload_Error_Log__c> ErrorLogFieldValues = [SELECT FNB_System_of_Record_Id__c, First_Name__c, Middle_Name__c, Last_Name__c, Business_Name__c, DBA__c, 
                                                  Tax_ID__c, TriggerData_ID__c, Bank_Number__c, Trigger_Type__c, Assignee__c, PL_ID__c, Precision_Lender_ID__c, CIXF_ID__c, CIXF__c,
                                                  Error__c, Date_Insert__c FROM Dataload_Error_Log__c 
                                                  WHERE Date_Insert__c = :insertDate AND Object_Type__c = :objType];
        return ErrorLogFieldValues;
    }
}