force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Unit A</fullName>
            </value>
            <value>
                <fullName>Business Unit B</fullName>
            </value>
            <value>
                <fullName>Business Unit C</fullName>
            </value>
            <value>
                <fullName>Business Unit D</fullName>
            </value>
            <value>
                <fullName>Business Unit E</fullName>
            </value>
            <value>
                <fullName>Business Unit F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>East Timor</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;&lt;provide a brief description here&gt;&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <label>Duration (hours)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of volunteers who have been assigned to nonprofit customers. When integrated with the hub, volunteers will need to know if an activity is still available for volunteer sign up or if it&#39;s full and closed</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/Volunteer_Activity_Participant__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpParticipant</customHelpPage>
    <description>A junction object used for linking Volunteer Activities to a participant in the activity and to the participant&#39;s role hierarchy at the time of the activity</description>
    <label>Volunteer Participant</label>
    <nameField>
        <displayFormat>Participant ID: {000000}</displayFormat>
        <label>Volunteer Activity Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>This field is used only for reporting and is hidden from the end user.  It is maintained by apex code by copying the values from the user record when participant is added and when the User record changes.</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Unit A</fullName>
            </value>
            <value>
                <fullName>Business Unit B</fullName>
            </value>
            <value>
                <fullName>Business Unit C</fullName>
            </value>
            <value>
                <fullName>Business Unit D</fullName>
            </value>
            <value>
                <fullName>Business Unit E</fullName>
            </value>
            <value>
                <fullName>Business Unit F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <description>If left blank, this field is updated programmatically when new volunteer activity participants are created.</description>
    <inlineHelpText>If left blank, this field is updated based on the Activity duration.</inlineHelpText>
    <label>Participation (hours)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N30000002ECnbEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Volunteer_Activity__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Activity__c</fullName>
    <label>Volunteer Activity</label>
    <referenceTo>Volunteer_Activity__c</referenceTo>
    <relationshipName>R00N30000002ECnNEAW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Organization__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>East Timor</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestVolActivity.cls
// Apex test methods for the VolActivity class.
@IsTest
private class TestVolActivity{
             
    // Test the sign-up process.
    testmethod static void testSignUp(){
        
        User newUser = [ select id from User where isActive = true limit 1 ];

        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity(vo, 5);

        // test send reminder/update/cancellation to an event that has no participants
        ApexPages.Message result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtREMINDER );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        result = VolActivity.sendUpdate(newAct.Id, EmailManager.MessageType.mtUPDATE );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        result = VolActivity.sendCancellationToAll(newAct.Id, false );
        System.assertEquals( ApexPages.Severity.INFO, result.getSeverity() );

        newAct = VolActivity.getRecord(newAct.Id);
        System.assertEquals( System.Label.VolActivityStatusCancelled, newAct.Status__c );

        newAct.Status__c = 'New';
        update newAct;
        
        System.assertEquals( ApexPages.Severity.INFO,  VolActivity.signUp( newAct.Id,newUser.Id ).getSeverity() );
                
        Volunteer_Activity_Participant__c[] vpList = [ select Id,Name 
                                                        from Volunteer_Activity_Participant__c
                                                        where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        newAct.Status__c = 'New';
        update newAct;
        
        result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtREMINDER );
        System.assertEquals( ApexPages.Severity.INFO, result.getSeverity() );

        result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtUPDATE );
        System.assertEquals( ApexPages.Severity.INFO, result.getSeverity() );

        List<User> signedUpUsers = new List<User>();
        signedUpUsers.add( newUser );
        Set<String> resList = VolActivity.getSignedUpUsers( newAct.Id,signedUpUsers );
        System.assertEquals( 1, resList.size() );
        
        // Sign up the same user: expect an error
        System.assertEquals( ApexPages.Severity.ERROR,  VolActivity.signUp( newAct.Id,newUser.Id ).getSeverity() );
        
        vpList = [ select Id,Name 
                    from Volunteer_Activity_Participant__c
                    where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        System.assertEquals( vpList.size(), 1 );
        
        Boolean boolResp = VolActivity.sendSignup( newAct.Id, newUser.Id );
        
        System.assertEquals( false, boolResp );

        // Send reminder to Cancelled Activity
        newAct.Status__c = System.Label.VolActivityStatusCancelled;
        update newAct;
        
        result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtREMINDER );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtUPDATE );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        // Send reminder to an activity that has no organization: this should fail.
        newAct.Status__c ='New';
        newAct.Volunteer_Organization__c = null;
        update newAct;
        
        result = VolActivity.sendUpdate( newAct.Id, EmailManager.MessageType.mtREMINDER );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        result = VolActivity.sendUpdate(newAct.Id, EmailManager.MessageType.mtUPDATE );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        // Delete the activity and check if the participants got deleted.
        newAct.Volunteer_Organization__c = TestCommon.setupVolunteerOrganization().Id;
        update newAct;
                        
        delete newAct;
        
        vpList = [ select Id,Name 
                    from Volunteer_Activity_Participant__c
                    where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        System.assertEquals( vpList.size(), 0 );
    }
    
    // Test deleting a participant.
    testmethod static void testDeleteParticipant(){
        
        User newUser                    = TestCommon.setupUser();
        Volunteer_Organization__c vo    = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct    = TestCommon.setupActivity(vo, 5);

        System.assertEquals(ApexPages.Severity.INFO,  VolActivity.signUp(newAct.Id, newUser.Id).getSeverity());
        
        Volunteer_Activity_Participant__c[] vpList = [ select Id,Name 
                                                        from Volunteer_Activity_Participant__c
                                                        where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
        
        System.assertEquals(vpList.size(),1);
        
        delete vpList[0];
        
        vpList = [ select Id,Name 
                    from Volunteer_Activity_Participant__c
                    where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        System.assertEquals( vpList.size(), 0 );
    } 

    testmethod static void testAnotherUserSignUp(){
        
        User newUser                    = TestCommon.setupUser();
        Volunteer_Organization__c vo    = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct    = TestCommon.setupActivity( vo, 5 );

        Volunteer_Activity_Participant__c vp = new Volunteer_Activity_Participant__c( User__c = newUser.Id, Volunteer_Activity__c = newAct.Id );
        insert vp;

        Volunteer_Activity_Participant__c[] vpList = [ select Id,Name 
                                                        from Volunteer_Activity_Participant__c
                                                        where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];

        System.assertEquals( vpList.size(), 1 );
    }

    // test invalid parameters to public methods
    testmethod static void testInvalidData(){
        
        System.assertEquals( ApexPages.Severity.ERROR,  VolActivity.signUp( 'a003000000BTY44', 'a003000000BVY44' ).getSeverity() );

        ApexPages.Message result = VolActivity.sendUpdate( 'a003000000BTY44', EmailManager.MessageType.mtREMINDER );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity()) ;

        result = VolActivity.sendUpdate( 'a003000000BTY44', EmailManager.MessageType.mtUPDATE );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        result = VolActivity.sendCancellationToAll( 'a003000000BTY44', false );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );

        Boolean boolResp = VolActivity.sendCancellationToUserRemoved( 'a003000000BTY44', 'a003000000BVY44' );
        System.assertEquals( false, boolResp );

        boolResp = VolActivity.sendCancellationToUserRemoved( 'a003000000BTY44', null );
        System.assertEquals( false, boolResp );

        User newUser = TestCommon.setupUser();

        System.assertEquals( ApexPages.Severity.ERROR,  VolActivity.signUp( 'a003000000BTY44', newUser.Id ).getSeverity() );

        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity( vo, 5 );

        System.assertEquals( ApexPages.Severity.ERROR,  VolActivity.signUp( newAct.Id, 'a003000000BTY44' ).getSeverity() );

        boolResp  = VolActivity.sendSignup( null, newUser.Id );
        System.assertEquals( boolResp, false );

        boolResp  = VolActivity.sendSignup( newAct.Id, 'a003000000BTY44' );
        System.assertEquals( boolResp, false );
    }

    testmethod static void testCancellation(){
        
        User [] newUsers                = TestCommon.setupUsers();
        Volunteer_Organization__c vo    = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct    = TestCommon.setupActivity( vo, 5 );

        for( User user : newUsers ){
            System.assertEquals( ApexPages.Severity.INFO,  VolActivity.signUp( newAct.Id, user.Id ).getSeverity() );
        }
   
        Boolean response = VolActivity.sendCancellationToUserRemoved( newAct.Id, newUsers[0].Id );
        System.assertEquals( false, response );

        try{
            delete vo;
        }
        catch( Exception ex ){
            System.assert( true );
        }
        
        response = VolActivity.sendCancellationToUserRemoved( newAct.Id, newUsers[0].Id );
        System.assertEquals( false, response );

        vo = TestCommon.setupVolunteerOrganization();
        
        newAct.Volunteer_Organization__c = vo.Id;
        update newAct;

        ApexPages.Message result = VolActivity.sendCancellationToAll( newAct.Id, false );
        System.assertEquals( ApexPages.Severity.INFO, result.getSeverity() );

        newAct.Status__c = System.Label.VolActivityStatusCancelled;
        update newAct;
        
        result = VolActivity.sendCancellationToAll( newAct.Id, false );
        System.assertEquals( ApexPages.Severity.ERROR, result.getSeverity() );
    }

    // test deleting an array of Volunteer_Activity__c objects
    testmethod static void testDeleteTriggerBulk(){
        
        Volunteer_Organization__c vo        = TestCommon.setupVolunteerOrganization();
        List<Volunteer_Activity__c> vaList  = new List<Volunteer_Activity__c>();
 
        for( integer i = 0; i < 5; i++ ){
            vaList.Add( TestCommon.setupActivity( vo, 5 ) );
        }
        
        try{
            Database.delete( vaList );
            Database.delete( vo );
            
            System.assert( true );
        }catch( Exception ex ){
            System.assert( false );
        }
        
    }

    testmethod static void testMaxUserLimit(){

        User [] testUsers   = TestCommon.setupUsers();
        User newUser        = testUsers[0];
        User anotherUser    = testUsers[1];

        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity( vo, 1 );

        System.assertEquals( ApexPages.Severity.INFO,  VolActivity.signUp( newAct.Id, newUser.Id ).getSeverity() );
        
        Volunteer_Activity_Participant__c[] vpList = [ select Id, Name 
                                                        from Volunteer_Activity_Participant__c
                                                        where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        System.assertEquals( vpList.size(), 1 );
        
        // Sign up the another user when max limit is 1: expect an error
        System.assertEquals( ApexPages.Severity.ERROR,  VolActivity.signUp( newAct.Id, anotherUser.Id ).getSeverity() );
        
        vpList = [ select Id,Name 
                    from Volunteer_Activity_Participant__c
                    where Volunteer_Activity__c =: newAct.Id and User__c =: newUser.Id ];
                                                
        System.assertEquals( vpList.size(), 1 );
    }

    testmethod static void testActivityParticipant(){
        
        User newUser = TestCommon.setupUser();

        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity( vo, 5 );

        Volunteer_Activity_Participant__c vp = new Volunteer_Activity_Participant__c( User__c=newUser.Id, Volunteer_Activity__c = newAct.Id );
        insert vp;
        
        System.assertEquals( 'true', 'true' );

        vp.Business_Unit__c = 'Business Unit A';
        update vp;

        Volunteer_Activity_Participant__c[] vpList = [ select Id,Name,Business_Unit__c 
                                                         from Volunteer_Activity_Participant__c
                                                         where Id=: vp.Id ];

        System.assertEquals( 'Business Unit A', vpList[0].Business_Unit__c );
    }

    testmethod static void testMassSignUp(){
        
        // Setup the test
        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity( vo, 5 );

        User newUser = TestCommon.setupUser();
        List<Id> massSignupUserIds = new List<Id>();
        massSignupUserIds.add( newUser.Id );
 
        // Test
        ApexPages.Message result = VolActivity.signUpBatch( newAct.Id, massSignupUserIds );

        if( result == null ){
            return;
        }

        System.assertEquals( ApexPages.Severity.INFO, result.getSeverity() );

        return;
    }

    testmethod static void testSendAllEmailOnUpdate(){
        
        User newUser = TestCommon.setupUser();

        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        Volunteer_Activity__c newAct = TestCommon.setupActivity( vo, 5 );

        Volunteer_Activity_Participant__c vp = new Volunteer_Activity_Participant__c( User__c = newUser.Id, Volunteer_Activity__c = newAct.Id );
        insert vp;

        Double duration = newAct.Duration_hours__c;
        newAct.Duration_hours__c += 1;

        update newAct;

        Volunteer_Activity__c[] updateAct = [ select Duration_hours__c 
                                                from Volunteer_Activity__c
                                                where Id=: newAct.Id ];
                                             
        System.assertEquals( duration + 1, updateAct[0].Duration_hours__c );
    }
    
    testmethod static void testUpdateTimeDate(){
        
        // Setup the test
        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
               
        Volunteer_Activity__c newAct = new  Volunteer_Activity__c(
                                                City__c='TestCity', 
                                                Country__c='TestCountry',
                                                Description__c='TestDescription',
                                                Name='Test Activity',
                                                State_Province__c='TS',
                                                Street__c='Test Street',
                                                Zip_Postal_Code__c='100101',
                                                Max_Number_of_Participants__c=5,
                                                Volunteer_Organization__c=vo.Id,
                                                Date_and_Time__c=DateTime.Now(),
                                                Duration_hours__c=2
                                                );
        insert newAct;
        
        // Test
        string strDateTime = '2010-10-12 10:10:10';        
        
        DateTime dt = datetime.valueOf( strDateTime );
        VolActivity.updateTimeDate( newAct.Id, strDateTime );    
        newAct = [ select id, Date_and_Time__c 
                    from Volunteer_Activity__c 
                    where id =: newAct.Id ];

        System.assert( newAct.Date_and_Time__c == dt );
    } 
    
    testmethod static void test(){
    
        VolActivity.CurrentUserHasCreatePermission = null;
        Boolean aux = VolActivity.CurrentUserHasCreatePermission;
        System.assert( aux );
        
        VolActivity.KeyPrefix = null;
        String aux2 = VolActivity.KeyPrefix;
    }
}