force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Unit A</fullName>
            </value>
            <value>
                <fullName>Business Unit B</fullName>
            </value>
            <value>
                <fullName>Business Unit C</fullName>
            </value>
            <value>
                <fullName>Business Unit D</fullName>
            </value>
            <value>
                <fullName>Business Unit E</fullName>
            </value>
            <value>
                <fullName>Business Unit F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Employee Success</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Technical Support</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US-East</fullName>
            </value>
            <value>
                <fullName>US-Central</fullName>
            </value>
            <value>
                <fullName>US-West</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AsiaPac</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>The region the activitiy is taking place</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Americas - East</fullName>
            </value>
            <value>
                <fullName>Americas - West</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/Volunteer_Activity_Participant__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpParticipant</customHelpPage>
    <description>A junction object used for linking Volunteer Activities to a participant in the activity and to the participant&#39;s role hierarchy at the time of the activity</description>
    <label>Volunteer Participant</label>
    <nameField>
        <displayFormat>Participant ID: {000000}</displayFormat>
        <label>Volunteer Activity Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>This field is used only for reporting and is hidden from the end user.  It is maintained by apex code by copying the values from the user record when participant is added and when the User record changes.</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Unit A</fullName>
            </value>
            <value>
                <fullName>Business Unit B</fullName>
            </value>
            <value>
                <fullName>Business Unit C</fullName>
            </value>
            <value>
                <fullName>Business Unit D</fullName>
            </value>
            <value>
                <fullName>Business Unit E</fullName>
            </value>
            <value>
                <fullName>Business Unit F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>This field is used only for reporting and is hidden from the end user.  It is maintained by apex code by copying the values from the user record when participant is added and when the User record changes.</description>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Technical Support</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Employee Success</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is used only for reporting and is hidden from the end user.  It is maintained by apex code by copying the values from the user record when participant is added and when the User record changes.</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>US-Central</fullName>
            </value>
            <value>
                <fullName>US-West</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>US-East</fullName>
            </value>
            <value>
                <fullName>AsiaPac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N30000002ECnbEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Volunteer_Activity__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Activity__c</fullName>
    <label>Volunteer Activity</label>
    <referenceTo>Volunteer_Activity__c</referenceTo>
    <relationshipName>R00N30000002ECnNEAW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VolActivityParticipant.cls
/**
* Apex code for the Volunteer Activity Participant custom object.
*/
public class VolActivityParticipant{
    
    /**
    * For the set user reference id, this function sets the VAP's reporting fields
    * based on the current User record values.  These fields include:
    * 1) Department
    * 2) Region
    * 3) Business Unit
    * @param activityParticipants
    */ 
    public static void updateUserReportingFields( List<Volunteer_Activity_Participant__c> activityParticipants ){
    	      
        Map<Id, User> usersId = new Map<Id, User>();
        for( User usr : [ select Id, Business_Unit__c, Department__c, Region__c from User limit 1000 ] ){
        	usersId.put( usr.Id, usr );
        } 
        
       	for( Volunteer_Activity_Participant__c vap : activityParticipants ){
       		
       		if( usersId.get( vap.User__c ) == null ){
       			vap.addError( 'Error setting activity reporting fields.' );
	        }
	         
	        User user = usersId.get( vap.User__c );
	
	        vap.Business_Unit__c 	= user.Business_Unit__c;
	        vap.Department__c 		= user.Department__c;
	        vap.Region__c 			= user.Region__c;
	        
       	}
    }   

    /**
    * Get the volunteer activity participant record.
    * @param vaId
    * @param userId
    * @return Volunteer_Activity_Participant__c
    */ 
    public static Volunteer_Activity_Participant__c getRecordForUser( Id vaId, Id userId ){
    	
        Volunteer_Activity_Participant__c[] vaps = [ select Id,User__c,Volunteer_Activity__c 
                                                    	from Volunteer_Activity_Participant__c 
                                                    	where User__c = :userId and Volunteer_Activity__c =: vaId ];
                                    
        if( vaps.size() == 0 ){
            return null;
        }
        
        return vaps[0];             
    }
}