force-app/main/default/objects/Card_Spend__c/Card_Spend__c.object-meta.xml
<CustomObject>
    <description>Utilized to house card spend data for Commercial card customers</description>
    <label>Card Spend</label>
    <nameField>
        <displayFormat>CS{0000000000}</displayFormat>
        <label>Card Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Spend__c/fields/Active_Cards__c.field-meta.xml
<CustomField>
    <fullName>Active_Cards__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Active Cards</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Company_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Company_Credit_Limit__c</fullName>
    <label>Company_Credit_Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Live_Account_Count__c.field-meta.xml
<CustomField>
    <fullName>Live_Account_Count__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Live Account Count</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Managed_Flag__c.field-meta.xml
<CustomField>
    <fullName>Managed_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Managed Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Month_End__c.field-meta.xml
<CustomField>
    <fullName>Month_End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month_End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Month_Spend__c.field-meta.xml
<CustomField>
    <fullName>Month_Spend__c</fullName>
    <label>Month_Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Multiple_Product_Flag__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Product_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Multiple Product Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Card Spends</relationshipLabel>
    <relationshipName>Card_Spends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Partnering_Bank__c.field-meta.xml
<CustomField>
    <fullName>Partnering_Bank__c</fullName>
    <description>SuperBank from the TBS system interface file for Card Spend</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Partnering Bank</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Spend__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Card Product Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partnering_Bank__c/Partnering_Bank__c.object-meta.xml
<CustomObject>
    <description>Used to house data on our partnering agent banks (a lookup relationship from the Card Product object)</description>
    <label>Partnering Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partnering Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnering Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/cardSpendChartStatController.cls
// Author: Alexander Nourbakhsh
// Date: 05.25.2016
// Project: Card Spend
// Purpose: This controller returns information about the most recent Card_Spend__c record by date,
// and calculates YTD and PYTD spend data. This controller is a companion to the cardSpendMonthChartController. 
//
//

public class cardSpendChartStatController {

    public Card_Spend__c calcRecord;
    public Decimal ytdSpendSum = 0;
    public Decimal pytdSpendSum = 0;
    public Decimal ytdAvgPerUtil = 0;
    public Decimal pytdAvgPerUtil = 0;
    Boolean renderPage = True;
    
    public cardSpendChartStatController(ApexPages.StandardController stdController) {
    }
       
    public cardSpendChartStatController() {
    
                    
        Decimal ytdCreditLimitSum = 0;
        Decimal pytdCreditLimitSum = 0;
        Decimal ytdAvgPerUtilRound = 0;
        Decimal pytdAvgPerUtilRound = 0;
        Set<Integer> ytdMonths = new Set<integer>();
        Date calcDate = date.today().addMonths(-1);
        

        try{
        
            calcRecord = [SELECT Id, Month_End__c, Company_ID__c, Company_Name__c, Partnering_Bank__c, Product_Code__c, Multiple_Product_Flag__c, Managed_Flag__c, Live_Account_Count__c, Active_Cards__c, Company_Credit_limit__c
                          FROM Card_Spend__c
                          WHERE Parent_Account__c = :ApexPages.currentPage().getParameters().get('id')
                          ORDER BY Month_End__c 
                          DESC 
                          LIMIT 1];
                                 
    
            
            for(Card_Spend__c cspend : [SELECT Id, Month_End__c, Month_Spend__c, Company_Credit_Limit__c
                                        FROM Card_Spend__c
                                        WHERE Parent_Account__c = :ApexPages.currentPage().getParameters().get('id')
                                        ORDER BY Month_End__c
                                        DESC
                                        LIMIT 24]) {
                                        
                                                   
                                        
                if(cspend.Month_End__c.Year() == calcDate.Year()) {
                    
                   ytdMonths.add(cspend.Month_End__c.Month());
                   ytdSpendSum += cspend.Month_Spend__c;
                   ytdCreditLimitSum += cspend.Company_Credit_Limit__c;
                   
                } else if (ytdMonths.contains(cspend.Month_End__c.Month())){
                   pytdSpendSum += cspend.Month_Spend__c;
                   pytdCreditLimitSum += cspend.Company_Credit_Limit__c;
                   
                } else {
                
                }
                        
            }
            
            if(ytdCreditLimitSum > 0){
            ytdAvgPerUtilRound = (ytdSpendSum/ytdCreditLimitSum)*100;
            } else {
            //do nothing
            }
    
    
            if(pytdCreditLimitSum > 0){
            pytdAvgPerUtilRound = (pytdSpendSum/pytdCreditLimitSum)*100;
            
            } else {
            //do nothing
            }
    
            pytdAvgPerUtil = pytdAvgPerUtilRound.setScale(2);
            ytdAvgPerUtil = ytdAvgPerUtilRound.setScale(2);
 
           
        } Catch (Exception e) {
            renderPage = False;
        }
    
    }

    public Card_Spend__c getCalcRecord() {
        return calcRecord;

    }
    
    public Boolean getRenderPage() {
        return renderPage;
    }
    
    public Date getLastMonthEndDate() {
        return calcRecord.Month_End__c;
    }
    
    public String getCompanyID() {
        return calcRecord.Company_ID__c;
    }
    
    public Decimal getCompanyCreditLimit() {
        return calcRecord.Company_Credit_Limit__c;
    }
    
    public String getTBSCompanyName() {
        return calcRecord.Company_Name__c;
    }
    
    public String getTBSPartneringBank() {
        return calcRecord.Partnering_Bank__c;
    }
    
    public String getProductCode() {
        return calcRecord.Product_Code__c;
    }
    
    public String getMultipleProductFlag() {
        return calcRecord.Multiple_Product_Flag__c;
    }
    
    public String getManagedFlag() {
        return calcRecord.Managed_Flag__c;
    }
    
    public String getLiveAccountCount() {
        return calcRecord.Live_Account_Count__c;
    }
    
    public String getActiveCards() {
        return calcRecord.Active_Cards__c;
    }
    
    public Decimal getYtdSpendSum() {
        return ytdSpendSum;
    }
    
    public Decimal getPytdSpendSum() {
        return pytdSpendSum;
    }
    
    public Decimal getYtdAvgPerUtil() {
        return ytdAvgPerUtil;
    }
    
    public Decimal getPytdAvgPerUtil() {
        return pytdAvgPerUtil;
    }
    
}