force-app/main/default/objects/Prospect_Profile__c/Prospect_Profile__c.object-meta.xml
<CustomObject>
    <description>Prospect Profile</description>
    <label>Prospect Profile</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospect Profiles</relationshipLabel>
    <relationshipName>Prospect_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Profile__c/fields/Accounting_Firm__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Firm__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Accounting Firm</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Profile__c/fields/Legal_Firm__c.field-meta.xml
<CustomField>
    <fullName>Legal_Firm__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Firm</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProspectProfileExtension.cls
public class ProspectProfileExtension {
public Prospect_Profile__c Prospect_Profile {get;set;}

public ProspectProfileExtension(ApexPages.standardController stdController){
    Prospect_Profile = (Prospect_Profile__c)stdController.getRecord();
    Prospect_Profile.Account__c = ApexPages.currentPage().getParameters().get('Account__c');
    Prospect_Profile.Name = ApexPages.currentPage().getParameters().get('Name');
    Prospect_Profile.Accounting_Firm__c = ApexPages.currentPage().getParameters().get('Accounting_Firm__c');
    Prospect_Profile.Legal_Firm__c = ApexPages.currentPage().getParameters().get('Legal_Firm__c');
}}