force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/IsOpportunity__c.field-meta.xml
<CustomField>
    <fullName>IsOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A volunteer activity which is not associated with a specific date or time (e.g., Big Brother/Big Sister mentoring).</inlineHelpText>
    <label>Ongoing Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <formula>Volunteer_Organization__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama (AL)</fullName>
            </value>
            <value>
                <fullName>Alaska (AK)</fullName>
            </value>
            <value>
                <fullName>Alberta (AB)</fullName>
            </value>
            <value>
                <fullName>Arizona (AZ)</fullName>
            </value>
            <value>
                <fullName>Arkansas (AR)</fullName>
            </value>
            <value>
                <fullName>British Columbia (BC)</fullName>
            </value>
            <value>
                <fullName>California (CA)</fullName>
            </value>
            <value>
                <fullName>Colorado (CO)</fullName>
            </value>
            <value>
                <fullName>Connecticut (CT)</fullName>
            </value>
            <value>
                <fullName>Delaware (DE)</fullName>
            </value>
            <value>
                <fullName>District of Columbia (DC)</fullName>
            </value>
            <value>
                <fullName>Florida (FL)</fullName>
            </value>
            <value>
                <fullName>Georgia (GA)</fullName>
            </value>
            <value>
                <fullName>Hawaii (HI)</fullName>
            </value>
            <value>
                <fullName>Idaho (ID)</fullName>
            </value>
            <value>
                <fullName>Illinois (IL)</fullName>
            </value>
            <value>
                <fullName>Indiana (IN)</fullName>
            </value>
            <value>
                <fullName>Iowa (IA)</fullName>
            </value>
            <value>
                <fullName>Kansas (KS)</fullName>
            </value>
            <value>
                <fullName>Kentucky (KY)</fullName>
            </value>
            <value>
                <fullName>Louisiana (LA)</fullName>
            </value>
            <value>
                <fullName>Maine (ME)</fullName>
            </value>
            <value>
                <fullName>Manitoba (MB)</fullName>
            </value>
            <value>
                <fullName>Maryland (MD)</fullName>
            </value>
            <value>
                <fullName>Massachusetts (MA)</fullName>
            </value>
            <value>
                <fullName>Michigan (MI)</fullName>
            </value>
            <value>
                <fullName>Minnesota (MN)</fullName>
            </value>
            <value>
                <fullName>Mississippi (MS)</fullName>
            </value>
            <value>
                <fullName>Missouri (MO)</fullName>
            </value>
            <value>
                <fullName>Montana (MT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of volunteers who have been assigned to nonprofit customers. When integrated with the hub, volunteers will need to know if an activity is still available for volunteer sign up or if it&#39;s full and closed</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Events__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Events__c</fullName>
    <label>Activity Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beautification/Cleaning/Painting/Gardening</fullName>
            </value>
            <value>
                <fullName>Business Assistance</fullName>
            </value>
            <value>
                <fullName>CRA Community Contact</fullName>
            </value>
            <value>
                <fullName>CRA Community Outreach</fullName>
            </value>
            <value>
                <fullName>Education/Training/Tutoring</fullName>
            </value>
            <value>
                <fullName>Faith-based</fullName>
            </value>
            <value>
                <fullName>Fundraising/Event Management</fullName>
            </value>
            <value>
                <fullName>Mentoring/leadership development</fullName>
            </value>
            <value>
                <fullName>Professional Skills</fullName>
            </value>
            <value>
                <fullName>Walks/Runs/Parades/Booth/Table</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Building/Construction/Rehabilitation/Home Maintenance</fullName>
            </value>
            <value>
                <fullName>Community Event Participation</fullName>
            </value>
            <value>
                <fullName>Food serving/distributing/sorting/delivering</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Health Care and Social Services</fullName>
            </value>
            <value>
                <fullName>Disaster/Emergency Services</fullName>
            </value>
            <value>
                <fullName>Civic Participation/Political</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SearchConfig.cls
/**
* Used for the search feature.
*/
public class SearchConfig{
	
    private static final Schema.SObjectType TARGET_OBJECT = volunteer_activity__c.sobjectType;
    private static final List<Schema.SObjectField> SEARCH_FIELDS = new Schema.SObjectField[] {
                                volunteer_activity__c.organization_name__c,
                                volunteer_activity__c.name,
                                volunteer_activity__c.city__c,
                                volunteer_activity__c.state_province__c,
                                volunteer_activity__c.isOpportunity__c};
                                
    private static final List<Schema.SObjectField> FILTERS = new Schema.SObjectField[] {
                                volunteer_activity__c.volunteer_events__c};
                                
    private static final List<Schema.SObjectField> COL_DEFAULTS = new Schema.SObjectField[] {
                                volunteer_activity__c.name,
                                volunteer_activity__c.organization_name__c,
                                volunteer_activity__c.volunteer_events__c,
                                volunteer_activity__c.city__c,
                                volunteer_activity__c.date_and_time__c};
                                
    private static final Map<String, String> DEFAULT_SEARCH_CLAUSES = new Map<String, String>{
                                volunteer_activity__c.date_and_time__c.getDescribe().getName() 
                                => 'date_and_time__c > YESTERDAY',
                                volunteer_activity__c.status__c.getDescribe().getName() 
                                => 'status__c NOT IN (\'Cancelled\',\'Completed\')' };
                                
	private static final Map<String, String> ACTIVITY_SEARCH_CLAUSES = new Map<String, String>{
                                volunteer_activity__c.status__c.getDescribe().getName() 
                                => 'status__c NOT IN (\'Cancelled\',\'Completed\')' };                                
    
    private static final Integer RESULTSET_SIZE_LIMIT = 50;
    private static final String EVENT_SORT_COLUMN = 'date_and_time__c';
    private static final String ACTIVITY_SORT_COLUMN = 'name';
    
    private static final List<String> SEARCH_FIELD_NAMES = new List<String>();
    private static final List<String> FILTER_NAMES = new List<String>();
    private static final List<String> COL_DEFAULT_NAMES = new List<String>();
    static {
        for(Schema.SObjectField field: SEARCH_FIELDS) {
            SEARCH_FIELD_NAMES.add(field.getDescribe().getName());
        }
        for(Schema.SObjectField field: FILTERS) {
            FILTER_NAMES.add(field.getDescribe().getName());
        }
        for(Schema.SObjectField field: COL_DEFAULTS) {
            COL_DEFAULT_NAMES.add(field.getDescribe().getName());
        }
    }
    
    /**
    * Getter method for Search fields
    * @return SEARCH_FIELD_NAMES
    */
    public static List<String> getSearchFields(){
        return SEARCH_FIELD_NAMES;
    }
    
    /**
    * Getter method for Filter fields
    * @return FILTER_NAMES
    */    
    public static List<String> getFilterFields(){
        return FILTER_NAMES;
    }
    
    /**
    * Getter method for Result columns
    * @return COL_DEFAULT_NAMES
    */
    public static List<String> getResultColumns(){
        return COL_DEFAULT_NAMES;
    }
    
    /**
    * Getter method for target Object
    * @return TARGET_OBJECT
    */
    public static Schema.SObjectType getTargetObject(){
        return TARGET_OBJECT;
    }
    
    /**
    * Getter method for default where clauses
    * @return DEFAULT_SEARCH_CLAUSES
    */
    public static Map<String, String> getDefaultWhereClauses(){
        return DEFAULT_SEARCH_CLAUSES;
    }
    
    /**
    * Getter method for size Limit
    * @return RESULTSET_SIZE_LIMIT
    */
    public static Integer getSizeLimit(){
        return RESULTSET_SIZE_LIMIT;
    }
    
    /**
    * Getter method for event sort column
    * @return EVENT_SORT_COLUMN
    */
    public static String getEventSortColumn(){
        return EVENT_SORT_COLUMN;
    }
    
    /**
    * Getter method for activity sort column
    * @return ACTIVITY_SORT_COLUMN
    */
    public static String getActivitySortColumn(){
    	return ACTIVITY_SORT_COLUMN;
    }
    
    /**
    * Getter method for activity where clause
    * @return ACTIVITY_SEARCH_CLAUSES
    */
    public static Map<String, String> getActivityWhereClauses(){
        return ACTIVITY_SEARCH_CLAUSES;
    }
}