force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <label>Duration (hours)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/IsOpportunity__c.field-meta.xml
<CustomField>
    <fullName>IsOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A volunteer activity which is not associated with a specific date or time (e.g., Big Brother/Big Sister mentoring).</inlineHelpText>
    <label>Ongoing Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Max_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Participants__c</fullName>
    <inlineHelpText>Blocks users from signing up if the activity is already full.</inlineHelpText>
    <label>Maximum Participants</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Organization__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestVolActivityMassSignUpControllerExt.cls
// Apex test methods for the VolActivityMassSignUpControllerExt class.
@isTest
private class TestVolActivityMassSignUpControllerExt{
	    
    private VolActivityMassSignUpControllerExt setupController( Volunteer_Activity__c va ){
    
        // Construct the controller that will be returned by this setup method.
        ApexPages.StandardController standardcontroller = new ApexPages.StandardController( va ) ;
        VolActivityMassSignUpControllerExt controller 	= new VolActivityMassSignUpControllerExt( standardcontroller );
     
        // Create a page for use in the test.
        PageReference p = Page.VolActivityMassSignUpPage;
        
        // Set the case ID in the context for use by the controller.
        p.getParameters().put( 'id', va.id );
        
        // Set the case ID in the context for use by the controller.
        Test.setCurrentPage( p );
        
        System.assert( controller != null );
        return controller;
    }
    
    private Volunteer_Activity__c setupTestCaseVA(){
    	
        datetime myDateTime = datetime.now();
        
        Volunteer_Activity__c va1 = new Volunteer_Activity__c(Street__c='a1',City__c='b2',
                Date_and_Time__c=myDateTime,IsOpportunity__c=false,duration_hours__c=1.0,
                Max_Number_of_Participants__c=1);
        try{
        	insert va1;
        	System.assert( true );
        }catch( Exception ex ){
        	System.assert( false );
        }
                
        return va1;
    }
        
    public static testMethod void massSignUpTest(){
    	
        TestVolActivityMassSignUpControllerExt testclass = new TestVolActivityMassSignUpControllerExt();
        
        Volunteer_Activity__c va = testclass.setupTestCaseVA();
        Volunteer_Organization__c vo = TestCommon.setupVolunteerOrganization();
        
        VolActivityMassSignUpControllerExt cont = new VolActivityMassSignUpControllerExt( new ApexPages.Standardcontroller( TestCommon.setupActivity( vo, 2 ) ));
        cont.getRenderMaxParticipants();
        cont.massSignUp();
        
        VolActivityMassSignUpControllerExt controller = testclass.setupController( va );
        
        controller.getUserList( va.id, 0 );
        
        controller.init();
        controller.nextPage();
        controller.prevPage();
        controller.getRenderNext();
        controller.getRenderPrev();
        
        String[] selectedUsers = new String[1];
        selectedUsers[0] = TestCommon.setupUser().id;
        
        controller.setSelUsers( selectedUsers );
        System.assertEquals( controller.getSelUsers().size(), 1 );
        
        controller.getCount();
        controller.fname = 'm';        
        controller.search();
        controller.getUserList( va.id, 5 );
        controller.getRenderNext();
        controller.getRenderPrev();
        
        controller.lname = 'm';
        controller.search();
        controller.getUserList( va.id, 0 );
        controller.getItems();

        controller.fname = 'g';
        controller.lname = 'r';
        controller.search();
        controller.getUserList( va.id, 0 ); 
        controller.getItems();

        controller.fname = 'g';
        controller.lname = 'r';
        controller.dept = 'e';
        controller.search();
        controller.getUserList( va.id, 0 );
        controller.getItems();
        
        controller.nextPage();
        controller.prevPage();
        controller.getRenderNext();
        controller.getRenderPrev();
        
        Test.startTest();
        Test.stopTest();     
    }
}