force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the activity occurs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <label>Duration (hours)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/IsOpportunity__c.field-meta.xml
<CustomField>
    <fullName>IsOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A volunteer activity which is not associated with a specific date or time (e.g., Big Brother/Big Sister mentoring).</inlineHelpText>
    <label>Ongoing Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/Volunteer_Activity_Participant__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpParticipant</customHelpPage>
    <description>A junction object used for linking Volunteer Activities to a participant in the activity and to the participant&#39;s role hierarchy at the time of the activity</description>
    <label>Volunteer Participant</label>
    <nameField>
        <displayFormat>Participant ID: {000000}</displayFormat>
        <label>Volunteer Activity Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_hours__c</fullName>
    <description>If left blank, this field is updated programmatically when new volunteer activity participants are created.</description>
    <inlineHelpText>If left blank, this field is updated based on the Activity duration.</inlineHelpText>
    <label>Participation (hours)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N30000002ECnbEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Activity_Participant__c/fields/Volunteer_Activity__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Activity__c</fullName>
    <label>Volunteer Activity</label>
    <referenceTo>Volunteer_Activity__c</referenceTo>
    <relationshipName>R00N30000002ECnNEAW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestVolActivitySignMeUpControllerExt.cls
// Apex test methods for the VolActivitySignMeUpControllerExt class.
@isTest
private with sharing class TestVolActivitySignMeUpControllerExt{
	
    public static testMethod void sigmeupTest(){
    	
        TestVolActivitySignMeUpControllerExt testclass = new TestVolActivitySignMeUpControllerExt();
        
        datetime myDateTime = datetime.now(); 
        
        Volunteer_Activity__c va = new Volunteer_Activity__c( Street__c='a1',City__c='b2',Duration_Hours__c=1.0,Date_and_Time__c=myDateTime,IsOpportunity__c=false);
        insert( va );
        
        Volunteer_Activity_Participant__c p1 = new Volunteer_Activity_Participant__c( Volunteer_Activity__c = va.Id, User__c = TestCommon.setupUser().id, Duration_hours__c = 1.0 );
        
        // Construct the controller that will be returned by this setup method.
        ApexPages.StandardController standardcontroller = new ApexPages.StandardController( va ) ;
        VolActivitySignMeUpControllerExt controller 	= new VolActivitySignMeUpControllerExt( standardcontroller );
    
        // Create a page for use in the test.
        PageReference p = Page.VolActivitySignMeUpConfirmation;
        
        // Set the case ID in the context for use by the controller.
        p.getParameters().put( 'id', va.id );
        
        // Set the case ID in the context for use by the controller.
        Test.setCurrentPage( p );
        
        System.assertEquals( null, controller.signUp() );
        
    }
}