force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestEmailManager.cls
@isTest
private class TestEmailManager{

    public testmethod static void testSendMessage(){
        
        User user = TestCommon.setupUser();
        
        string address          = 'One Landmark';
        string address2         = 'One Landmark2';
        string personal         = 'Volunteerforce';
        
        Volunteer_Activity__c va        = new Volunteer_Activity__c();
        Volunteer_Organization__c vo    = new Volunteer_Organization__c();
        
        List<InternetAddress> recipients = new List<InternetAddress>();
        
        InternetAddress organizer   = new InternetAddress( address, user.Id );
        InternetAddress viaFrom     = new InternetAddress( address2, user.Id );
        InternetAddress recipient   = new InternetAddress( personal, user.Id );
        
        recipients.add( viaFrom );
        recipients.add( recipient );
        
        Boolean result = EmailManager.sendMessageToParticipantsBatch( vo, va, organizer, recipients, EmailManager.MessageType.mtREMINDER );
        System.assert( !result );
    }
    
    public testmethod static void testSendMassMail(){
        
        User user = TestCommon.setupUser();
        
        string address          = 'One Landmark';
        string address2         = 'One Landmark2';
        string personal         = 'Volunteerforce';
        
        Volunteer_Activity__c va = TestCommon.setupActivity( TestCommon.setupVolunteerOrganization(), 2 );
        
        List<Id> recipients         = new List<Id>();
        InternetAddress organizer   = new InternetAddress( address, user.Id );
        InternetAddress viaFrom     = new InternetAddress( address2, user.Id );
        InternetAddress recipient   = new InternetAddress( personal, user.Id );
        
        recipients.add( user.id );
        recipients.add( user.id );
        recipients.add( user.id );
        
        EmailTemplate[] ets = [ Select Id, IsActive, Name, OwnerId, Subject
                                    from EmailTemplate 
                                    where Name = 'Participant event removed participant' and IsActive = true ];
                                    

    }
}