force-app/main/default/objects/Volunteer_Activity__c/Volunteer_Activity__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpActivity</customHelpPage>
    <description>Keeps track of volunteer activities and allows employees to sign up to participate in volunteer activities.</description>
    <label>Volunteer Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Activity__c/fields/Volunteer_Organization__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Organization</label>
    <referenceTo>Volunteer_Organization__c</referenceTo>
    <relationshipName>Volunteering</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Organization__c/Volunteer_Organization__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpOrganization</customHelpPage>
    <description>Manages information about Organizations that sponsor Volunteer Activities.</description>
    <label>Non Profit Organization</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Profit Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VolOrganization.cls
/**
* Utility class for Volunteer Organizations
* @author Matias Menafra
* @createddate 24/06/2010
*/
public with sharing class VolOrganization{

	/**
	* Constructor
	*/
	public VolOrganization(){
	
	}
	
	/**
	* Bulk method which verifies deletion on Volunteer Organizations
	* @param volOrganizations
	*/
	public static void deleteCheckVolunterrOrganization( List<Volunteer_Organization__c> volOrganizations ){
	
		List<Id> organizationIds = new List<Id>();
		for( Volunteer_Organization__c org : volOrganizations ){
			organizationIds.add( org.Id );
		}
		
		List<Volunteer_Activity__c> activityList = [ select Id from Volunteer_Activity__c where Volunteer_Organization__c IN : organizationIds  ];
		
		if( activityList.size() > 0 ){
			volOrganizations.get( 0 ).addError( 'Cannot delete Organizations which have Activities associated with the Organization.' );
		}
	}
}