force-app/main/default/objects/POSI__c/POSI__c.object-meta.xml
<CustomObject>
    <description>Allows a user to capture information on a prospect or existing customer that details their profile, objectives, strategies, and issues (POSI grid) - Aligns with the banks strategy on IMPAX sales techniques</description>
    <label>Corporate Profile Grid</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>POSI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate Profile Grids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POSI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>POSI</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TriggerSupport__c/TriggerSupport__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manage running FNBO custom triggers</description>
    <label>Trigger Support</label>
</CustomObject>

force-app/main/default/objects/TriggerSupport__c/fields/TriggerIsDisabled__c.field-meta.xml
<CustomField>
    <fullName>TriggerIsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When &quot;check&quot;, trigger code will be bypassed 
When &quot;unchecked&quot;, trigger code will be executed</description>
    <label>TriggerIsDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/POSIRelatedList_Controller_Test.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 02/01/2017
// Project: POSI Grid

@isTest
public class POSIRelatedList_Controller_Test {
    
    static testMethod void POSIRelatedList_Controller_Test() {
       
        //08/08/2019 Added as part of test class fix -begin
 
	     List<TriggerSupport__c> triggerSupportList = new List<TriggerSupport__c>();
         TriggerSupport__c accountTriggerSupportSetting = new TriggerSupport__c();
         accountTriggerSupportSetting.Name = 'Account';
         accountTriggerSupportSetting.TriggerIsDisabled__c = true;
         triggerSupportList.add(accountTriggerSupportSetting);
         insert triggerSupportList;
         Account acct = new Account(name = 'posiTestAccount', recordTypeId = '01230000000sSMd');
        
        insert acct;
        
        POSI__c posiTest = new POSI__C(Account__c = acct.Id);
        insert posiTest;
        
        ApexPages.currentPage().getParameters().put('id',acct.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        POSIRelatedList_Controller ce = new POSIRelatedList_Controller(sc);
        
        test.startTest();
        
        List<POSI__c> posiRecords = ce.getPOSI();
        Boolean posiRender = ce.getRenderPage();
        
        System.assertNotEquals(null, posiRecords);
        System.assertNotEquals(null, posiRender);
        
        test.stopTest();
        
    }
}