force-app/main/default/objects/POSI__c/POSI__c.object-meta.xml
<CustomObject>
    <description>Allows a user to capture information on a prospect or existing customer that details their profile, objectives, strategies, and issues (POSI grid) - Aligns with the banks strategy on IMPAX sales techniques</description>
    <label>Corporate Profile Grid</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>POSI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate Profile Grids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POSI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>POSI</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/POSIRelatedList_Controller.cls
// Author: Alexander Nourbakhsh
// Date Created/Modified: 01.31.2017
// Project: POSI Grid
// Purpose: 
//

public class POSIRelatedList_Controller {

    private list<POSI__c> POSI = new List<POSI__c>();
    private boolean renderPage = True;
    
    public POSIRelatedList_Controller(ApexPages.StandardController controller) {
        
                try{
            // SOQL statements to build sObject lists                      
            POSI = [SELECT Id, Name, Account__c, Account__r.Name, CreatedById, CreatedDate
                    FROM POSI__c 
                    WHERE Account__c = :ApexPages.currentPage().getParameters().get('id')
                    LIMIT 50000];        
      
                } catch (exception e) {
            
           renderPage = false;
                }      
    }
    
        public list<POSI__C> getPOSI() {
                return POSI;
    }    
    public boolean getRenderPage() {
        return renderPage;
    } 
}