force-app/main/default/objects/FIC_Survey_Application__c/FIC_Survey_Application__c.object-meta.xml
<CustomObject>
    <description>Stores data received from Grant and Donation applications submitted by non profit organizations in our communitieis</description>
    <label>FIC Survey Application</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>FIC Survey Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIC Survey Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Executive_Director__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Executive Director</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Executive_Director_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Executive Director Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Executive_Director_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director_Phone_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Executive Director Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/First_National_Bank_Employee_on_Board__c.field-meta.xml
<CustomField>
    <fullName>First_National_Bank_Employee_on_Board__c</fullName>
    <label>First National Bank Employee on Board</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/First_National_Bank_Request__c.field-meta.xml
<CustomField>
    <fullName>First_National_Bank_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreed to Terms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Name_of_Organization_W_9__c.field-meta.xml
<CustomField>
    <fullName>G_Name_of_Organization_W_9__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of Organization W-9</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Corporate_Cont_Grants_Fees__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Corporate_Cont_Grants_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Corporate Cont/Grants/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Earned_Revenue__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Earned_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Earned Revenue</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Foundation_Cont_Grants_Fees__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Foundation_Cont_Grants_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Foundation Cont/Grants/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Government_Contracts_Grants__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Government_Contracts_Grants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Government Contracts/Grants</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Individual_contributions_grants__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Individual_contributions_grants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Individual Contributions/Grants</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Investment_Interest_Tax_Rev__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Investment_Interest_Tax_Rev__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Investment Interest/Tax Rev</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Membership_Dues_Fees__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Membership_Dues_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Membership Dues/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_Other__c.field-meta.xml
<CustomField>
    <fullName>G_Org_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org Other</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Org_United_Way__c.field-meta.xml
<CustomField>
    <fullName>G_Org_United_Way__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Org United Way</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Corporate_Cont_Grants_Fees__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Corporate_Cont_Grants_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Corporate Cont/Grants/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Earned_Revenue__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Earned_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Earned Revenue</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Foundation_Cont_Grants_Fees__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Foundation_Cont_Grants_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Foundation Cont/Grants/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Government_Contracts_Grants__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Government_Contracts_Grants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Government Contracts/Grants</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Individual_Contributions_Grant__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Individual_Contributions_Grant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Individual Contributions/Grants</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Investment_Interest_Tax_Rev__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Investment_Interest_Tax_Rev__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Investment Interest/Tax Rev</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Membership_dues_fees__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Membership_dues_fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Membership Dues/Fees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_Other__c.field-meta.xml
<CustomField>
    <fullName>G_Program_Other__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program Other</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/G_Program_United_Way__c.field-meta.xml
<CustomField>
    <fullName>G_Program_United_Way__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Program United Way</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Grant_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Contact_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grant Contact Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Mission_Statement__c.field-meta.xml
<CustomField>
    <fullName>Mission_Statement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission Statement</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Name_of_Organization__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Organization__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of Organization</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Status__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Status__c</fullName>
    <label>Non-Profit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>501C(3)</fullName>
            </value>
            <value>
                <fullName>501C(6)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Non_Profit_Status_Other__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Status_Other__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Non-Profit Status Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_City__c.field-meta.xml
<CustomField>
    <fullName>Organization_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_Have_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Organization_Have_Relationship__c</fullName>
    <label>Organization Have Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_State__c.field-meta.xml
<CustomField>
    <fullName>Organization_State__c</fullName>
    <label>Organization State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Organization_Street_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Organization_Zip__c.field-meta.xml
<CustomField>
    <fullName>Organization_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization Zip</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Tax ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIC_Survey_Application__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/grantApplicationFormController_Test.cls
@isTest
public class grantApplicationFormController_Test {
    @isTest
    static void grantApplicationFormController_Test() {
        
        FIC_Survey_Application__c grant = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant = new ApexPages.standardController(grant);
        grantApplicationForm_Controller ce_grant = new grantApplicationForm_Controller(sc_grant);
             
        grant.Tax_ID__c = '77-7777777';
        
        ce_grant.signin();

        grant.Tax_ID__c = '77-777777';
        
        ce_grant.signin();

        grant.Tax_ID__c = '77-777x777';
        
        ce_grant.signin();
        
        // pos
        // neg

        grant.Tax_ID__c = '11-1111111';
        grant.Non_Profit_Status__c = '501C(3)';

        ce_grant.gr13();

        grant.Tax_ID__c = '11-1111111';
        grant.Non_Profit_Status__c = 'Other';
        grant.Non_Profit_Status_Other__c = null;

        ce_grant.gr13();

        
        ce_grant.gr14();
        
        grant.First_National_Bank_Request__c = True;
        grant.First_National_Bank_Employee_on_Board__c = 'No';
        grant.Organization_Have_Relationship__c = 'No';
        
        ce_grant.gr14();
       
        
        ce_grant.gr15();
        
        // pos
        // neg
        
        ce_grant.gr16();
        ce_grant.purpose_choice='stablehousing';        
        ce_grant.gr16();
        ce_grant.purpose_choice='stronglocal';        
        ce_grant.gr16();
        ce_grant.purpose_choice='revitalize';        
        ce_grant.gr16();
        ce_grant.purpose_choice='educwrkfrce';        
        ce_grant.gr16();
        
        ce_grant.gr17();
        
        grant.G_Program_Government_Contracts_Grants__c = 0;
        grant.G_Program_Individual_Contributions_Grant__c = 0;
        grant.G_Program_Corporate_Cont_Grants_Fees__c = 0;
        grant.G_Program_Foundation_Cont_Grants_Fees__c = 0;
        grant.G_Program_Membership_dues_fees__c = 0;
        grant.G_Program_Investment_Interest_Tax_Rev__c = 0;
        grant.G_Program_Earned_Revenue__c = 0;
        grant.G_Program_United_Way__c = 0;
        grant.G_Program_Other__c = 0;
        
        grant.G_Org_Government_Contracts_Grants__c = 0;
        grant.G_Org_Individual_contributions_grants__c = 0;
        grant.G_Org_Corporate_Cont_Grants_Fees__c = 0;
        grant.G_Org_Foundation_Cont_Grants_Fees__c = 0;
        grant.G_Org_Membership_Dues_Fees__c = 0;
        grant.G_Org_Investment_Interest_Tax_Rev__c = 0;
        grant.G_Org_Earned_Revenue__c = 0;
        grant.G_Org_United_Way__c = 0;
        grant.G_Org_Other__c = 0;
        
        ce_grant.gr18();
        
        grant.G_Program_Government_Contracts_Grants__c = 0;
        grant.G_Program_Individual_Contributions_Grant__c = 0;
        grant.G_Program_Corporate_Cont_Grants_Fees__c = 20;
        grant.G_Program_Foundation_Cont_Grants_Fees__c = 30;
        grant.G_Program_Membership_dues_fees__c = 0;
        grant.G_Program_Investment_Interest_Tax_Rev__c = 0;
        grant.G_Program_Earned_Revenue__c = 20;
        grant.G_Program_United_Way__c = 30;
        grant.G_Program_Other__c = 0;
        
        grant.G_Org_Government_Contracts_Grants__c = 0;
        grant.G_Org_Individual_contributions_grants__c = 0;
        grant.G_Org_Corporate_Cont_Grants_Fees__c = 0;
        grant.G_Org_Foundation_Cont_Grants_Fees__c = 0;
        grant.G_Org_Membership_Dues_Fees__c = 80;
        grant.G_Org_Investment_Interest_Tax_Rev__c = 0;
        grant.G_Org_Earned_Revenue__c = 0;
        grant.G_Org_United_Way__c = 20;
        grant.G_Org_Other__c = 0;
        
        ce_grant.gr18();
        
        ce_grant.gr19();
        
        ce_grant.grcert();
        //
        ce_grant.gr21();
        ce_grant.thisappcontactemail = 'tusken6@cox.net';

        attachment attachment = new attachment();
      //List<Attachment> attachlist = new list<Attachment>();
        attachment.Name = 'attach test attach test';
        blob bodystuff = blob.valueOf('attach test attach test');
        attachment.body = bodystuff;
        
      //attachlist.add(attachment);
        ce_grant.attachment = attachment;
        ce_grant.attach();         
        ce_grant.delete25attachments();
        
        ce_grant.submit();
        
    } 
    @isTest
    static void grantApplicationFormController_Test2() {
        FIC_Survey_Application__c grant2 = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant2 = new ApexPages.standardController(grant2);
        grantApplicationForm_Controller ce_grant2 = new grantApplicationForm_Controller(sc_grant2);
        
        ce_grant2.beginApp();
        grant2.Tax_id__c = '11-1111111';
        Insert grant2;
        ce_grant2.returnedtosignin = true;
        ce_grant2.signin();

        ce_grant2.gr13();
        
        grant2.Name_of_Organization__c = 'Taz Spinning School';
        grant2.G_Name_of_Organization_W_9__c = 'Taz Spinning School';
        grant2.Organization_Street_Address__c = '43 E Alameda Ave';
        grant2.Organization_City__c = 'Los Angeles';
        grant2.Organization_State__c = 'California';
        grant2.Organization_Zip__c = '90210';
        grant2.Non_Profit_Status__c = '501C(3)';
        grant2.Mission_Statement__c = 'LASKJET';
        grant2.Executive_Director__c = 'asletkj';
        grant2.Executive_Director_Email_Address__c = 'salkejt@asdtlkj.com';
        grant2.Executive_Director_Phone_Number__c = '4025551213';
        grant2.Grant_Contact_Name__c = 'slakejt';
        grant2.Grant_Contact_Email__c = 'aseltkj@asetlkj.com';
        grant2.Grant_Contact_Phone__c = '4025551212';
        grant2.G_Organization_Facebook__c = 'NA';
        grant2.G_Organization_Twitter_Handle__c = 'NA';
        grant2.G_Organization_Instagram_Handle__c = 'NA';
        grant2.G_Other_Social_Media_Accounts__c = 'NA';
        
        ce_grant2.gr13();
        
        grant2.Program_Event_Name__c = 'Spin Til you drop';
        grant2.Program_Event_Description__c = 'slakjt';
        grant2.Amount_Requested__c = 50000;
        grant2.G_Years_Program_Operated__c = 10;
        grant2.G_Primary_County_Served__c = 'laskdj';
        grant2.G_Secondary_County_Served__c = 'jklastlk';
        
        ce_grant2.gr15();  

        grant2.G_Stable_Housing__c = TRUE;
        
        ce_grant2.gr17();

        grant2.G_Educated_Workforce__c = TRUE;
        
        ce_grant2.gr17();

        grant2.G_Strong_Local_Economies__c = TRUE;
        
        ce_grant2.gr17();
        
        grant2.G_Funding_Primarily_Serve_Youth__c = 'Yes';
        grant2.G_Medicaid_Eligibility_for_Program__c = 'Yes';
        grant2.G_Income_Thresholds_to_be_Eligible__c = 'Yes';
        grant2.G_Geographical_Radius_of_Organization__c = 'Yes';
        grant2.G_Small_Businesses_or_Small_Farms__c = 'Yes';
        grant2.G_Low_or_Moderate_Income_Neighborhood__c = 'Yes';
        grant2.G_Track_Income_Information__c = 'Yes';
         
        ce_grant2.grcert();
    }
    @isTest
    static void grantApplicationFormController_TestSignInReturn() {
        FIC_Survey_Application__c grant3 = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant3 = new ApexPages.standardController(grant3);
        grantApplicationForm_Controller ce_grant3 = new grantApplicationForm_Controller(sc_grant3);
        
        ce_grant3.beginApp();
        grant3.Tax_id__c = '11-1111111';
        Insert grant3;
        ce_grant3.GrantID = grant3.id;
        ce_grant3.returnedtosignin = true;
        ce_grant3.thisapptaxid = '22-2222222';
        ce_grant3.thisappprevioustaxid = '22-2222222';
        ce_grant3.thisappcontactemail = 'KoshiKawa@gmail.com';
        ce_grant3.thisapppreviouscontactemail = 'BeneHana@yahoo.com';
        ce_grant3.thisappmarket = 'Omaha';
        ce_grant3.thisappprevmarket = 'Omaha';
        ce_grant3.signin();
    }    
    @isTest
    static void grantApplicationFormController_TestSignIn() {
        FIC_Survey_Application__c grant4 = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant4 = new ApexPages.standardController(grant4);
        grantApplicationForm_Controller ce_grant4 = new grantApplicationForm_Controller(sc_grant4);
        
        ce_grant4.beginApp();
        grant4.Tax_id__c = '11-1111111';
        Insert grant4;
        ce_grant4.GrantID = grant4.id;
        ce_grant4.returnedtosignin = false;
        ce_grant4.thisapptaxid = '22-2222222';
        ce_grant4.thisappprevioustaxid = '22-2222222';
        ce_grant4.thisappcontactemail = 'KoshiKawa@gmail.com';
        ce_grant4.thisapppreviouscontactemail = 'BeneHana@yahoo.com';
        ce_grant4.thisappmarket = 'Omaha';
        ce_grant4.thisappprevmarket = 'Omaha';
        ce_grant4.signin();
        
    }
    @isTest
    static void grantApplicationFormController_TestSaveForLater() {
        FIC_Survey_Application__c grant5 = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant5 = new ApexPages.standardController(grant5);
        grantApplicationForm_Controller ce_grant5 = new grantApplicationForm_Controller(sc_grant5);
        
        ce_grant5.beginApp();
        grant5.Tax_id__c = '11-1111111';
        Insert grant5;
        PageReference myVfPage = Page.gr15;
        myVfPage.getParameters().put('id',grant5.id);
        Test.setCurrentPage(myVfPage); 
        String id = ApexPages.currentPage().getParameters().get('id');
        ce_grant5.SaveForLater();
      //ce_grant5.WhereWereWe = 'gr15';
        ce_grant5.purpose_choice = 'stablehousing';
        ce_grant5.SaveForLater();
        ce_grant5.purpose_choice = 'stronglocal';
        ce_grant5.SaveForLater();
        ce_grant5.purpose_choice = 'revitalize';
        ce_grant5.SaveForLater();
        ce_grant5.purpose_choice = 'educwrkfrce';
        ce_grant5.SaveForLater();
        
    }
    @isTest
    static void grantApplicationFormController_TestBack() {
        FIC_Survey_Application__c grant6 = new FIC_Survey_Application__c();
        
        ApexPages.StandardController sc_grant6 = new ApexPages.standardController(grant6);
        grantApplicationForm_Controller ce_grant6 = new grantApplicationForm_Controller(sc_grant6);
        
        ce_grant6.beginApp();
        grant6.Tax_id__c = '11-1111111';
        Insert grant6;
        PageReference myVfPage = Page.gr15;
        myVfPage.getParameters().put('id',grant6.id);
        Test.setCurrentPage(myVfPage); 
        String id = ApexPages.currentPage().getParameters().get('id');
        ce_grant6.Back();
        ce_grant6.purpose_choice = 'stablehousing';
        ce_grant6.Back();
        ce_grant6.purpose_choice = 'stronglocal';
        ce_grant6.Back();
        ce_grant6.purpose_choice = 'revitalize';
        ce_grant6.Back();
        ce_grant6.purpose_choice = 'educwrkfrce';
        ce_grant6.Back();
        
    }                
}