force-app/main/default/objects/PrecisionLenderShowField__c/PrecisionLenderShowField__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Precision Lender Show Field</label>
</CustomObject>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Average_Assets__c.field-meta.xml
<CustomField>
    <fullName>Average_Assets__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Average Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Current_Deposit_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Deposit_Balance__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Current Deposit Balance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Current_Loan_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Current Loan Balance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_Interest_Expense__c.field-meta.xml
<CustomField>
    <fullName>FTP_Interest_Expense__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP Interest Expense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_Interest_Income__c.field-meta.xml
<CustomField>
    <fullName>FTP_Interest_Income__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP Interest Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_Net_Income__c.field-meta.xml
<CustomField>
    <fullName>FTP_Net_Income__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP Net Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_ROA__c.field-meta.xml
<CustomField>
    <fullName>FTP_ROA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP ROA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_ROE__c.field-meta.xml
<CustomField>
    <fullName>FTP_ROE__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP ROE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/FTP_Target_ROE__c.field-meta.xml
<CustomField>
    <fullName>FTP_Target_ROE__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FTP Target ROE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Loan_Average_Balance__c.field-meta.xml
<CustomField>
    <fullName>Loan_Average_Balance__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Loan Average Balance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Total_Loan_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Commitment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Total Loan Commitment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Total_Relationship_FTP_Net_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Relationship_FTP_Net_Income__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Total Relationship FTP Net Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Total_Relationship_FTP_ROA__c.field-meta.xml
<CustomField>
    <fullName>Total_Relationship_FTP_ROA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Total Relationship FTP ROA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Total_Relationship_FTP_ROE__c.field-meta.xml
<CustomField>
    <fullName>Total_Relationship_FTP_ROE__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Total Relationship FTP ROE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrecisionLenderShowField__c/fields/Total_Relationship_FTP_Target_ROE__c.field-meta.xml
<CustomField>
    <fullName>Total_Relationship_FTP_Target_ROE__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Total Relationship FTP Target ROE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PrecisionLenderShowFieldController.cls
public class PrecisionLenderShowFieldController {	   
    @AuraEnabled
    public static List<Account> getFieldValues(Id acctId)
    {
        List<Account> PLFieldValues = [SELECT PLNDR__FS_Loan_Average_Balance__c,
            PLNDR__FS_Average_Assets__c,
            PLNDR__Total_Loan_Commitment__c,
            PLNDR__Current_Deposit_Balance__c,
            PLNDR__Current_Loan_Balance__c,
            PLNDR__FTPFS_Net_Income__c,
            PLNDR__FTPFS_ROA__c,
            PLNDR__FTPFS_ROE__c,
            PLNDR__FTPFS_Target_ROE__c,
            PLNDR__FTPFS_Interest_Income__c,
            PLNDR__FTPFS_Interest_Expense__c,
            PLNDR__Total_relationship_FTP_Net_Income__c,
            PLNDR__Total_Relationship_FTP_ROA__c,
            PLNDR__Total_Relationship_FTP_ROE__c,
            PLNDR__Total_Relationship_FTP_Target_ROE__c FROM Account WHERE Id = :acctId];
        return PLFieldValues;
    }
    
    @AuraEnabled
    public static List<PrecisionLenderShowField__C> getPLSetup()
    {
        List<PrecisionLenderShowField__C> Setup = [SELECT Average_Assets__c, Current_Deposit_Balance__c, Current_Loan_Balance__c, FTP_Interest_Expense__c,
                                                  FTP_Interest_Income__c, FTP_Net_Income__c, FTP_ROA__c, FTP_ROE__c, FTP_Target_ROE__c, Loan_Average_Balance__c,
                                                  Total_Loan_Commitment__c, Total_Relationship_FTP_Net_Income__c, Total_Relationship_FTP_ROA__c,
                                                  Total_Relationship_FTP_ROE__c, Total_Relationship_FTP_Target_ROE__c FROM PrecisionLenderShowField__C];
        return Setup;
    }
    
}